import type {AuditEvent} from '@healthcare/audit';

export type LocalizedText={ar?:string;en?:string};
export type MedicationErrorStatus='draft'|'submitted'|'triage'|'under_investigation'|'awaiting_information'|'awaiting_approval'|'approved'|'follow_up'|'verified'|'closed'|'reopened';
export type IncidentType='incident'|'near_miss'|'no_harm'|'harm'|'sentinel_event';
export type MedicationStage='prescribing'|'transcribing'|'dispensing'|'preparation'|'administration'|'monitoring'|'storage'|'other';
export type NccMerpCategory='A'|'B'|'C'|'D'|'E'|'F'|'G'|'H'|'I';
export type Severity='low'|'moderate'|'high'|'critical';
export type TenantScope={tenantId:string;organizationId:string;facilityId?:string};
export type MedicationErrorAttachment=TenantScope&{id:string;reportId:string;kind:'photo'|'file'|'evidence';fileName:string;contentType:string;storageKey?:string;uploadedAt:string;uploadedBy:string;placeholder:boolean};
export type MedicationErrorComment=TenantScope&{id:string;reportId:string;body:string;language:'ar'|'en';visibility:'team'|'confidential';authorId:string;createdAt:string};
export type MedicationErrorAssignment={ownerId?:string;reviewerId?:string;dueAt?:string;reassignedAt?:string;reason?:string};
export type MedicationErrorRevision=TenantScope&{id:string;reportId:string;revision:number;changedBy:string;changedAt:string;reason:string;snapshot:unknown};
export type MedicationErrorReport=TenantScope&{id:string;referenceNumber:string;status:MedicationErrorStatus;revision:number;incidentType:IncidentType;nccMerpCategory?:NccMerpCategory;severity:Severity;outcome?:string;medicationStage:MedicationStage;occurredAt:string;reportedAt:string;reportedBy:string;departmentId?:string;title:string;description:string;immediateAction?:string;contributingFactors:string[];errorCategories:string[];riskScore:number;witnessInformation?:string;reviewerNotes?:string;managerNotes?:string;qualityNotes?:string;pharmacyNotes?:string;assignment:MedicationErrorAssignment;investigation?:string;rootCauseAnalysis?:string;correctiveActions?:string;preventiveActions?:string;followUp?:string;verification?:string;closureNotes?:string;submittedAt?:string;approvedAt?:string;approvedBy?:string;closedAt?:string;reopenedAt?:string;attachments:MedicationErrorAttachment[];comments:MedicationErrorComment[]};
export const medicationErrorPermissions=['medication_errors.view','medication_errors.create','medication_errors.edit_draft','medication_errors.submit','medication_errors.review','medication_errors.assign','medication_errors.approve','medication_errors.close','medication_errors.reopen','medication_errors.export','medication_errors.manage_configuration'] as const;
export type MedicationErrorPermission=(typeof medicationErrorPermissions)[number];
export const medicationErrorTransitions:Record<MedicationErrorStatus,ReadonlyArray<MedicationErrorStatus>>={draft:['submitted'],submitted:['triage','awaiting_information'],triage:['under_investigation','awaiting_information'],under_investigation:['awaiting_information','awaiting_approval','follow_up'],awaiting_information:['triage','under_investigation'],awaiting_approval:['approved'],approved:['follow_up'],follow_up:['verified','under_investigation'],verified:['closed','under_investigation'],closed:['reopened'],reopened:['triage','under_investigation']};
export function canTransition(from:MedicationErrorStatus,to:MedicationErrorStatus){return medicationErrorTransitions[from].includes(to)}
export function requiredFieldsMissing(report:MedicationErrorReport){const missing:string[]=[];for(const key of ['title','description','occurredAt','reportedBy'] as const)if(!report[key])missing.push(key);if(report.riskScore<0||report.riskScore>25)missing.push('riskScore');if(report.status==='submitted'&&!report.nccMerpCategory)missing.push('nccMerpCategory');return missing}
export function transitionReport(report:MedicationErrorReport,to:MedicationErrorStatus,actorId:string,reason?:string):MedicationErrorReport{if(!canTransition(report.status,to))throw new Error(`Invalid medication error transition: ${report.status} -> ${to}`);if(to==='submitted'&&requiredFieldsMissing({...report,status:'submitted'}).length)throw new Error('Required report fields are incomplete');if(to==='closed'&&(!report.approvedAt||!report.verification||!report.closureNotes))throw new Error('Closure requires approval, verification, and closure notes');if(to==='reopened'&&!reason)throw new Error('Reopening requires a reason');const now=new Date().toISOString();return {...report,status:to,submittedAt:to==='submitted'?now:report.submittedAt,approvedAt:to==='approved'?now:report.approvedAt,approvedBy:to==='approved'?actorId:report.approvedBy,closedAt:to==='closed'?now:report.closedAt,reopenedAt:to==='reopened'?now:report.reopenedAt,assignment:{...report.assignment,reason:reason??report.assignment.reason}}}
export function createRevision(report:MedicationErrorReport,actorId:string,reason:string):MedicationErrorRevision{if(report.status==='draft')throw new Error('Draft reports are edited without a submitted revision');return {id:`${report.id}-revision-${report.revision+1}`,tenantId:report.tenantId,organizationId:report.organizationId,facilityId:report.facilityId,reportId:report.id,revision:report.revision+1,changedBy:actorId,changedAt:new Date().toISOString(),reason,snapshot:structuredClone(report)}}
export const protectedClinicalFields=['incidentType','nccMerpCategory','severity','outcome','medicationStage','occurredAt','departmentId','title','description','immediateAction','contributingFactors','errorCategories','riskScore','witnessInformation','investigation','rootCauseAnalysis','correctiveActions','preventiveActions','followUp','verification','closureNotes'] as const;
export function canReadReport(report:MedicationErrorReport,actorId:string,permissions:readonly MedicationErrorPermission[]){return report.status==='draft'?report.reportedBy===actorId&&permissions.includes('medication_errors.edit_draft'):permissions.includes('medication_errors.view')}
export function shouldUseDemoDraftStorage(options:{demoMode:boolean;hasSupabasePersistence:boolean;production:boolean}){return options.demoMode&&!options.hasSupabasePersistence&&!options.production}
export const medicationErrorAuditActions=['report.draft_saved','report.submitted','report.reviewed','report.assigned','report.approved','report.reopened','report.closed','report.revised','comment.created','attachment.requested','capa.requested'] as const;
export type MedicationErrorAuditEvent=AuditEvent&{action:(typeof medicationErrorAuditActions)[number]};
export type CapaIntegrationContract={sourceType:'medication_error';sourceId:string;summary:string;createCapa:()=>Promise<never>};
export type NotificationContract={kind:'assignment'|'reminder'|'escalation'|'feedback';reportId:string;recipientId:string;send:()=>Promise<never>};
export type MedicationErrorExportContract={format:'csv'|'excel'|'json'|'pdf';language:'ar'|'en'|'bilingual';filters:Record<string,unknown>};
export type MedicationErrorImportContract={format:'csv'|'excel'|'json';mode:'create'|'append'|'merge';mapping:Record<string,string>};
