'use client';
import {useEffect,useMemo,useState} from 'react';
import {useTranslations} from 'next-intl';
import {requiredFieldsMissing,shouldUseDemoDraftStorage,transitionReport,type MedicationErrorReport} from '@healthcare/medication-errors';
import {hasSupabasePublicConfig} from '@/lib/env';
import {demoMedicationError,medicationErrorRepository} from '@/features/medication-errors/repository';
const storageKey='medication-error-demo-draft'; const scope={tenantId:'demo-tenant',organizationId:'demo-organization',facilityId:'demo-facility'};
export function MedicationErrorWorkspace({view}:{view:'dashboard'|'report'|'reports'}){
 const t=useTranslations('medicationErrors');const demoMode=shouldUseDemoDraftStorage({demoMode:true,hasSupabasePersistence:hasSupabasePublicConfig,production:process.env.NODE_ENV==='production'});const [reports,setReports]=useState<MedicationErrorReport[]>([]);const [report,setReport]=useState(demoMedicationError);const [query,setQuery]=useState('');const [status,setStatus]=useState('all');const [sort,setSort]=useState('newest');const [saved,setSaved]=useState(false);
 useEffect(()=>{medicationErrorRepository.list().then(setReports);if(!demoMode)return;try{const raw=localStorage.getItem(storageKey);if(raw)setReport(JSON.parse(raw));}catch{localStorage.removeItem(storageKey)}},[demoMode]);
 useEffect(()=>{if(!demoMode)return;localStorage.setItem(storageKey,JSON.stringify(report));setSaved(true)},[demoMode,report]);
 const shown=useMemo(()=>[...reports].filter(item=>(status==='all'||item.status===status)&&`${item.referenceNumber} ${item.title}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>sort==='risk'?b.riskScore-a.riskScore:b.occurredAt.localeCompare(a.occurredAt)),[reports,query,status,sort]);const update=<K extends keyof MedicationErrorReport>(key:K,value:MedicationErrorReport[K])=>setReport(current=>({...current,[key]:value}));const submit=()=>{try{const next=transitionReport(report,'submitted',report.reportedBy);setReport(next);setReports(current=>[...current.filter(item=>item.id!==next.id),next])}catch{setSaved(false)}};
 if(view==='dashboard')return <section className="page"><h1>{t('dashboard')}</h1><p>{t('demoNotice')}</p><div className="ui-grid">{[['drafts',reports.filter(x=>x.status==='draft').length],['open',reports.filter(x=>x.status!=='closed').length],['highRisk',reports.filter(x=>x.riskScore>=15).length]].map(([key,value])=><article className="ui-card" key={String(key)}><strong>{t(String(key))}</strong><p>{value}</p></article>)}</div></section>;
 if(view==='reports')return <section className="page"><h1>{t('reports')}</h1><p>{t('demoNotice')}</p><input value={query} onChange={event=>setQuery(event.target.value)} placeholder={t('search')}/><select value={status} onChange={event=>setStatus(event.target.value)}><option value="all">{t('all')}</option><option value="draft">{t('draft')}</option><option value="submitted">{t('submitted')}</option></select><select value={sort} onChange={event=>setSort(event.target.value)}><option value="newest">{t('newest')}</option><option value="risk">{t('riskScore')}</option></select>{shown.map(item=><article className="ui-card" key={item.id}><strong>{item.referenceNumber}</strong><p>{item.title||t('untitled')} · {t(item.status)} · {item.riskScore}</p></article>)}</section>;
 if(!demoMode)return <section className="page"><h1>{t('newReport')}</h1><p>{t('securePersistenceUnavailable')}</p></section>;
 return <section className="page"><h1>{t('newReport')}</h1><p>{t('autosave')}: {saved?t('saved'):t('saving')}</p><input value={report.title} placeholder={t('title')} onChange={event=>update('title',event.target.value)}/><textarea value={report.description} placeholder={t('description')} onChange={event=>update('description',event.target.value)}/><select value={report.incidentType} onChange={event=>update('incidentType',event.target.value as MedicationErrorReport['incidentType'])}>{['incident','near_miss','no_harm','harm','sentinel_event'].map(value=><option key={value} value={value}>{t(value)}</option>)}</select><select value={report.medicationStage} onChange={event=>update('medicationStage',event.target.value as MedicationErrorReport['medicationStage'])}>{['prescribing','transcribing','dispensing','preparation','administration','monitoring','storage','other'].map(value=><option key={value} value={value}>{t(value)}</option>)}</select><input type="number" min="0" max="25" value={report.riskScore} aria-label={t('riskScore')} onChange={event=>update('riskScore',Number(event.target.value))}/><p>{requiredFieldsMissing(report).length?t('incomplete'):t('ready')}</p><button onClick={submit}>{t('submit')}</button><button onClick={()=>setReport(current=>({...current,comments:[...current.comments,{...scope,id:crypto.randomUUID(),reportId:current.id,body:t('commentPlaceholder'),language:'en',visibility:'team',authorId:current.reportedBy,createdAt:new Date().toISOString()}]}))}>{t('addComment')}</button><p>{t('attachmentsPlaceholder')}</p></section>;
}
