'use client';

import {useMemo, useState} from 'react';
import {useLocale, useTranslations} from 'next-intl';
import {canTransitionPolicy, createDraftPolicyVersion, type PolicyDefinition, type PolicyStatus, type PolicyVersion} from '@healthcare/policies-procedures';

const scope={tenantId:'demo-tenant',organizationId:'demo-organization',facilityId:'demo-facility'};
const initialDefinitions: PolicyDefinition[]=[{...scope,id:'policy-1',policyId:'POL-001',policyNumber:'POL-001',ownerId:'demo-owner',status:'published',currentVersionId:'policy-v1',title:{ar:'سلامة استخدام الأدوية',en:'Medication Safety'},related:[]}];
const initialVersions: PolicyVersion[]=[{...scope,id:'policy-v1',policyId:'policy-1',versionMajor:1,versionMinor:0,status:'published',title:{ar:'سلامة استخدام الأدوية',en:'Medication Safety'},description:{ar:'إجراء تجريبي لإدارة السياسات.',en:'Demonstration policy-management procedure.'},contentLanguage:'bilingual',changeSummary:'Initial publication',keywords:['medication','safety'],tags:['quality'],createdBy:'demo-owner',createdAt:'2026-07-13T00:00:00.000Z',publishedAt:'2026-07-13T00:00:00.000Z',publishedBy:'demo-approver'}];

export function PoliciesWorkspace({view}:{view:'library'|'dashboard'}) {
  const t=useTranslations('policies'); const locale=useLocale() as 'ar'|'en'; const [definitions,setDefinitions]=useState(initialDefinitions); const [versions,setVersions]=useState(initialVersions); const [query,setQuery]=useState(''); const [status,setStatus]=useState<'all'|PolicyStatus>('all'); const [notice,setNotice]=useState('');
  const rows=useMemo(()=>definitions.filter(item=>(status==='all'||item.status===status)&&`${item.policyNumber} ${item.title.ar??''} ${item.title.en??''}`.toLowerCase().includes(query.toLowerCase())),[definitions,query,status]);
  const label=(item:PolicyDefinition|PolicyVersion)=>item.title[locale]??item.title.en??item.title.ar??t('untitled');
  const makeVersion=(definition:PolicyDefinition)=>{const published=versions.find(item=>item.id===definition.currentVersionId);if(!published)return;const draft=createDraftPolicyVersion(definition,published,'demo-owner',t('demoChangeSummary'));setVersions(current=>[...current,draft]);setDefinitions(current=>current.map(item=>item.id===definition.id?{...item,status:'draft'}:item));setNotice(t('versionCreated'));};
  if(view==='dashboard'){const published=definitions.filter(item=>item.status==='published').length;return <section className="page"><h1>{t('dashboard')}</h1><p>{t('demoNotice')}</p><div className="ui-grid">{[['published',published],['drafts',definitions.filter(item=>item.status==='draft').length],['upcomingReviews',1],['readCompletion','100%']].map(([key,value])=><article className="ui-card" key={String(key)}><strong>{t(String(key))}</strong><p>{value}</p></article>)}</div></section>}
  return <section className="page"><h1>{t('library')}</h1><p>{t('demoNotice')}</p>{notice&&<p role="status">{notice}</p>}<div className="controls"><input aria-label={t('search')} value={query} onChange={event=>setQuery(event.target.value)} placeholder={t('search')}/><select aria-label={t('status')} value={status} onChange={event=>setStatus(event.target.value as 'all'|PolicyStatus)}>{['all','draft','under_review','approved','published','superseded','archived'].map(value=><option value={value} key={value}>{t(value)}</option>)}</select></div>{rows.map(definition=>{const version=versions.find(item=>item.id===definition.currentVersionId)??versions.find(item=>item.policyId===definition.id);return <article className="ui-card" key={definition.id}><h2>{label(definition)}</h2><p>{definition.policyNumber} · {t(definition.status)} · {t('owner')}: {definition.ownerId}</p>{version&&<p>{t('version')}: {version.versionMajor}.{version.versionMinor}</p>}<div className="controls"><button onClick={()=>setNotice(`${t('preview')}: ${label(definition)}`)}>{t('preview')}</button><button disabled={definition.status!=='published'} onClick={()=>makeVersion(definition)}>{t('createVersion')}</button><button disabled={!canTransitionPolicy(definition.status,'archived')} onClick={()=>setDefinitions(current=>current.map(item=>item.id===definition.id?{...item,status:'archived'}:item))}>{t('archive')}</button></div></article>})}</section>;
}
