export type Localized={ar?:string;en?:string}; export type WorkflowVersionStatus='draft'|'under_review'|'approved'|'published'|'archived'; export type WorkflowTaskStatus='open'|'assigned'|'in_progress'|'blocked'|'pending_verification'|'completed'|'reopened'|'cancelled';
export type WorkflowScope={tenantId:string;organizationId:string;facilityId?:string};
export type WorkflowCondition={field:string;operator:'equals'|'not_equals'|'contains'|'greater_than'|'less_than'|'date_overdue'|'has_role'|'has_permission'|'department'|'facility'|'severity_threshold'|'risk_threshold'|'ncc_merp_threshold'|'finding_critical'|'approval_status'|'task_status';value?:string|number|boolean};
export type WorkflowAction={kind:'assign_user'|'assign_role'|'assign_department'|'create_task'|'request_approval'|'set_due_date'|'timeline'|'audit'|'notification'|'reminder'|'escalate'|'lock'|'unlock'|'capa_request'|'update_allowlisted_field'|'follow_up';configuration:Record<string,unknown>};
export type WorkflowState={key:string;label:Localized;colorToken:string;displayOrder:number;initial:boolean;terminal:boolean;readOnly:boolean;requiresAssignment:boolean;requiresApproval:boolean;allowedRoles:string[];allowedPermissions:string[];sla?:{dueInMinutes?:number;warningPercent?:number;escalationPercent?:number}};
export type WorkflowTransition={key:string;from:string;to:string;label:Localized;requiredPermission?:string;allowedRoles:string[];requiredFields:string[];conditions:WorkflowCondition[];requiresReason:boolean;requiresComment:boolean;requiresAttachment:boolean;requiresApproval:boolean;confirmation?:Localized;actions:WorkflowAction[];auditAction:string;notificationEvents:string[]};
export type WorkflowDefinition=WorkflowScope&{id:string;moduleKey:string;name:Localized;description?:Localized;tags:string[];ownerId:string;status:WorkflowVersionStatus;currentVersionId?:string;effectiveDate?:string;reviewDate?:string};
export type WorkflowVersion=WorkflowScope&{id:string;definitionId:string;version:number;status:WorkflowVersionStatus;states:WorkflowState[];transitions:WorkflowTransition[];createdAt:string;createdBy:string};
export type WorkflowInstance=WorkflowScope&{id:string;workflowVersionId:string;sourceType:string;sourceId:string;state:string;locked:boolean;revision:number;assigneeId?:string;dueAt?:string;createdAt:string;createdBy:string};
export type WorkflowEvent=WorkflowScope&{id:string;instanceId:string;kind:'system'|'transition'|'assignment'|'approval'|'escalation'|'sla'|'task'|'comment';action:string;createdAt:string;createdBy?:string;metadata?:Record<string,unknown>};
export type WorkflowTask=WorkflowScope&{id:string;instanceId:string;title:Localized;description?:Localized;assigneeId?:string;dueAt?:string;priority:'low'|'medium'|'high'|'critical';status:WorkflowTaskStatus;completionNotes?:string;verifiedBy?:string};
export type WorkflowApproval=WorkflowScope&{id:string;instanceId:string;sequence:number;mode:'single'|'sequential'|'parallel'|'any_one'|'unanimous';approverId?:string;requiredRole?:string;status:'requested'|'approved'|'rejected'|'changes_requested';distinctFromId?:string;comment?:string;dueAt?:string};
export type WorkflowComment=WorkflowScope&{id:string;instanceId:string;body:string;visibility:'team'|'confidential';createdBy:string;createdAt:string}; export type WorkflowReminder=WorkflowScope&{id:string;instanceId:string;channel:'in_app'|'email'|'sms_placeholder'|'push_placeholder'|'webhook_placeholder';kind:'before_due'|'at_due'|'overdue'|'escalation';minimumIntervalMinutes:number};
export type WorkflowApprovalMode='single'|'sequential'|'parallel'|'any_one'|'unanimous'; export type WorkflowApprovalDecision='requested'|'approved'|'rejected'|'changes_requested'; export type ApprovalVote={sequence:number;mode:WorkflowApprovalMode;status:WorkflowApprovalDecision};
export const workflowPermissions=['workflows.view','workflows.start','workflows.transition','workflows.assign','workflows.reassign','workflows.approve','workflows.reject','workflows.manage_definitions','workflows.publish','workflows.archive','workflows.manage_sla','workflows.manage_escalations','workflows.view_confidential_comments','workflows.manage_tasks','workflows.verify_tasks'] as const; export type WorkflowPermission=(typeof workflowPermissions)[number];
export function transitionAllowed(version:WorkflowVersion,instance:WorkflowInstance,to:string,permissions:readonly string[],fields:Record<string,unknown>,reason?:string){const transition=version.transitions.find(item=>item.from===instance.state&&item.to===to);if(!transition)throw new Error('Invalid workflow transition');if(transition.requiredPermission&&!permissions.includes(transition.requiredPermission))throw new Error('Workflow permission denied');if(transition.requiresReason&&!reason)throw new Error('Workflow reason required');if(transition.requiredFields.some(field=>fields[field]===undefined||fields[field]===null||fields[field]===''))throw new Error('Workflow required field missing');return transition}
export function createDraftWorkflowVersion(definition:WorkflowDefinition,published:WorkflowVersion,actorId:string):WorkflowVersion{if(definition.status!=='published'||published.status!=='published')throw new Error('Only published workflows create protected draft versions');return structuredClone({...published,id:`${published.id}-draft-${published.version+1}`,version:published.version+1,status:'draft',createdAt:new Date().toISOString(),createdBy:actorId})}
export function slaOverdue(dueAt?:string,now=new Date()){return Boolean(dueAt&&new Date(dueAt)<now)} export function escalationEligible(dueAt:string,minimumIntervalMinutes:number,lastEscalatedAt?:string,now=new Date()){return new Date(dueAt)<now&&(!lastEscalatedAt||now.getTime()-new Date(lastEscalatedAt).getTime()>=minimumIntervalMinutes*60000)}
export function approvalSatisfied(mode:WorkflowApprovalMode,votes:readonly ApprovalVote[]){if(!votes.length)return false;if(votes.some(v=>v.status==='rejected'||v.status==='changes_requested'))return false;if(mode==='single'||mode==='any_one')return votes.some(v=>v.status==='approved');return votes.every(v=>v.status==='approved')}
export function approvalMayVote(vote:ApprovalVote,votes:readonly ApprovalVote[]){return vote.status==='requested'&&(vote.mode!=='sequential'||!votes.some(item=>item.mode==='sequential'&&item.sequence<vote.sequence&&item.status!=='approved'))}
export function taskTransitionAllowed(from:WorkflowTaskStatus,to:WorkflowTaskStatus,actor:'assignee'|'verifier'|'manager',notes?:string){const needsNotes=(to==='pending_verification'||to==='reopened'||to==='cancelled');if(needsNotes&&!notes?.trim())return false;if(to==='pending_verification')return actor==='assignee'&&['assigned','in_progress','reopened'].includes(from);if(to==='completed')return actor==='verifier'&&from==='pending_verification';if(to==='reopened')return actor==='manager'&&['pending_verification','completed'].includes(from);if(to==='cancelled')return actor==='manager'&&!['completed','cancelled'].includes(from);return false}
export type MedicationErrorWorkflowAdapter={moduleKey:'medication_errors';mapStatus:(status:string)=>string}; export const medicationErrorWorkflowAdapter:MedicationErrorWorkflowAdapter={moduleKey:'medication_errors',mapStatus:status=>status}; export type InspectionWorkflowAdapter={moduleKey:'inspections';events:readonly ['started','draft','submitted','under_review','approved','findings_follow_up','closed','reopened']}; export const inspectionWorkflowAdapter:InspectionWorkflowAdapter={moduleKey:'inspections',events:['started','draft','submitted','under_review','approved','findings_follow_up','closed','reopened']};
