'use client';

import {useEffect,useState} from 'react';
import {useTranslations} from 'next-intl';
import {createEmptyField,duplicateBuilderField,emptyBuilderDraft,formDraftStorageKey,isFormEditable,moveBuilderField,recoverBuilderDraft,removeBuilderField,serializeBuilderDraft,supportedFieldTypes,type BuilderDraft,type BuilderField,type ConfidentialityLevel,type ContentLanguage,updateBuilderField} from '@/features/administration/form-builder-utils';

const languageKeys:Record<ContentLanguage,string>={arabic:'languageArabic',english:'languageEnglish',bilingual:'languageBilingual'};
const fieldTypeKey=(type:string)=>`fieldType${type.split('_').map(part=>part[0].toUpperCase()+part.slice(1)).join('')}`;

export function FormBuilder(){
  const t=useTranslations('administration');
  const [draft,setDraft]=useState<BuilderDraft>(emptyBuilderDraft); const [autosaved,setAutosaved]=useState(false); const [saved,setSaved]=useState(false);
  const editable=isFormEditable('draft');
  useEffect(()=>{const stored=localStorage.getItem(formDraftStorageKey);const recovered=recoverBuilderDraft(stored);if(stored&&recovered.fields.length===0&&stored!==serializeBuilderDraft(emptyBuilderDraft()))localStorage.removeItem(formDraftStorageKey);setDraft(recovered)},[]);
  useEffect(()=>{localStorage.setItem(formDraftStorageKey,serializeBuilderDraft(draft));setAutosaved(true)},[draft]);
  const updateDraft=<K extends keyof BuilderDraft>(key:K,value:BuilderDraft[K])=>setDraft(current=>({...current,[key]:value}));
  const updateField=(id:string,key:keyof BuilderField,value:string|boolean)=>setDraft(current=>updateBuilderField(current,id,key,value));
  const save=()=>{localStorage.setItem(formDraftStorageKey,serializeBuilderDraft(draft));setSaved(true)};
  const previewFields=draft.preview==='arabic'?draft.fields.map(field=>field.ar):draft.preview==='english'?draft.fields.map(field=>field.en):draft.fields.map(field=>`${field.ar} / ${field.en}`);
  return <section className="page"><h1>{t('builder')}</h1><p>{t('placeholder')}</p>
    <div className="ui-toolbar"><label>{t('contentLanguage')}<select value={draft.language} disabled={!editable} onChange={event=>updateDraft('language',event.target.value as ContentLanguage)}>{(Object.keys(languageKeys) as ContentLanguage[]).map(language=><option value={language} key={language}>{t(languageKeys[language])}</option>)}</select></label><label>{t('preview')}<select value={draft.preview} onChange={event=>updateDraft('preview',event.target.value as ContentLanguage)}>{(Object.keys(languageKeys) as ContentLanguage[]).map(language=><option value={language} key={language}>{t(languageKeys[language])}</option>)}</select></label></div>
    <input value={draft.ar} disabled={!editable} placeholder={t('arabicName')} onChange={event=>updateDraft('ar',event.target.value)}/><input value={draft.en} disabled={!editable} placeholder={t('englishName')} onChange={event=>updateDraft('en',event.target.value)}/><input value={draft.descriptionAr} disabled={!editable} placeholder={t('arabicDescription')} onChange={event=>updateDraft('descriptionAr',event.target.value)}/><input value={draft.descriptionEn} disabled={!editable} placeholder={t('englishDescription')} onChange={event=>updateDraft('descriptionEn',event.target.value)}/>
    <button disabled={!editable} onClick={()=>setDraft(current=>({...current,fields:[...current.fields,createEmptyField()]}))}>{t('addField')}</button><button disabled={!editable} onClick={save}>{t('saveDraft')}</button><p>{autosaved?t('localAutosaveActive'):t('localAutosave')}</p>{saved&&<p>{t('localDraftSaved')}</p>}
    {draft.fields.map((field,index)=><article className="ui-card" key={field.id}><label>{t('fieldType')}<select value={field.type} disabled={!editable} onChange={event=>updateField(field.id,'type',event.target.value)}>{supportedFieldTypes.map(type=><option value={type} key={type}>{t(fieldTypeKey(type))}</option>)}</select></label><label>{t('confidentiality')}<select value={field.confidentiality} disabled={!editable} onChange={event=>updateField(field.id,'confidentiality',event.target.value as ConfidentialityLevel)}><option value="normal">{t('confidentialityNormal')}</option><option value="confidential">{t('confidentialityConfidential')}</option><option value="restricted">{t('confidentialityRestricted')}</option></select></label>
      <input value={field.ar} disabled={!editable} placeholder={t('arabicLabel')} onChange={event=>updateField(field.id,'ar',event.target.value)}/><input value={field.en} disabled={!editable} placeholder={t('englishLabel')} onChange={event=>updateField(field.id,'en',event.target.value)}/><input value={field.helpAr} disabled={!editable} placeholder={t('arabicHelp')} onChange={event=>updateField(field.id,'helpAr',event.target.value)}/><input value={field.helpEn} disabled={!editable} placeholder={t('englishHelp')} onChange={event=>updateField(field.id,'helpEn',event.target.value)}/><input value={field.defaultValue} disabled={!editable} placeholder={t('defaultValue')} onChange={event=>updateField(field.id,'defaultValue',event.target.value)}/><input value={field.validation} disabled={!editable} placeholder={t('validationRule')} onChange={event=>updateField(field.id,'validation',event.target.value)}/>
      {(['required','readOnly','searchable','sortable','filterable','exportable','importable'] as const).map(key=><label key={key}><input type="checkbox" checked={field[key]} disabled={!editable} onChange={event=>updateField(field.id,key,event.target.checked)}/>{t(key)}</label>)}
      <button disabled={!editable} onClick={()=>setDraft(current=>({...current,fields:[...current.fields,duplicateBuilderField(field)]}))}>{t('duplicate')}</button><button disabled={!editable} onClick={()=>setDraft(current=>removeBuilderField(current,field.id))}>{t('remove')}</button><button disabled={!editable||index===0} onClick={()=>setDraft(current=>moveBuilderField(current,index,-1))}>{t('up')}</button><button disabled={!editable||index===draft.fields.length-1} onClick={()=>setDraft(current=>moveBuilderField(current,index,1))}>{t('down')}</button>
    </article>)}
    <article className="ui-card"><h2>{draft.preview==='arabic'?t('previewArabic'):draft.preview==='english'?t('previewEnglish'):t('previewBilingual')}</h2>{previewFields.map((label,index)=><p key={`${index}-${label}`}>{label}</p>)}</article>
  </section>;
}
