'use client';

import {useEffect,useMemo,useState} from 'react';
import {useTranslations} from 'next-intl';
import {administrationRepository,demoArchivedRecords,demoDeletionRequest,exportCsvDefinition,exportJsonDefinition,type DemoForm,type ReferenceItem} from '@/features/administration/repository';
import {validatePermanentDeletion} from '@healthcare/platform-administration';

function download(name:string,text:string,type:string){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();window.setTimeout(()=>URL.revokeObjectURL(url),0)}

export function AdministrationWorkspace({view}:{view:'dashboard'|'reference'|'archived'|'deletions'|'imports'|'exports'}){
  const t=useTranslations('administration'); const [forms,setForms]=useState<DemoForm[]>([]); const [items,setItems]=useState<ReferenceItem[]>([]); const [query,setQuery]=useState(''); const [referenceSort,setReferenceSort]=useState('name'); const [confirm,setConfirm]=useState<string|null>(null); const [source,setSource]=useState('csv'); const [mode,setMode]=useState('create');
  useEffect(()=>{administrationRepository.forms().then(setForms);administrationRepository.reference().then(setItems)},[]);
  const metrics=[{label:t('metricForms'),value:forms.length},{label:t('metricDrafts'),value:forms.filter(x=>x.status==='draft').length},{label:t('metricPublished'),value:forms.filter(x=>x.status==='published').length},{label:t('metricArchived'),value:forms.filter(x=>x.status==='archived').length},{label:t('metricReference'),value:items.length},{label:t('metricDeletions'),value:1},{label:t('metricImports'),value:1}];
  const visibleItems=useMemo(()=>[...items].filter(x=>`${x.labelAr} ${x.labelEn} ${x.code}`.toLocaleLowerCase().includes(query.toLocaleLowerCase())).sort((a,b)=>referenceSort==='order'?a.order-b.order:a.labelEn.localeCompare(b.labelEn)),[items,query,referenceSort]);
  const move=(id:string,direction:-1|1)=>setItems(current=>{const index=current.findIndex(x=>x.id===id);const target=index+direction;if(index<0||target<0||target>=current.length)return current;const next=[...current];[next[index],next[target]]=[next[target],next[index]];return next.map((item,i)=>({...item,order:i+1}))});
  const update=(id:string,fn:(item:ReferenceItem)=>ReferenceItem)=>setItems(current=>current.map(item=>item.id===id?fn(item):item));
  if(view==='dashboard')return <section className="page"><h1>{t('title')}</h1><p>{t('placeholder')}</p><div className="ui-grid">{metrics.map(metric=><article className="ui-card" key={metric.label}><strong>{metric.label}</strong><p>{metric.value}</p><small>{t('demoMetric')}</small></article>)}</div></section>;
  if(view==='reference')return <section className="page"><h1>{t('reference')}</h1><p>{t('localDemo')}</p><div className="ui-toolbar"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={t('search')}/><select aria-label={t('sort')} value={referenceSort} onChange={e=>setReferenceSort(e.target.value)}><option value="name">{t('alphabetical')}</option><option value="order">{t('displayOrder')}</option></select><button onClick={()=>setItems(current=>[...current,{id:crypto.randomUUID(),labelAr:t('newReference'),labelEn:t('newReference'),code:`NEW-${current.length+1}`,order:current.length+1,active:true,archived:false,scope:'organization'}])}>{t('add')}</button></div>{visibleItems.map(item=><article className="ui-card" key={item.id}><strong>{item.labelAr} / {item.labelEn}</strong><p>{item.code} · {item.active?t('active'):t('inactive')} · {item.archived?t('archived'):t('current')}</p><button onClick={()=>update(item.id,x=>({...x,labelEn:`${x.labelEn} *`}))}>{t('edit')}</button><button onClick={()=>move(item.id,-1)}>{t('up')}</button><button onClick={()=>move(item.id,1)}>{t('down')}</button><button onClick={()=>update(item.id,x=>({...x,active:!x.active}))}>{item.active?t('deactivate'):t('activate')}</button><button onClick={()=>update(item.id,x=>({...x,archived:!x.archived}))}>{item.archived?t('restore'):t('archive')}</button></article>)}</section>;
  if(view==='archived')return <section className="page"><h1>{t('archived')}</h1><p>{t('localDemo')}</p>{demoArchivedRecords.map(record=><article className="ui-card" key={record.id}><strong>{record.label}</strong><p>{record.type} · {record.archivedAt}</p><button onClick={()=>setConfirm(record.id)}>{t('restore')}</button>{confirm===record.id&&<div role="dialog"><p>{t('restoreConfirmation')}</p><button onClick={()=>setConfirm(null)}>{t('cancel')}</button><button onClick={()=>setConfirm(null)}>{t('confirmRestore')}</button></div>}</article>)}</section>;
  if(view==='deletions'){let valid=true;try{validatePermanentDeletion(demoDeletionRequest)}catch{valid=false}const safeguards:Array<[string,boolean]>=[['reauthenticated',demoDeletionRequest.reauthenticated],['reason',Boolean(demoDeletionRequest.reason)],['typedConfirmation',demoDeletionRequest.typedConfirmation===demoDeletionRequest.recordId],['dependenciesChecked',demoDeletionRequest.dependenciesChecked],['backupConfirmed',demoDeletionRequest.backupConfirmed],['secondApproval',Boolean(demoDeletionRequest.secondApproverId)]];return <section className="page"><h1>{t('deletions')}</h1><p>{t('permanentDisabled')}</p>{safeguards.map(([key,ok])=><p key={key}>{t(`safeguard${key[0].toUpperCase()}${key.slice(1)}`)}: {ok?t('complete'):t('incomplete')}</p>)}<button disabled={!valid}>{t('approveDeletion')}</button></section>}
  if(view==='imports')return <section className="page"><h1>{t('imports')}</h1><p>{t('parsingPlaceholder')}</p><label>{t('source')}<select value={source} onChange={e=>setSource(e.target.value)}><option value="csv">CSV</option><option value="json">JSON</option><option value="excel">Excel</option><option value="google">Google Sheets</option></select></label><label>{t('mode')}<select value={mode} onChange={e=>setMode(e.target.value)}>{['create','append','merge','update','replaceDraft'].map(value=><option key={value} value={value}>{t(`importMode${value[0].toUpperCase()}${value.slice(1)}`)}</option>)}</select></label><input type="file"/><input placeholder={t('sourceUrl')}/><h2>{t('mappingPreview')}</h2><p>{t('mappingPlaceholder')}</p><p>{t('warnings')}: {t('none')}</p><p>{t('errors')}: {t('none')}</p></section>;
  return <section className="page"><h1>{t('exports')}</h1><p>{t('localDemo')}</p><button onClick={()=>download('forms.json',exportJsonDefinition(forms),'application/json')}>{t('downloadJson')}</button><button onClick={()=>download('forms.csv',exportCsvDefinition(forms),'text/csv')}>{t('downloadCsv')}</button><button disabled>{t('excelDisabled')}</button><button disabled>{t('pdfDisabled')}</button></section>;
}
