import 'server-only';
import {createServerUserSupabaseClient} from '@/lib/supabase-server';

export type AdministrationScope={tenantId:string;organizationId?:string|null;facilityId?:string|null};
export class SupabaseAdministrationRepository {
  async listForms(scope:AdministrationScope){const supabase=await createServerUserSupabaseClient();const {data,error}=await supabase.from('form_definitions').select('id,name_ar,name_en,module_key,status,content_language,updated_at,revision').eq('tenant_id',scope.tenantId).is('organization_id',scope.organizationId??null).is('facility_id',scope.facilityId??null).is('deleted_at',null);if(error)throw new Error('Unable to load forms.');return data;}
  async createDraft(scope:AdministrationScope,input:{moduleKey:string;nameAr?:string;nameEn?:string;language:'arabic'|'english'|'bilingual'}){const supabase=await createServerUserSupabaseClient();const {data,error}=await supabase.from('form_definitions').insert({tenant_id:scope.tenantId,organization_id:scope.organizationId??null,facility_id:scope.facilityId??null,module_key:input.moduleKey,name_ar:input.nameAr??null,name_en:input.nameEn??null,content_language:input.language,status:'draft'}).select().single();if(error)throw new Error('Unable to create a form draft.');return data;}
  async archiveForm(scope:AdministrationScope,id:string,revision:number){const supabase=await createServerUserSupabaseClient();const {data,error}=await supabase.from('form_definitions').update({status:'archived',revision:revision+1,archived_at:new Date().toISOString()}).eq('id',id).eq('tenant_id',scope.tenantId).eq('revision',revision).select().maybeSingle();if(error)throw new Error('Unable to archive form.');if(!data)throw new Error('Form changed by another user.');return data;}
  async listReferenceItems(scope:AdministrationScope,groupId:string){const supabase=await createServerUserSupabaseClient();const {data,error}=await supabase.from('reference_data_items').select('*').eq('group_id',groupId).eq('tenant_id',scope.tenantId).is('organization_id',scope.organizationId??null).is('facility_id',scope.facilityId??null).is('deleted_at',null).order('display_order');if(error)throw new Error('Unable to load reference data.');return data;}
}
