export type ReportLanguage='ar'|'en'|'bilingual'; export type ReportStatus='draft'|'under_review'|'approved'|'published'|'archived'; export type ReportScope={tenantId:string;organizationId:string;facilityId?:string};
export type ReportFilter={field:string;operator:'equals'|'in'|'between'|'contains'|'gte'|'lte';value:unknown}; export type ReportColumn={key:string;label:{ar?:string;en?:string};sourceField:string;visible:boolean;sortable:boolean;confidential?:boolean}; export type Calculation={key:string;operation:'count'|'sum'|'average'|'median'|'min'|'max'|'percentage'|'sla_compliance'|'overdue'|'closed'|'open'|'pending'|'risk_distribution'|'trend';sourceField?:string};
export type ReportDefinition=ReportScope&{id:string;moduleKey:string;name:{ar?:string;en?:string};description?:{ar?:string;en?:string};status:ReportStatus;currentVersionId?:string;ownerId:string}; export type ReportVersion=ReportScope&{id:string;definitionId:string;version:number;status:ReportStatus;filters:ReportFilter[];columns:ReportColumn[];calculations:Calculation[];groupBy:string[];createdBy:string;createdAt:string};
export type WidgetType='kpi_card'|'counter'|'gauge'|'line'|'area'|'bar'|'stacked_bar'|'pie'|'donut'|'heatmap'|'trend'|'table'|'top_n'|'timeline'|'activity_feed'; export type DashboardWidget={id:string;type:WidgetType;title:{ar?:string;en?:string};reportVersionId?:string;configuration:Record<string,unknown>;displayOrder:number}; export type DashboardDefinition=ReportScope&{id:string;name:{ar?:string;en?:string};widgets:DashboardWidget[];ownerId:string;status:ReportStatus};
export const reportingPermissions=['reports.view','reports.create','reports.edit','reports.publish','reports.export','reports.schedule','dashboards.view','dashboards.manage'] as const; export type ReportingPermission=(typeof reportingPermissions)[number]; export type ExportContract={format:'pdf'|'excel'|'csv';language:ReportLanguage;reportVersionId:string;filters:ReportFilter[]};
export function createDraftReportVersion(definition:ReportDefinition,published:ReportVersion,actorId:string):ReportVersion{if(definition.status!=='published'||published.status!=='published')throw new Error('Only published reports can create draft versions');return structuredClone({...published,id:`${published.id}-draft-${published.version+1}`,version:published.version+1,status:'draft',createdBy:actorId,createdAt:new Date().toISOString()})}
export function scopedRows<T extends ReportScope>(rows:readonly T[],scope:ReportScope){return rows.filter(row=>row.tenantId===scope.tenantId&&row.organizationId===scope.organizationId&&(scope.facilityId===undefined||row.facilityId===scope.facilityId))}
export function paginate<T>(rows:readonly T[],page:number,pageSize:number){const safePage=Math.max(1,page),safeSize=Math.max(1,Math.min(pageSize,200));return {items:rows.slice((safePage-1)*safeSize,safePage*safeSize),total:rows.length,page:safePage,pageSize:safeSize}}
export function calculateMetric(values:readonly number[],operation:Calculation['operation']){if(operation==='count')return values.length;if(!values.length)return 0;const sorted=[...values].sort((a,b)=>a-b);if(operation==='sum')return values.reduce((a,b)=>a+b,0);if(operation==='average')return values.reduce((a,b)=>a+b,0)/values.length;if(operation==='median')return sorted.length%2?sorted[(sorted.length-1)/2]:(sorted[sorted.length/2-1]+sorted[sorted.length/2])/2;if(operation==='min')return sorted[0];if(operation==='max')return sorted.at(-1)!;return 0}
