export type CapaStatus='draft'|'submitted'|'under_review'|'approved'|'in_progress'|'pending_evidence'|'pending_effectiveness_review'|'effective'|'ineffective'|'reopened'|'completed'|'closed'|'rejected'|'cancelled'|'overdue'|'archived';
export type CapaScope={tenantId:string;organizationId:string;facilityId?:string};
export type CapaText={ar?:string;en?:string};
export const capaPermissions=['capa.view','capa.create','capa.edit','capa.submit','capa.review','capa.approve','capa.assign','capa.start','capa.add_actions','capa.complete_actions','capa.upload_evidence','capa.review_effectiveness','capa.close','capa.reopen','capa.reject','capa.cancel','capa.extend_due_date','capa.archive','capa.restore','capa.view_history','capa.view_confidential','capa.manage_configuration','capa.export','capa.view_dashboard','capa.override_assignment','capa.override_separation_of_duties'] as const;
export type CapaPermission=(typeof capaPermissions)[number];
export type CapaRecord=CapaScope&{id:string;number:string;title:CapaText;description:CapaText;status:CapaStatus;ownerId:string;createdBy:string;approverId?:string;reviewerId?:string;targetCompletionDate?:string;confidentiality:'normal'|'confidential'|'restricted';source?:{module:string;type:string;id?:string;findingId?:string}};
export type CapaAction=CapaScope&{id:string;capaId:string;sequence:number;title:CapaText;status:'planned'|'assigned'|'in_progress'|'blocked'|'pending_evidence'|'pending_verification'|'completed'|'rejected'|'cancelled'|'overdue';assigneeId?:string;verifierId?:string;dueDate?:string};
export type RootCauseAnalysis=CapaScope&{id:string;capaId:string;method:string;problemStatement:string;contributingFactors:string[];rootCauses:string[];participants:string[];reviewedBy?:string;reviewDate?:string};
export function canTransitionCapa(from:CapaStatus,to:CapaStatus){return ({draft:['submitted','cancelled','archived'],submitted:['under_review','rejected','cancelled'],under_review:['approved','rejected'],approved:['in_progress','cancelled'],in_progress:['pending_evidence','pending_effectiveness_review','completed'],pending_evidence:['in_progress'],pending_effectiveness_review:['effective','ineffective'],ineffective:['reopened'],reopened:['in_progress'],completed:['closed'],effective:['completed'],closed:['archived'],rejected:['archived'],cancelled:['archived'],overdue:['in_progress','pending_evidence','cancelled'],archived:[]} as Record<CapaStatus,CapaStatus[]>)[from].includes(to)}
export function canApproveCapa(record:CapaRecord,actor:string,permissions:readonly string[]){return record.status==='under_review'&&actor!==record.createdBy&&actor!==record.ownerId&&permissions.includes('capa.approve')&&(record.approverId===undefined||record.approverId===actor||permissions.includes('capa.override_assignment'))}
export function canCloseCapa(record:CapaRecord,actor:string,permissions:readonly string[]){return record.status==='completed'&&actor!==record.ownerId&&permissions.includes('capa.close')||permissions.includes('capa.override_separation_of_duties')}
