import type {AuditEvent} from '@healthcare/audit';
export const platformAdministrationPermissions=['platform.full_access','platform.manage_modules','platform.manage_forms','platform.manage_fields','platform.manage_reference_data','platform.manage_database_records','platform.manage_imports','platform.manage_exports','platform.manage_schema_requests','platform.restore_records','platform.permanently_delete_records','platform.view_audit_logs','platform.manage_roles','platform.manage_permissions','platform.manage_branding','platform.manage_licensing'] as const;
export type PlatformAdministrationPermission=(typeof platformAdministrationPermissions)[number];
export type AdministrationScope={level:'global'|'organization'|'facility';tenantId?:string;organizationId?:string;facilityId?:string};
export type PlatformRole={key:'platform_owner'|'organization_administrator'|'facility_administrator';scope:AdministrationScope;permissions:readonly PlatformAdministrationPermission[]};
export const scopeAllows=(scope:AdministrationScope,target:AdministrationScope)=>{if(scope.level==='global')return scope.tenantId===undefined&&scope.organizationId===undefined&&scope.facilityId===undefined; if(!scope.tenantId||!scope.organizationId||scope.tenantId!==target.tenantId||scope.organizationId!==target.organizationId)return false; return scope.level==='organization'||Boolean(scope.facilityId&&scope.facilityId===target.facilityId);};
export const hasPlatformPermission=(role:PlatformRole,permission:PlatformAdministrationPermission,target:AdministrationScope)=>{const globalOwner=role.key==='platform_owner'&&role.scope.level==='global'&&scopeAllows(role.scope,target); const granted=role.permissions.includes(permission)||(role.permissions.includes('platform.full_access')&&globalOwner); return granted&&scopeAllows(role.scope,target);};
export type Localized={ar?:string;en?:string}; export type FormStatus='draft'|'published'|'archived';
export type DynamicFieldType='text'|'long_text'|'number'|'decimal'|'percentage'|'date'|'time'|'datetime'|'yes_no'|'single_choice'|'multiple_choice'|'dropdown'|'checkbox'|'rating'|'score'|'file'|'image'|'signature'|'user_selector'|'department_selector'|'facility_selector'|'medication_selector'|'reference_record_selector'|'calculated';
export type DynamicField={id:string;label:Localized;helpText?:Localized;type:DynamicFieldType;required:boolean;defaultValue?:unknown;displayOrder?:number;validation?:Record<string,unknown>;conditionalLogic?:{fieldId:string;operator:string;value:unknown};visibilityRules?:{fieldId:string;operator:string;value:unknown};readOnly?:boolean;confidentialityLevel?:'normal'|'confidential'|'restricted';searchable?:boolean;sortable?:boolean;filterable?:boolean;exportable?:boolean;importable?:boolean;options?:Localized[]};
export type UniversalFormVersion={id:string;formId:string;version:number;status:FormStatus;fields:DynamicField[];createdAt:string};
export type UniversalForm={id:string;tenantId:string;organizationId:string;name:Localized;status:FormStatus;currentVersionId:string};
export const createDraftFormVersion=(form:UniversalForm,version:UniversalFormVersion):UniversalFormVersion=>{if(form.status!=='published')throw new Error('Publication protection applies only to published forms.');return {...version,id:`${version.id}-draft-${version.version+1}`,version:version.version+1,status:'draft',fields:version.fields.map(x=>({...x,label:{...x.label},validation:x.validation&&{...x.validation},conditionalLogic:x.conditionalLogic&&{...x.conditionalLogic},options:x.options?.map(o=>({...o}))}))}};
export const referenceDataTypes=['facilities','branches','departments','job_titles','medication_categories','error_types','severity_levels','inspection_types','finding_statuses','policy_categories','document_types','recall_classifications','equipment_types','custom_dropdown_values'] as const;
export type RecordAdministrationAction='search'|'filter'|'history'|'controlled_correction'|'archive'|'restore'|'soft_delete'|'permanent_deletion_request'|'duplicate_merge'|'import'|'export';
export type DeletionRequest={recordId:string;requesterId:string;reason:string;typedConfirmation:string;dependenciesChecked:boolean;backupConfirmed:boolean;reauthenticated:boolean;secondApprovalRequired:boolean;secondApproverId?:string;protectedRecord:boolean};
export function validatePermanentDeletion(request:DeletionRequest){if(request.protectedRecord)throw new Error('Protected compliance and historical records cannot be permanently deleted.');if(request.secondApprovalRequired&&(!request.secondApproverId||request.secondApproverId===request.requesterId))throw new Error('A distinct second approver is required.');if(!request.reauthenticated||!request.reason||request.typedConfirmation!==request.recordId||!request.dependenciesChecked||!request.backupConfirmed)throw new Error('Permanent deletion safeguards are incomplete.');}
export type AdministrationAuditEvent=AuditEvent&{action:'record.soft_deleted'|'record.restore_requested'|'record.permanent_deletion_requested'|'form.version_created'};
export type ImportExportMapping={format:'word'|'excel'|'csv'|'json'|'google_sheets';fieldMappings:Record<string,string>};
