import type {AuditEvent} from '@healthcare/audit';
import type {Permission} from '@healthcare/permissions';

export type LocalizedText = {ar?: string; en?: string};
export type ApprovalStatus = 'draft' | 'under_review' | 'approved' | 'published' | 'archived';
export type QuestionType = 'yes_no' | 'compliance' | 'pass_fail' | 'single_choice' | 'multiple_choice' | 'numeric' | 'rating' | 'percentage' | 'short_text' | 'long_text' | 'date' | 'time' | 'photo' | 'attachment' | 'signature';
export type FindingStatus = 'open' | 'assigned' | 'in_progress' | 'pending_verification' | 'closed' | 'reopened';
export type TenantRecord = {id: string; tenantId: string; organizationId: string; facilityId?: string};
export type InspectionAnswerOption = {id: string; label: LocalizedText; score: number; createsFinding?: boolean; isFailure?: boolean};
export type InspectionQuestion = TenantRecord & {sectionId: string; text: LocalizedText; guidance?: LocalizedText; type: QuestionType; required: boolean; weight: number; maxScore: number; critical: boolean; allowNotApplicable: boolean; requireCommentOnFailure: boolean; requireEvidenceOnFailure: boolean; requireCorrectiveOwner: boolean; requireDueDate: boolean; displayOrder: number; helpText?: LocalizedText; referencePolicy?: string; referenceStandard?: string; tags: string[]; options: InspectionAnswerOption[]};
export type InspectionSection = TenantRecord & {templateVersionId: string; title: LocalizedText; instructions?: LocalizedText; weight: number; displayOrder: number; required: boolean; questions: InspectionQuestion[]};
export type InspectionTemplate = TenantRecord & {name: LocalizedText; description?: LocalizedText; departmentType?: string; inspectionType: string; status: ApprovalStatus; effectiveDate?: string; reviewDate?: string; ownerId: string; tags: string[]; instructions?: LocalizedText; estimatedDurationMinutes?: number; passingScore: number; criticalFailureRules: {failOnCritical: boolean}; currentVersionId: string};
export type InspectionTemplateVersion = TenantRecord & {templateId: string; version: number; status: ApprovalStatus; sections: InspectionSection[]; createdAt: string; createdBy: string};
export type InspectionResponse = {questionId: string; optionId?: string; value?: string | number | string[]; notApplicable?: boolean; comment?: string; evidenceIds: string[]};
export type InspectionEvidence = TenantRecord & {sessionId: string; questionId: string; kind: 'photo' | 'attachment' | 'signature'; placeholder: true; label: string};
export type InspectionSession = TenantRecord & {templateVersionId: string; departmentId: string; inspectorId: string; status: 'draft' | 'submitted' | 'reopened'; startedAt: string; submittedAt?: string; notes?: string; responses: InspectionResponse[]};
export type InspectionScore = {rawScore: number; percentage: number; passed: boolean; criticalFailure: boolean; sectionScores: Record<string, number>; rounding: number};
export type InspectionFinding = TenantRecord & {number: string; sessionId: string; questionId: string; severity: 'low'|'medium'|'high'|'critical'; description: string; evidenceIds: string[]; assignedOwnerId?: string; dueDate?: string; status: FindingStatus; immediateAction?: string; followUpNotes?: string; verificationStatus: 'not_started'|'pending'|'verified'; futureCapaReference?: string};
export type InspectionPermission = Extract<Permission, never> | 'inspections.view'|'inspections.create'|'inspections.perform'|'inspections.manage_templates'|'inspections.review'|'inspections.approve'|'inspections.publish'|'inspections.reopen'|'inspections.view_reports'|'inspections.export'|'inspections.manage_findings';
export const inspectionPermissions: readonly InspectionPermission[] = ['inspections.view','inspections.create','inspections.perform','inspections.manage_templates','inspections.review','inspections.approve','inspections.publish','inspections.reopen','inspections.view_reports','inspections.export','inspections.manage_findings'];
export const inspectionAuditActions = ['template.created','template.updated','template.version_created','template.approved','template.published','session.started','session.draft_saved','session.submitted','session.reopened','finding.created','finding.assigned','finding.closed'] as const;
export type InspectionAuditEvent = AuditEvent & {action: (typeof inspectionAuditActions)[number]};
export type FutureCapaIntegration = {sourceType: 'inspection_finding'; sourceId: string; createCapa: () => Promise<never>};

export function scoreInspection(version: InspectionTemplateVersion, responses: InspectionResponse[], passingScore: number): InspectionScore {
  let earned = 0, available = 0, criticalFailure = false; const sectionScores: Record<string, number> = {};
  for (const section of version.sections) { let se = 0, sa = 0; for (const q of section.questions) { const r = responses.find(x => x.questionId === q.id); if (r?.notApplicable) continue; const option = q.options.find(x => x.id === r?.optionId); const value = typeof r?.value === 'number' ? r.value : option?.score ?? 0; const max = q.maxScore * q.weight; sa += max; se += Math.min(value, q.maxScore) * q.weight; if (q.critical && (option?.isFailure || (typeof r?.value === 'number' && r.value === 0))) criticalFailure = true; } const pct = sa ? (se / sa) * 100 : 0; sectionScores[section.id] = Math.round(pct * 100) / 100; earned += se * section.weight; available += sa * section.weight; }
  const percentage = available ? Math.round((earned / available) * 10000) / 100 : 0; return {rawScore: earned, percentage, passed: percentage >= passingScore && !criticalFailure, criticalFailure, sectionScores, rounding: 2};
}
export function requiredResponsesMissing(version: InspectionTemplateVersion, responses: InspectionResponse[]) { return version.sections.flatMap(s => s.questions).filter(q => q.required && !responses.find(r => r.questionId === q.id && (r.notApplicable || r.optionId || r.value !== undefined))).map(q => q.id); }
export function generateFindings(session: InspectionSession, version: InspectionTemplateVersion): InspectionFinding[] { return version.sections.flatMap(s => s.questions).flatMap(q => { const r = session.responses.find(x => x.questionId === q.id); const option = q.options.find(x => x.id === r?.optionId); if (!option?.isFailure && !q.critical) return []; return [{id:`finding-${q.id}`,tenantId:session.tenantId,organizationId:session.organizationId,facilityId:session.facilityId,number:`INS-${session.id}-${q.displayOrder}`,sessionId:session.id,questionId:q.id,severity:q.critical?'critical':'medium',description:q.text.en ?? q.text.ar ?? '',evidenceIds:r?.evidenceIds ?? [],status:'open',verificationStatus:'not_started'}]; }); }
export function createDraftVersion(template: InspectionTemplate, prior: InspectionTemplateVersion, actorId: string): InspectionTemplateVersion { if (template.status !== 'published') throw new Error('Only published templates require a new draft version.'); return {...prior,id:`${prior.id}-draft-${prior.version + 1}`,version:prior.version + 1,status:'draft',createdAt:new Date().toISOString(),createdBy:actorId}; }
