-- Corrective CAPA security migration. Existing CAPA records are preserved.
create or replace function public.capa_transition_allowed(p_from public.capa_status,p_to public.capa_status) returns boolean language sql immutable as $$
  select (p_from,p_to) in (('draft','submitted'),('submitted','under_review'),('submitted','rejected'),('under_review','approved'),('under_review','rejected'),('approved','in_progress'),('approved','cancelled'),('in_progress','pending_evidence'),('in_progress','pending_effectiveness_review'),('pending_evidence','in_progress'),('pending_effectiveness_review','effective'),('pending_effectiveness_review','ineffective'),('ineffective','reopened'),('reopened','in_progress'),('effective','completed'),('completed','closed'),('closed','archived'),('rejected','archived'),('cancelled','archived'));
$$;

create or replace function public.can_view_capa(p_capa_id uuid) returns boolean language plpgsql stable security definer set search_path=public as $$
declare c public.capa_records%rowtype;
begin
  if auth.uid() is null then return false; end if;
  select * into c from public.capa_records where id=p_capa_id;
  if not found or not public.scope_allowed(c.tenant_id,c.organization_id,c.facility_id) then return false; end if;
  if c.confidentiality_level <> 'normal' and not public.can_capa('capa.view_confidential',c.tenant_id,c.organization_id,c.facility_id) and auth.uid() not in (c.owner_id,c.created_by,c.approver_id,c.reviewer_id) then return false; end if;
  if c.status in ('archived','closed') and not public.can_capa('capa.view_history',c.tenant_id,c.organization_id,c.facility_id) and auth.uid() not in (c.owner_id,c.created_by,c.approver_id,c.reviewer_id) then return false; end if;
  return public.can_capa('capa.view',c.tenant_id,c.organization_id,c.facility_id)
    or auth.uid() in (c.owner_id,c.created_by,c.approver_id,c.reviewer_id)
    or exists(select 1 from public.capa_assignments a where a.capa_id=c.id and a.user_id=auth.uid())
    or exists(select 1 from public.capa_actions a where a.capa_id=c.id and (a.assigned_user_id=auth.uid() or a.verification_user_id=auth.uid()));
end $$;

create or replace function public.capa_closure_ready(p_capa uuid) returns boolean language sql stable security definer set search_path=public as $$
 select exists(select 1 from public.capa_root_cause_analyses r where r.capa_id=p_capa and r.reviewed_by is not null and r.review_date is not null)
 and not exists(select 1 from public.capa_actions a where a.capa_id=p_capa and a.status <> 'completed')
 and not exists(select 1 from public.capa_actions a where a.capa_id=p_capa and a.evidence_required and not exists(select 1 from public.capa_evidence e where e.capa_id=p_capa and e.action_id=a.id and e.scan_status='accepted'))
 and exists(select 1 from public.capa_effectiveness_reviews e where e.capa_id=p_capa and e.result='effective' and not e.reopen_decision)
 and not exists(select 1 from public.capa_effectiveness_reviews i where i.capa_id=p_capa and i.result='ineffective' and not exists(select 1 from public.capa_effectiveness_reviews e where e.capa_id=p_capa and e.result='effective' and e.created_at>i.created_at))
 and not exists(select 1 from public.capa_due_date_extensions x where x.capa_id=p_capa and x.status='requested');
$$;

create or replace function public.transition_capa(p_capa uuid,p_to public.capa_status,p_reason text default null) returns void language plpgsql security definer set search_path=public as $$
declare c public.capa_records%rowtype; required text;
begin
 select * into c from public.capa_records where id=p_capa for update;
 if not found or not public.capa_transition_allowed(c.status,p_to) then raise exception 'CAPA lifecycle transition denied'; end if;
 required:=case p_to when 'submitted' then 'capa.submit' when 'under_review' then 'capa.review' when 'approved' then 'capa.approve' when 'in_progress' then 'capa.start' when 'pending_evidence' then 'capa.complete_actions' when 'pending_effectiveness_review' then 'capa.review_effectiveness' when 'completed' then 'capa.close' when 'closed' then 'capa.close' when 'reopened' then 'capa.reopen' when 'rejected' then 'capa.reject' when 'cancelled' then 'capa.cancel' when 'archived' then 'capa.archive' else 'capa.edit' end;
 if not public.can_capa(required,c.tenant_id,c.organization_id,c.facility_id) or ((p_to in ('rejected','cancelled','reopened')) and coalesce(trim(p_reason),'')='') or (p_to in ('completed','closed') and not public.capa_closure_ready(c.id)) or (p_to='approved' and auth.uid() in (c.created_by,c.owner_id) and not public.can_capa('capa.override_separation_of_duties',c.tenant_id,c.organization_id,c.facility_id)) or (p_to='closed' and auth.uid()=c.owner_id and not public.can_capa('capa.override_separation_of_duties',c.tenant_id,c.organization_id,c.facility_id)) then raise exception 'CAPA transition denied'; end if;
 perform set_config('app.capa_controlled','on',true); perform set_config('app.reporting_audit','on',true);
 update public.capa_records set status=p_to,actual_completion_date=case when p_to='completed' then current_date else actual_completion_date end,closed_at=case when p_to='closed' then now() else closed_at end,closed_by=case when p_to='closed' then auth.uid() else closed_by end,updated_at=now(),updated_by=auth.uid() where id=c.id;
 perform public.record_capa_event(c.id,c.tenant_id,c.organization_id,c.facility_id,'capa.'||p_to::text,jsonb_build_object('reason',p_reason));
end $$;

-- Correct schema drift: assignments use user_id, never assigned_user_id.
create or replace function public.enforce_capa_assignment_scope() returns trigger language plpgsql security definer set search_path=public as $$
declare c public.capa_records%rowtype;
begin select * into c from public.capa_records where id=new.capa_id; if not found or c.tenant_id<>new.tenant_id or c.organization_id<>new.organization_id or c.facility_id is distinct from new.facility_id or not public.policy_member_in_scope(new.user_id,new.tenant_id,new.organization_id,new.facility_id) then raise exception 'CAPA assignment outside scope' using errcode='23503'; end if; return new; end $$;
drop trigger if exists capa_assignments_scope on public.capa_assignments;
create trigger capa_assignments_scope before insert or update on public.capa_assignments for each row execute function public.enforce_capa_assignment_scope();

alter table public.capa_records enable row level security; alter table public.capa_sources enable row level security; alter table public.capa_actions enable row level security; alter table public.capa_root_cause_analyses enable row level security; alter table public.capa_effectiveness_reviews enable row level security; alter table public.capa_due_date_extensions enable row level security; alter table public.capa_assignments enable row level security; alter table public.capa_comments enable row level security; alter table public.capa_evidence enable row level security; alter table public.capa_events enable row level security;
drop policy if exists capa_records_read on public.capa_records; create policy capa_records_read on public.capa_records for select using(public.can_view_capa(id));
drop policy if exists capa_children_read on public.capa_actions; drop policy if exists capa_comments_read on public.capa_comments; create policy capa_actions_read on public.capa_actions for select using(public.can_view_capa(capa_id));
create policy capa_sources_read on public.capa_sources for select using(public.can_view_capa(capa_id)); create policy capa_rca_read on public.capa_root_cause_analyses for select using(public.can_view_capa(capa_id)); create policy capa_effectiveness_read on public.capa_effectiveness_reviews for select using(public.can_view_capa(capa_id)); create policy capa_extensions_read on public.capa_due_date_extensions for select using(public.can_view_capa(capa_id)); create policy capa_assignments_read on public.capa_assignments for select using(public.can_view_capa(capa_id)); create policy capa_comments_read_parent on public.capa_comments for select using(public.can_view_capa(capa_id) and (not confidential or public.can_capa('capa.view_confidential',tenant_id,organization_id,facility_id))); create policy capa_evidence_read on public.capa_evidence for select using(public.can_view_capa(capa_id));
drop policy if exists capa_events_read on public.capa_events; create policy capa_events_read on public.capa_events for select using(public.can_view_capa(capa_id) and public.can_capa('capa.view_history',tenant_id,organization_id,facility_id));
revoke insert,update,delete on public.capa_records,public.capa_sources,public.capa_actions,public.capa_root_cause_analyses,public.capa_effectiveness_reviews,public.capa_due_date_extensions,public.capa_assignments,public.capa_comments,public.capa_evidence,public.capa_events from authenticated;
grant select on public.capa_records,public.capa_sources,public.capa_actions,public.capa_root_cause_analyses,public.capa_effectiveness_reviews,public.capa_due_date_extensions,public.capa_assignments,public.capa_comments,public.capa_evidence,public.capa_events to authenticated;
revoke all on function public.can_view_capa(uuid),public.capa_transition_allowed(public.capa_status,public.capa_status),public.capa_closure_ready(uuid),public.enforce_capa_assignment_scope() from public,anon;
grant execute on function public.can_view_capa(uuid),public.transition_capa(uuid,public.capa_status,text) to authenticated;

-- CAPA must use its own trusted audit path. Reporting is a read/export concern and
-- must never be a prerequisite for a regulated state change.
create or replace function public.append_capa_audit_event(p_t uuid,p_o uuid,p_f uuid,p_action text,p_entity_id uuid,p_metadata jsonb default '{}'::jsonb) returns uuid language plpgsql security definer set search_path=public as $$ declare id uuid;
begin
 if auth.uid() is null or current_setting('app.capa_controlled',true)<>'on' or p_metadata ?| array['password','token','secret','access_token'] then raise exception 'CAPA audit event is not authorized'; end if;
 insert into public.audit_events(tenant_id,organization_id,facility_id,actor_id,action,entity_type,entity_id,metadata) values(p_t,p_o,p_f,auth.uid(),p_action,'capa_record',p_entity_id,p_metadata) returning public.audit_events.id into id; return id;
end $$;
create or replace function public.record_capa_event(p_capa uuid,p_t uuid,p_o uuid,p_f uuid,p_action text,p_metadata jsonb default '{}'::jsonb) returns void language plpgsql security definer set search_path=public as $$
begin
 if auth.uid() is null or current_setting('app.capa_controlled',true)<>'on' then raise exception 'CAPA event is not authorized'; end if;
 insert into public.capa_events(capa_id,tenant_id,organization_id,facility_id,actor_id,action,metadata) values(p_capa,p_t,p_o,p_f,auth.uid(),p_action,p_metadata);
 perform public.append_capa_audit_event(p_t,p_o,p_f,p_action,p_capa,p_metadata);
end $$;

-- Per-scope counters are locked by the unique counter row; numbers never use MAX()
-- and gaps are acceptable after a rolled-back transaction or an intentionally voided draft.
create table if not exists public.capa_number_counters(tenant_id uuid not null references public.tenants(id),organization_id uuid not null references public.organizations(id),facility_key text not null,calendar_year integer not null check(calendar_year between 2000 and 9999),last_value integer not null default 0 check(last_value>=0),primary key(tenant_id,organization_id,facility_key,calendar_year));
alter table public.capa_number_counters enable row level security;
create table if not exists public.capa_action_counters(capa_id uuid primary key references public.capa_records(id) on delete restrict,last_value integer not null default -1 check(last_value>=-1));
alter table public.capa_action_counters enable row level security;
create or replace function public.next_capa_number(p_t uuid,p_o uuid,p_f uuid) returns text language plpgsql security definer set search_path=public as $$ declare n integer; y integer:=extract(year from current_date); k text:=coalesce(p_f::text,'global'); begin
 insert into public.capa_number_counters(tenant_id,organization_id,facility_key,calendar_year,last_value) values(p_t,p_o,k,y,1) on conflict(tenant_id,organization_id,facility_key,calendar_year) do update set last_value=public.capa_number_counters.last_value+1 returning last_value into n;
 return 'CAPA-'||y::text||'-'||lpad(n::text,6,'0');
end $$;
create or replace function public.create_capa(p_t uuid,p_o uuid,p_f uuid,p_title_ar text,p_title_en text,p_description_ar text,p_description_en text,p_owner uuid,p_source_module text default 'manual',p_source_type text default 'manual',p_source_id uuid default null) returns uuid language plpgsql security definer set search_path=public as $$ declare id uuid; number text; begin
 if auth.uid() is null or not public.can_capa('capa.create',p_t,p_o,p_f) or not public.policy_member_in_scope(p_owner,p_t,p_o,p_f) or not public.capa_source_allowed(p_source_module,p_source_type,p_source_id,p_t,p_o,p_f) then raise exception 'CAPA creation denied'; end if;
 if coalesce(nullif(trim(p_title_ar),''),nullif(trim(p_title_en),'')) is null then raise exception 'CAPA title is required'; end if;
 number:=public.next_capa_number(p_t,p_o,p_f); perform set_config('app.capa_controlled','on',true);
 insert into public.capa_records(tenant_id,organization_id,facility_id,capa_number,title_ar,title_en,description_ar,description_en,owner_id,created_by,updated_by) values(p_t,p_o,p_f,number,nullif(trim(p_title_ar),''),nullif(trim(p_title_en),''),nullif(trim(p_description_ar),''),nullif(trim(p_description_en),''),p_owner,auth.uid(),auth.uid()) returning public.capa_records.id into id;
 insert into public.capa_sources(capa_id,tenant_id,organization_id,facility_id,source_module,source_record_type,source_record_id,created_by) values(id,p_t,p_o,p_f,p_source_module,p_source_type,p_source_id,auth.uid()); perform public.record_capa_event(id,p_t,p_o,p_f,'capa.created'); return id;
end $$;

-- Adapter validation checks existence, scope and the caller's authorized read path.
create or replace function public.capa_source_allowed(p_module text,p_type text,p_id uuid,p_t uuid,p_o uuid,p_f uuid) returns boolean language plpgsql security definer set search_path=public as $$ begin
 if p_module='manual' and p_type='manual' and p_id is null then return true; end if;
 if p_module='medication_errors' and p_type='medication_error' then return exists(select 1 from public.medication_error_reports x where x.id=p_id and x.tenant_id=p_t and x.organization_id=p_o and x.facility_id is not distinct from p_f and public.can_medication_error('medication_errors.view',p_t,p_o,p_f)); end if;
 if p_module='policies' and p_type='policy' then return exists(select 1 from public.policy_definitions x where x.id=p_id and x.tenant_id=p_t and x.organization_id=p_o and x.facility_id is not distinct from p_f and (public.can_policy('policies.view',p_t,p_o,p_f) or public.can_policy('policies.edit',p_t,p_o,p_f) or public.can_policy('policies.review',p_t,p_o,p_f))); end if;
 raise exception 'CAPA source adapter is not implemented';
end $$;

-- Immutable tenant/scope/parent fields prevent moving a child record into another CAPA.
create or replace function public.enforce_capa_child_integrity() returns trigger language plpgsql security definer set search_path=public as $$ declare c public.capa_records%rowtype; begin
 if tg_op='UPDATE' and (new.capa_id,new.tenant_id,new.organization_id,new.facility_id) is distinct from (old.capa_id,old.tenant_id,old.organization_id,old.facility_id) then raise exception 'CAPA child scope is immutable'; end if;
 select cr.* into c from public.capa_records cr where cr.id=new.capa_id; if not found or (c.tenant_id,c.organization_id,c.facility_id) is distinct from (new.tenant_id,new.organization_id,new.facility_id) then raise exception 'CAPA child scope mismatch'; end if;
 return new;
end $$;
create or replace function public.enforce_capa_action_integrity() returns trigger language plpgsql security definer set search_path=public as $$ declare c public.capa_records%rowtype; begin
 if tg_op='UPDATE' and (new.capa_id,new.tenant_id,new.organization_id,new.facility_id) is distinct from (old.capa_id,old.tenant_id,old.organization_id,old.facility_id) then raise exception 'CAPA child scope is immutable'; end if;
 select cr.* into c from public.capa_records cr where cr.id=new.capa_id;
 if not found or (c.tenant_id,c.organization_id,c.facility_id) is distinct from (new.tenant_id,new.organization_id,new.facility_id) then raise exception 'CAPA child scope mismatch'; end if;
 if new.assigned_user_id is not null and not public.policy_member_in_scope(new.assigned_user_id,new.tenant_id,new.organization_id,new.facility_id) then raise exception 'CAPA action assignee outside scope'; end if;
 return new;
end $$;
create or replace function public.enforce_capa_assignment_integrity() returns trigger language plpgsql security definer set search_path=public as $$ declare c public.capa_records%rowtype; begin
 if tg_op='UPDATE' and (new.capa_id,new.tenant_id,new.organization_id,new.facility_id) is distinct from (old.capa_id,old.tenant_id,old.organization_id,old.facility_id) then raise exception 'CAPA child scope is immutable'; end if;
 select cr.* into c from public.capa_records cr where cr.id=new.capa_id;
 if not found or (c.tenant_id,c.organization_id,c.facility_id) is distinct from (new.tenant_id,new.organization_id,new.facility_id) or not public.policy_member_in_scope(new.user_id,new.tenant_id,new.organization_id,new.facility_id) then raise exception 'CAPA assignment outside scope'; end if;
 return new;
end $$;
drop trigger if exists capa_actions_scope on public.capa_actions; create trigger capa_actions_scope before insert or update on public.capa_actions for each row execute function public.enforce_capa_action_integrity();
drop trigger if exists capa_sources_scope on public.capa_sources; create trigger capa_sources_scope before insert or update on public.capa_sources for each row execute function public.enforce_capa_child_integrity();
drop trigger if exists capa_assignments_scope on public.capa_assignments; create trigger capa_assignments_scope before insert or update on public.capa_assignments for each row execute function public.enforce_capa_assignment_integrity();
drop trigger if exists capa_rca_scope on public.capa_root_cause_analyses; create trigger capa_rca_scope before insert or update on public.capa_root_cause_analyses for each row execute function public.enforce_capa_child_integrity();
drop trigger if exists capa_effectiveness_scope on public.capa_effectiveness_reviews; create trigger capa_effectiveness_scope before insert or update on public.capa_effectiveness_reviews for each row execute function public.enforce_capa_child_integrity();
drop trigger if exists capa_extensions_child_scope on public.capa_due_date_extensions; create trigger capa_extensions_child_scope before insert or update on public.capa_due_date_extensions for each row execute function public.enforce_capa_child_integrity();
drop trigger if exists capa_comments_scope on public.capa_comments; create trigger capa_comments_scope before insert or update on public.capa_comments for each row execute function public.enforce_capa_child_integrity();
drop trigger if exists capa_evidence_scope on public.capa_evidence; create trigger capa_evidence_scope before insert or update on public.capa_evidence for each row execute function public.enforce_capa_child_integrity();
drop trigger if exists capa_events_scope on public.capa_events; create trigger capa_events_scope before insert or update on public.capa_events for each row execute function public.enforce_capa_child_integrity();

-- Controlled action lifecycle. Direct table DML remains revoked.
create or replace function public.create_capa_action(p_capa uuid,p_title_ar text,p_title_en text,p_assignee uuid,p_due date,p_evidence_required boolean default false) returns uuid language plpgsql security definer set search_path=public as $$ declare c public.capa_records%rowtype; id uuid; s integer; begin
 select * into c from public.capa_records where public.capa_records.id=p_capa for update; if not found or c.status not in ('approved','in_progress','reopened') or not public.can_capa('capa.add_actions',c.tenant_id,c.organization_id,c.facility_id) or not public.policy_member_in_scope(p_assignee,c.tenant_id,c.organization_id,c.facility_id) or coalesce(nullif(trim(p_title_ar),''),nullif(trim(p_title_en),'')) is null then raise exception 'CAPA action creation denied'; end if;
 insert into public.capa_action_counters(capa_id,last_value) values(c.id,0) on conflict(capa_id) do update set last_value=public.capa_action_counters.last_value+1 returning last_value into s; perform set_config('app.capa_controlled','on',true); insert into public.capa_actions(capa_id,tenant_id,organization_id,facility_id,sequence,title_ar,title_en,assigned_user_id,due_date,evidence_required,status) values(c.id,c.tenant_id,c.organization_id,c.facility_id,s,nullif(trim(p_title_ar),''),nullif(trim(p_title_en),''),p_assignee,p_due,p_evidence_required,'assigned') returning public.capa_actions.id into id; perform public.record_capa_event(c.id,c.tenant_id,c.organization_id,c.facility_id,'capa.action_created',jsonb_build_object('action_id',id)); return id;
end $$;
create or replace function public.transition_capa_action(p_action uuid,p_to public.capa_action_status,p_reason text default null) returns void language plpgsql security definer set search_path=public as $$ declare a public.capa_actions%rowtype; c public.capa_records%rowtype; allowed boolean; begin
 select * into a from public.capa_actions where id=p_action for update; select * into c from public.capa_records where id=a.capa_id for update; allowed=(a.status,p_to) in (('planned','assigned'),('assigned','in_progress'),('in_progress','blocked'),('blocked','in_progress'),('in_progress','pending_evidence'),('pending_evidence','pending_verification'),('pending_verification','completed'),('pending_verification','rejected'),('rejected','in_progress'),('assigned','cancelled'),('in_progress','cancelled'),('blocked','cancelled'));
 if not found or not allowed or c.status not in ('in_progress','reopened','pending_evidence') or (auth.uid()<>a.assigned_user_id and not public.can_capa('capa.complete_actions',c.tenant_id,c.organization_id,c.facility_id)) or (p_to in ('blocked','rejected','cancelled') and coalesce(trim(p_reason),'')='') or (p_to='pending_verification' and a.evidence_required and not exists(select 1 from public.capa_evidence e where e.action_id=a.id and e.scan_status='accepted')) or (p_to='completed' and (a.verification_user_id is null or auth.uid()<>a.verification_user_id) and not public.can_capa('capa.complete_actions',c.tenant_id,c.organization_id,c.facility_id)) then raise exception 'CAPA action transition denied'; end if;
 perform set_config('app.capa_controlled','on',true); update public.capa_actions set status=p_to,actual_start_date=case when p_to='in_progress' then coalesce(actual_start_date,current_date) else actual_start_date end,completion_date=case when p_to='completed' then current_date else completion_date end,verification_date=case when p_to='completed' then current_date else verification_date end,rejection_reason=case when p_to='rejected' then trim(p_reason) else rejection_reason end where id=a.id; perform public.record_capa_event(c.id,c.tenant_id,c.organization_id,c.facility_id,'capa.action_'||p_to::text,jsonb_build_object('action_id',a.id,'reason',p_reason));
end $$;
create or replace function public.reassign_capa_action(p_action uuid,p_assignee uuid,p_verifier uuid,p_reason text) returns void language plpgsql security definer set search_path=public as $$ declare a public.capa_actions%rowtype; c public.capa_records%rowtype; begin select * into a from public.capa_actions where id=p_action for update; select * into c from public.capa_records where id=a.capa_id for update; if not found or not public.can_capa('capa.assign',c.tenant_id,c.organization_id,c.facility_id) or not public.policy_member_in_scope(p_assignee,c.tenant_id,c.organization_id,c.facility_id) or (p_verifier is not null and (p_verifier=p_assignee or not public.policy_member_in_scope(p_verifier,c.tenant_id,c.organization_id,c.facility_id))) or ((a.assigned_user_id,p_verifier) is distinct from (p_assignee,p_verifier) and coalesce(trim(p_reason),'')='') then raise exception 'CAPA action reassignment denied'; end if; perform set_config('app.capa_controlled','on',true); update public.capa_actions set assigned_user_id=p_assignee,verification_user_id=p_verifier,status=case when status='planned' then 'assigned' else status end where id=a.id; perform public.record_capa_event(c.id,c.tenant_id,c.organization_id,c.facility_id,'capa.action_reassigned',jsonb_build_object('action_id',a.id,'reason',trim(p_reason))); end $$;

-- Due dates are changed only by a request/decision record; action and CAPA targets
-- share the same immutable audit trail.
alter table public.capa_due_date_extensions add column if not exists action_id uuid references public.capa_actions(id) on delete restrict;
create or replace function public.enforce_capa_extension_integrity() returns trigger language plpgsql security definer set search_path=public as $$ begin
 if new.action_id is not null and not exists(select 1 from public.capa_actions a where a.id=new.action_id and a.capa_id=new.capa_id and a.tenant_id=new.tenant_id and a.organization_id=new.organization_id and a.facility_id is not distinct from new.facility_id) then raise exception 'CAPA extension action does not belong to CAPA'; end if; return new;
end $$;
drop trigger if exists capa_extensions_scope on public.capa_due_date_extensions; create trigger capa_extensions_scope before insert or update on public.capa_due_date_extensions for each row execute function public.enforce_capa_extension_integrity();
create or replace function public.request_capa_due_date_extension(p_capa uuid,p_action uuid,p_new_due date,p_reason text) returns uuid language plpgsql security definer set search_path=public as $$ declare c public.capa_records%rowtype; a public.capa_actions%rowtype; old date; id uuid; begin
 select * into c from public.capa_records where id=p_capa for update; if p_action is not null then select * into a from public.capa_actions where id=p_action and capa_id=c.id for update; end if; old:=case when p_action is null then c.target_completion_date else a.due_date end;
 if not found or not public.can_capa('capa.extend_due_date',c.tenant_id,c.organization_id,c.facility_id) or old is null or p_new_due<=old or coalesce(trim(p_reason),'')='' or exists(select 1 from public.capa_due_date_extensions x where x.capa_id=c.id and x.action_id is not distinct from p_action and x.status='requested') then raise exception 'CAPA due-date extension request denied'; end if;
 perform set_config('app.capa_controlled','on',true); insert into public.capa_due_date_extensions(capa_id,action_id,tenant_id,organization_id,facility_id,old_due_date,requested_due_date,reason,requested_by) values(c.id,p_action,c.tenant_id,c.organization_id,c.facility_id,old,p_new_due,trim(p_reason),auth.uid()) returning public.capa_due_date_extensions.id into id; perform public.record_capa_event(c.id,c.tenant_id,c.organization_id,c.facility_id,'capa.due_date_extension_requested',jsonb_build_object('extension_id',id,'action_id',p_action)); return id;
end $$;
create or replace function public.decide_capa_due_date_extension(p_extension uuid,p_approve boolean,p_comment text default null) returns void language plpgsql security definer set search_path=public as $$ declare x public.capa_due_date_extensions%rowtype; c public.capa_records%rowtype; begin
 select * into x from public.capa_due_date_extensions where id=p_extension for update; select * into c from public.capa_records where id=x.capa_id for update; if not found or x.status<>'requested' or not public.can_capa('capa.approve',c.tenant_id,c.organization_id,c.facility_id) or auth.uid()=x.requested_by or (not p_approve and coalesce(trim(p_comment),'')='') then raise exception 'CAPA due-date extension decision denied'; end if;
 perform set_config('app.capa_controlled','on',true); update public.capa_due_date_extensions set status=case when p_approve then 'approved' else 'rejected' end,decided_by=auth.uid(),decided_at=now(),decision_comment=nullif(trim(p_comment),'') where id=x.id; if p_approve then if x.action_id is null then update public.capa_records set target_completion_date=x.requested_due_date,updated_at=now(),updated_by=auth.uid() where id=c.id; else update public.capa_actions set due_date=x.requested_due_date where id=x.action_id; end if; end if; perform public.record_capa_event(c.id,c.tenant_id,c.organization_id,c.facility_id,'capa.due_date_extension_'||case when p_approve then 'approved' else 'rejected' end,jsonb_build_object('extension_id',x.id,'action_id',x.action_id)); end $$;

-- A CAPA evidence authorization has the identical private, short-lived,
-- checksum-and-scan-gated contract used by Policy uploads.
create table if not exists public.capa_upload_authorizations(id uuid primary key default gen_random_uuid(),capa_id uuid not null references public.capa_records(id) on delete restrict,action_id uuid references public.capa_actions(id) on delete restrict,tenant_id uuid not null references public.tenants(id),organization_id uuid not null references public.organizations(id),facility_id uuid references public.facilities(id),uploader_id uuid not null references public.user_profiles(id),storage_key text not null unique,expected_size bigint not null check(expected_size between 1 and 52428800),expected_checksum text not null check(expected_checksum ~ '^[A-Fa-f0-9]{64}$'),expires_at timestamptz not null,finalized_at timestamptz,malware_scan_status text not null default 'pending' check(malware_scan_status in ('pending','accepted','rejected')),checksum_verification_status text not null default 'pending' check(checksum_verification_status in ('pending','verified','failed')),created_at timestamptz not null default now());
alter table public.capa_evidence add column if not exists upload_authorization_id uuid references public.capa_upload_authorizations(id) on delete restrict;
create unique index if not exists capa_evidence_upload_authorization_unique on public.capa_evidence(upload_authorization_id) where upload_authorization_id is not null;
alter table public.capa_upload_authorizations enable row level security;
create policy capa_upload_authorizations_owner on public.capa_upload_authorizations for select using(uploader_id=auth.uid() and public.can_view_capa(capa_id));
insert into storage.buckets(id,name,public) values('capa-evidence','capa-evidence',false) on conflict(id) do update set public=false;
create or replace function public.authorize_capa_evidence_upload(p_capa uuid,p_action uuid,p_filename text,p_size bigint,p_checksum text) returns uuid language plpgsql security definer set search_path=public as $$ declare c public.capa_records%rowtype; a public.capa_actions%rowtype; id uuid; safe text; key text; begin
 select cr.* into c from public.capa_records cr where cr.id=p_capa for update; if p_action is not null then select ca.* into a from public.capa_actions ca where ca.id=p_action and ca.capa_id=c.id; end if; safe:=regexp_replace(lower(coalesce(trim(p_filename),'')),'[^a-z0-9._-]','_','g');
 if not found or c.status in ('closed','archived','cancelled') or not public.can_capa('capa.upload_evidence',c.tenant_id,c.organization_id,c.facility_id) or p_size not between 1 and 52428800 or p_checksum !~ '^[A-Fa-f0-9]{64}$' or safe !~ '^[a-z0-9][a-z0-9_-]*\.(pdf|docx|doc|xlsx|xls|pptx|jpg|jpeg|png|webp)$' then raise exception 'CAPA evidence upload authorization denied'; end if;
 key:='tenant/'||c.tenant_id||'/organization/'||c.organization_id||'/facility/'||coalesce(c.facility_id::text,'global')||'/capa/'||c.id||'/actions/'||coalesce(p_action::text,'record')||'/'||gen_random_uuid()||'-'||safe; insert into public.capa_upload_authorizations(capa_id,action_id,tenant_id,organization_id,facility_id,uploader_id,storage_key,expected_size,expected_checksum,expires_at) values(c.id,p_action,c.tenant_id,c.organization_id,c.facility_id,auth.uid(),key,p_size,p_checksum,now()+interval '15 minutes') returning public.capa_upload_authorizations.id into id; return id;
end $$;
create or replace function public.capa_storage_object_allowed(p_name text,p_write boolean) returns boolean language plpgsql security definer set search_path=public,storage as $$ begin
 if auth.uid() is null or p_name !~ '^tenant/[0-9a-f-]{36}/organization/[0-9a-f-]{36}/facility/([0-9a-f-]{36}|global)/capa/[0-9a-f-]{36}/actions/([0-9a-f-]{36}|record)/[0-9a-f-]{36}-[A-Za-z0-9._-]+$' then return false; end if;
 if p_write then return exists(select 1 from public.capa_upload_authorizations a where a.storage_key=p_name and a.uploader_id=auth.uid() and a.expires_at>now() and a.finalized_at is null and a.checksum_verification_status='pending' and public.can_capa('capa.upload_evidence',a.tenant_id,a.organization_id,a.facility_id)); end if;
 return exists(select 1 from public.capa_evidence e left join public.capa_upload_authorizations a on a.id=e.upload_authorization_id where e.storage_bucket='capa-evidence' and e.storage_key=p_name and e.scan_status='accepted' and (a.id is null or (a.malware_scan_status='accepted' and a.checksum_verification_status='verified')) and public.can_view_capa(e.capa_id));
end $$;
drop policy if exists capa_evidence_storage_insert on storage.objects; drop policy if exists capa_evidence_storage_select on storage.objects;
create policy capa_evidence_storage_insert on storage.objects for insert to authenticated with check(bucket_id='capa-evidence' and public.capa_storage_object_allowed(name,true));
create policy capa_evidence_storage_select on storage.objects for select to authenticated using(bucket_id='capa-evidence' and public.capa_storage_object_allowed(name,false));
create or replace function public.finalize_capa_evidence_verified(p_authorization uuid,p_mime text) returns uuid language plpgsql security definer set search_path=public,storage as $$ declare a public.capa_upload_authorizations%rowtype; c public.capa_records%rowtype; size bigint; id uuid; ext text; begin
 if auth.role()<>'service_role' then raise exception 'Trusted CAPA evidence finalization requires service role'; end if; select cua.* into a from public.capa_upload_authorizations cua where cua.id=p_authorization for update; select cr.* into c from public.capa_records cr where cr.id=a.capa_id for update; select nullif(so.metadata->>'size','')::bigint into size from storage.objects so where so.bucket_id='capa-evidence' and so.name=a.storage_key;
 ext:=lower(regexp_replace(a.storage_key,'^.*\.','')); if not found or a.finalized_at is not null or a.expires_at<=now() or a.checksum_verification_status<>'verified' or a.malware_scan_status<>'accepted' or size is distinct from a.expected_size or not public.policy_member_in_scope(a.uploader_id,a.tenant_id,a.organization_id,a.facility_id) or not public.policy_actor_has_permission(a.uploader_id,'capa.upload_evidence',a.tenant_id,a.organization_id,a.facility_id) or c.status in ('closed','archived','cancelled') or (ext='pdf' and p_mime<>'application/pdf') or (ext='docx' and p_mime<>'application/vnd.openxmlformats-officedocument.wordprocessingml.document') or (ext='doc' and p_mime<>'application/msword') or (ext='xlsx' and p_mime<>'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet') or (ext='xls' and p_mime<>'application/vnd.ms-excel') or (ext='pptx' and p_mime<>'application/vnd.openxmlformats-officedocument.presentationml.presentation') or (ext in ('jpg','jpeg') and p_mime<>'image/jpeg') or (ext='png' and p_mime<>'image/png') or (ext='webp' and p_mime<>'image/webp') then raise exception 'CAPA evidence finalization denied'; end if;
 insert into public.capa_evidence(capa_id,action_id,tenant_id,organization_id,facility_id,storage_bucket,storage_key,checksum,mime_type,byte_size,scan_status,uploaded_by,upload_authorization_id) values(a.capa_id,a.action_id,a.tenant_id,a.organization_id,a.facility_id,'capa-evidence',a.storage_key,a.expected_checksum,p_mime,a.expected_size,'accepted',a.uploader_id,a.id) returning public.capa_evidence.id into id; update public.capa_upload_authorizations cua set finalized_at=now() where cua.id=a.id; return id;
end $$;

revoke all on function public.append_capa_audit_event(uuid,uuid,uuid,text,uuid,jsonb),public.record_capa_event(uuid,uuid,uuid,uuid,text,jsonb),public.next_capa_number(uuid,uuid,uuid),public.capa_source_allowed(text,text,uuid,uuid,uuid,uuid),public.enforce_capa_child_integrity(),public.capa_storage_object_allowed(text,boolean),public.finalize_capa_evidence_verified(uuid,text) from public,anon,authenticated;
revoke all on function public.create_capa(uuid,uuid,uuid,text,text,text,text,uuid,text,text,uuid),public.create_capa_action(uuid,text,text,uuid,date,boolean),public.transition_capa_action(uuid,public.capa_action_status,text),public.reassign_capa_action(uuid,uuid,uuid,text),public.request_capa_due_date_extension(uuid,uuid,date,text),public.decide_capa_due_date_extension(uuid,boolean,text),public.authorize_capa_evidence_upload(uuid,uuid,text,bigint,text) from public,anon;
grant execute on function public.create_capa(uuid,uuid,uuid,text,text,text,text,uuid,text,text,uuid),public.create_capa_action(uuid,text,text,uuid,date,boolean),public.transition_capa_action(uuid,public.capa_action_status,text),public.reassign_capa_action(uuid,uuid,uuid,text),public.request_capa_due_date_extension(uuid,uuid,date,text),public.decide_capa_due_date_extension(uuid,boolean,text),public.authorize_capa_evidence_upload(uuid,uuid,text,bigint,text) to authenticated;
grant execute on function public.finalize_capa_evidence_verified(uuid,text) to service_role;

-- Submission, approval and closure gates are separate from the status matrix so
-- a transition can never manufacture its own prerequisites.
create or replace function public.capa_submission_ready(p_capa uuid) returns boolean language sql stable security definer set search_path=public as $$
 select exists(select 1 from public.capa_records c where c.id=p_capa and coalesce(nullif(trim(c.title_ar),''),nullif(trim(c.title_en),'')) is not null and coalesce(nullif(trim(c.description_ar),''),nullif(trim(c.description_en),'')) is not null and c.owner_id is not null and exists(select 1 from public.capa_sources s where s.capa_id=c.id));
$$;
create or replace function public.capa_approval_ready(p_capa uuid) returns boolean language sql stable security definer set search_path=public as $$
 select exists(select 1 from public.capa_records c where c.id=p_capa and c.approver_id is not null and c.reviewer_id is not null and c.target_completion_date is not null and c.root_cause_method_reference_id is not null and coalesce(nullif(trim(c.root_cause_summary),''),nullif(trim(c.corrective_action_summary),''),nullif(trim(c.preventive_action_summary),'')) is not null);
$$;
create or replace function public.capa_closure_ready(p_capa uuid) returns boolean language sql stable security definer set search_path=public as $$
 select exists(select 1 from public.capa_records c where c.id=p_capa and c.approver_id is not null and c.reviewer_id is not null and c.effectiveness_criteria is not null and c.closure_decision is not null)
 and exists(select 1 from public.capa_root_cause_analyses r where r.capa_id=p_capa and r.reviewed_by is not null and r.review_date is not null and coalesce(nullif(trim(r.root_cause_summary),''),nullif(trim(r.conclusion),'')) is not null)
 and not exists(select 1 from public.capa_actions a where a.capa_id=p_capa and a.status <> 'completed')
 and not exists(select 1 from public.capa_actions a where a.capa_id=p_capa and a.evidence_required and not exists(select 1 from public.capa_evidence e where e.capa_id=p_capa and e.action_id=a.id and e.scan_status='accepted'))
 and exists(select 1 from public.capa_effectiveness_reviews e where e.capa_id=p_capa and e.result='effective' and not e.reopen_decision)
 and not exists(select 1 from public.capa_due_date_extensions x where x.capa_id=p_capa and x.status='requested');
$$;
create or replace function public.transition_capa(p_capa uuid,p_to public.capa_status,p_reason text default null) returns void language plpgsql security definer set search_path=public as $$ declare c public.capa_records%rowtype; required text; begin
 select * into c from public.capa_records where id=p_capa for update; if not found or not public.capa_transition_allowed(c.status,p_to) then raise exception 'CAPA lifecycle transition denied'; end if;
 required:=case p_to when 'submitted' then 'capa.submit' when 'under_review' then 'capa.review' when 'approved' then 'capa.approve' when 'in_progress' then 'capa.start' when 'pending_evidence' then 'capa.complete_actions' when 'pending_effectiveness_review' then 'capa.review_effectiveness' when 'completed' then 'capa.close' when 'closed' then 'capa.close' when 'reopened' then 'capa.reopen' when 'rejected' then 'capa.reject' when 'cancelled' then 'capa.cancel' when 'archived' then 'capa.archive' else null end;
 if required is null or not public.can_capa(required,c.tenant_id,c.organization_id,c.facility_id) or (p_to in ('rejected','cancelled','reopened') and coalesce(trim(p_reason),'')='') or (p_to='submitted' and not public.capa_submission_ready(c.id)) or (p_to='approved' and (not public.capa_approval_ready(c.id) or auth.uid() in (c.created_by,c.owner_id) and not public.can_capa('capa.override_separation_of_duties',c.tenant_id,c.organization_id,c.facility_id))) or (p_to in ('completed','closed') and not public.capa_closure_ready(c.id)) or (p_to='closed' and auth.uid()=c.owner_id and not public.can_capa('capa.override_separation_of_duties',c.tenant_id,c.organization_id,c.facility_id)) then raise exception 'CAPA transition denied'; end if;
 perform set_config('app.capa_controlled','on',true); update public.capa_records set status=p_to,actual_completion_date=case when p_to='completed' then current_date else actual_completion_date end,closed_at=case when p_to='closed' then now() else closed_at end,closed_by=case when p_to='closed' then auth.uid() else closed_by end,archived_at=case when p_to='archived' then now() else archived_at end,archived_by=case when p_to='archived' then auth.uid() else archived_by end,updated_at=now(),updated_by=auth.uid() where id=c.id; perform public.record_capa_event(c.id,c.tenant_id,c.organization_id,c.facility_id,'capa.'||p_to::text,jsonb_build_object('from',c.status,'reason',nullif(trim(p_reason),'')));
end $$;

revoke all on function public.enforce_capa_extension_integrity(),public.capa_submission_ready(uuid),public.capa_approval_ready(uuid) from public,anon,authenticated;
grant execute on function public.transition_capa(uuid,public.capa_status,text) to authenticated;

-- Keep legacy public signatures safe while routing them to the controlled paths.
create or replace function public.assign_capa_action(p_capa uuid,p_title_ar text,p_title_en text,p_assignee uuid,p_due date) returns uuid language plpgsql security definer set search_path=public as $$
begin return public.create_capa_action(p_capa,p_title_ar,p_title_en,p_assignee,p_due,false); end $$;
create or replace function public.capa_transition_allowed(p_from public.capa_status,p_to public.capa_status) returns boolean language sql immutable as $$
 select (p_from,p_to) in (('draft','submitted'),('submitted','under_review'),('submitted','rejected'),('under_review','approved'),('under_review','rejected'),('approved','in_progress'),('approved','cancelled'),('in_progress','pending_evidence'),('in_progress','pending_effectiveness_review'),('pending_evidence','in_progress'),('pending_effectiveness_review','effective'),('pending_effectiveness_review','ineffective'),('ineffective','reopened'),('reopened','in_progress'),('effective','completed'),('completed','closed'),('closed','archived'),('rejected','archived'),('cancelled','archived'));
$$;
create or replace function public.record_capa_effectiveness(p_capa uuid,p_result text,p_comments text,p_reopen boolean) returns uuid language plpgsql security definer set search_path=public as $$ declare c public.capa_records%rowtype; id uuid; target public.capa_status; begin
 select cr.* into c from public.capa_records cr where cr.id=p_capa for update; if not found or c.status<>'pending_effectiveness_review' or not public.can_capa('capa.review_effectiveness',c.tenant_id,c.organization_id,c.facility_id) or auth.uid()=c.owner_id or p_result not in ('effective','partially_effective','ineffective') then raise exception 'CAPA effectiveness review denied'; end if;
 target:=case when p_reopen or p_result<>'effective' then 'ineffective' else 'effective' end; perform set_config('app.capa_controlled','on',true); insert into public.capa_effectiveness_reviews(capa_id,tenant_id,organization_id,facility_id,reviewer_id,criteria,result,reopen_decision,comments) values(c.id,c.tenant_id,c.organization_id,c.facility_id,auth.uid(),coalesce(nullif(trim(c.effectiveness_criteria),''),'Configured effectiveness criteria'),p_result,p_reopen,nullif(trim(p_comments),'')) returning id into id; update public.capa_records set status=target,updated_at=now(),updated_by=auth.uid() where id=c.id; perform public.record_capa_event(c.id,c.tenant_id,c.organization_id,c.facility_id,'capa.effectiveness_recorded',jsonb_build_object('review_id',id,'result',p_result,'reopen',p_reopen)); return id;
end $$;
revoke all on function public.assign_capa_action(uuid,text,text,uuid,date),public.record_capa_effectiveness(uuid,text,text,boolean) from public,anon;
grant execute on function public.assign_capa_action(uuid,text,text,uuid,date),public.record_capa_effectiveness(uuid,text,text,boolean) to authenticated;

-- Final hardening overrides. Confidentiality is permission-only (ownership or an
-- assignment never bypasses it), and evidence rework always leaves an audit reason.
create or replace function public.can_view_capa(p_capa_id uuid) returns boolean language plpgsql stable security definer set search_path=public as $$
declare c public.capa_records%rowtype;
begin
 if auth.uid() is null then return false; end if;
 select * into c from public.capa_records where id=p_capa_id;
 if not found or not public.scope_allowed(c.tenant_id,c.organization_id,c.facility_id) then return false; end if;
 if c.confidentiality_level <> 'normal' and not public.can_capa('capa.view_confidential',c.tenant_id,c.organization_id,c.facility_id) then return false; end if;
 if c.status in ('archived','closed') and not public.can_capa('capa.view_history',c.tenant_id,c.organization_id,c.facility_id) then return false; end if;
 return public.can_capa('capa.view',c.tenant_id,c.organization_id,c.facility_id)
   or auth.uid() in (c.owner_id,c.created_by,c.approver_id,c.reviewer_id)
   or exists(select 1 from public.capa_assignments a where a.capa_id=c.id and a.user_id=auth.uid() and public.policy_member_in_scope(a.user_id,a.tenant_id,a.organization_id,a.facility_id))
   or exists(select 1 from public.capa_actions a where a.capa_id=c.id and (a.assigned_user_id=auth.uid() or a.verification_user_id=auth.uid()) and public.policy_member_in_scope(auth.uid(),a.tenant_id,a.organization_id,a.facility_id));
end $$;
alter table public.capa_evidence add constraint capa_evidence_scan_status_controlled check(scan_status in ('pending','accepted','quarantined','failed')) not valid;
alter table public.capa_actions add column if not exists verification_required boolean not null default false;
create or replace function public.capa_transition_allowed(p_from public.capa_status,p_to public.capa_status) returns boolean language sql immutable as $$
 select (p_from,p_to) in (('draft','submitted'),('submitted','under_review'),('submitted','rejected'),('under_review','approved'),('under_review','rejected'),('approved','in_progress'),('approved','cancelled'),('in_progress','pending_evidence'),('in_progress','pending_effectiveness_review'),('pending_evidence','in_progress'),('pending_effectiveness_review','effective'),('pending_effectiveness_review','reopened'),('reopened','in_progress'),('effective','completed'),('completed','closed'),('closed','archived'),('rejected','archived'),('cancelled','archived'));
$$;
create or replace function public.transition_capa_action(p_action uuid,p_to public.capa_action_status,p_reason text default null) returns void language plpgsql security definer set search_path=public as $$ declare a public.capa_actions%rowtype; c public.capa_records%rowtype; allowed boolean; begin
 select * into a from public.capa_actions where id=p_action for update; if not found then raise exception 'CAPA action transition denied'; end if; select * into c from public.capa_records where id=a.capa_id for update;
 allowed=(a.status,p_to) in (('planned','assigned'),('assigned','in_progress'),('in_progress','blocked'),('blocked','in_progress'),('in_progress','pending_evidence'),('in_progress','pending_verification'),('in_progress','completed'),('pending_evidence','pending_verification'),('pending_evidence','completed'),('pending_verification','completed'),('pending_verification','rejected'),('rejected','in_progress'),('assigned','cancelled'),('in_progress','cancelled'),('blocked','cancelled'));
 if not allowed or c.status not in ('in_progress','reopened','pending_evidence') or (auth.uid()<>a.assigned_user_id and not public.can_capa('capa.complete_actions',c.tenant_id,c.organization_id,c.facility_id)) or (p_to in ('blocked','rejected','cancelled') and coalesce(trim(p_reason),'')='') or (p_to='pending_evidence' and not a.evidence_required) or (p_to='pending_verification' and (not a.verification_required or a.verification_user_id is null or (a.evidence_required and not exists(select 1 from public.capa_evidence e where e.action_id=a.id and e.scan_status='accepted')))) or (p_to='completed' and ((a.evidence_required and not exists(select 1 from public.capa_evidence e where e.action_id=a.id and e.scan_status='accepted')) or (a.verification_required and (a.status<>'pending_verification' or auth.uid()<>a.verification_user_id)))) then raise exception 'CAPA action transition denied'; end if;
 perform set_config('app.capa_controlled','on',true); update public.capa_actions set status=p_to,actual_start_date=case when p_to='in_progress' then coalesce(actual_start_date,current_date) else actual_start_date end,completion_date=case when p_to='completed' then current_date else completion_date end,verification_date=case when p_to='completed' and verification_required then current_date else verification_date end,verification_result=case when p_to='completed' and verification_required then 'verified' else verification_result end,rejection_reason=case when p_to='rejected' then trim(p_reason) else rejection_reason end where id=a.id; perform public.record_capa_event(c.id,c.tenant_id,c.organization_id,c.facility_id,'capa.action_'||p_to::text,jsonb_build_object('action_id',a.id,'reason',nullif(trim(p_reason),'')));
end $$;
create or replace function public.transition_capa(p_capa uuid,p_to public.capa_status,p_reason text default null) returns void language plpgsql security definer set search_path=public as $$ declare c public.capa_records%rowtype; required text; begin
 select * into c from public.capa_records where id=p_capa for update; if not found or not public.capa_transition_allowed(c.status,p_to) then raise exception 'CAPA lifecycle transition denied'; end if;
 required:=case p_to when 'submitted' then 'capa.submit' when 'under_review' then 'capa.review' when 'approved' then 'capa.approve' when 'in_progress' then case when c.status='pending_evidence' then 'capa.upload_evidence' else 'capa.start' end when 'pending_evidence' then 'capa.complete_actions' when 'pending_effectiveness_review' then 'capa.review_effectiveness' when 'completed' then 'capa.close' when 'closed' then 'capa.close' when 'reopened' then 'capa.reopen' when 'rejected' then 'capa.reject' when 'cancelled' then 'capa.cancel' when 'archived' then 'capa.archive' else null end;
 if required is null or not public.can_capa(required,c.tenant_id,c.organization_id,c.facility_id) or (p_to in ('rejected','cancelled','reopened') and coalesce(trim(p_reason),'')='') or (c.status='pending_evidence' and p_to='in_progress' and (coalesce(trim(p_reason),'')='' or not exists(select 1 from public.capa_evidence e where e.capa_id=c.id and e.scan_status in ('quarantined','failed')))) or (p_to='submitted' and not public.capa_submission_ready(c.id)) or (p_to='approved' and (not public.capa_approval_ready(c.id) or auth.uid() in (c.created_by,c.owner_id) and not public.can_capa('capa.override_separation_of_duties',c.tenant_id,c.organization_id,c.facility_id))) or (p_to in ('completed','closed') and not public.capa_closure_ready(c.id)) or (p_to='closed' and auth.uid()=c.owner_id and not public.can_capa('capa.override_separation_of_duties',c.tenant_id,c.organization_id,c.facility_id)) then raise exception 'CAPA transition denied'; end if;
 perform set_config('app.capa_controlled','on',true); update public.capa_records set status=p_to,actual_completion_date=case when p_to='completed' then current_date else actual_completion_date end,closed_at=case when p_to='closed' then now() else closed_at end,closed_by=case when p_to='closed' then auth.uid() else closed_by end,archived_at=case when p_to='archived' then now() else archived_at end,archived_by=case when p_to='archived' then auth.uid() else archived_by end,updated_at=now(),updated_by=auth.uid() where id=c.id; perform public.record_capa_event(c.id,c.tenant_id,c.organization_id,c.facility_id,'capa.'||p_to::text,jsonb_build_object('from',c.status,'reason',nullif(trim(p_reason),'')));
end $$;
create or replace function public.record_capa_effectiveness(p_capa uuid,p_result text,p_comments text,p_reopen boolean) returns uuid language plpgsql security definer set search_path=public as $$ declare c public.capa_records%rowtype; id uuid; target public.capa_status; begin
 select cr.* into c from public.capa_records cr where cr.id=p_capa for update; if not found or c.status<>'pending_effectiveness_review' or not public.can_capa('capa.review_effectiveness',c.tenant_id,c.organization_id,c.facility_id) or auth.uid()=c.owner_id or p_result not in ('effective','partially_effective','ineffective') then raise exception 'CAPA effectiveness review denied'; end if;
 target:=case when p_reopen or p_result<>'effective' then 'reopened' else 'effective' end; perform set_config('app.capa_controlled','on',true); insert into public.capa_effectiveness_reviews(capa_id,tenant_id,organization_id,facility_id,reviewer_id,criteria,result,reopen_decision,comments) values(c.id,c.tenant_id,c.organization_id,c.facility_id,auth.uid(),coalesce(nullif(trim(c.effectiveness_criteria),''),'Configured effectiveness criteria'),p_result,p_reopen,nullif(trim(p_comments),'')) returning public.capa_effectiveness_reviews.id into id; update public.capa_records cr set status=target,updated_at=now(),updated_by=auth.uid() where cr.id=c.id; perform public.record_capa_event(c.id,c.tenant_id,c.organization_id,c.facility_id,'capa.effectiveness_recorded',jsonb_build_object('review_id',id,'result',p_result,'reopened',target='reopened')); return id;
end $$;

-- Missing controlled writers would make the secure lifecycle unusable. These
-- functions derive every actor field from auth.uid() and reject closed records.
create or replace function public.configure_capa_for_review(p_capa uuid,p_reviewer uuid,p_approver uuid,p_target_due date,p_method uuid,p_effectiveness_criteria text) returns void language plpgsql security definer set search_path=public as $$ declare c public.capa_records%rowtype; begin
 select * into c from public.capa_records where id=p_capa for update; if not found or c.status not in ('draft','submitted','under_review') or not public.can_capa('capa.edit',c.tenant_id,c.organization_id,c.facility_id) or p_reviewer=p_approver or not public.policy_member_in_scope(p_reviewer,c.tenant_id,c.organization_id,c.facility_id) or not public.policy_member_in_scope(p_approver,c.tenant_id,c.organization_id,c.facility_id) or p_target_due is null or p_method is null or coalesce(trim(p_effectiveness_criteria),'')='' then raise exception 'CAPA configuration denied'; end if; perform set_config('app.capa_controlled','on',true); update public.capa_records set reviewer_id=p_reviewer,approver_id=p_approver,target_completion_date=p_target_due,root_cause_method_reference_id=p_method,effectiveness_criteria=trim(p_effectiveness_criteria),updated_at=now(),updated_by=auth.uid() where id=c.id; perform public.record_capa_event(c.id,c.tenant_id,c.organization_id,c.facility_id,'capa.configured'); end $$;
-- Approval and closure fields remain protected from direct client DML. This
-- controlled writer lets an authorized user complete the plan progressively.
create or replace function public.update_capa_plan(p_capa uuid,p_root_cause_summary text,p_corrective_action_summary text,p_preventive_action_summary text,p_closure_decision text) returns void language plpgsql security definer set search_path=public as $$ declare c public.capa_records%rowtype; before_values jsonb; after_values jsonb; begin
 select * into c from public.capa_records where id=p_capa for update;
 if not found or c.status not in ('draft','submitted','under_review') or auth.uid() is null or not public.policy_member_in_scope(auth.uid(),c.tenant_id,c.organization_id,c.facility_id) or not public.can_view_capa(c.id) or not public.can_capa('capa.edit',c.tenant_id,c.organization_id,c.facility_id) or coalesce(nullif(trim(p_root_cause_summary),''),nullif(trim(p_corrective_action_summary),''),nullif(trim(p_preventive_action_summary),'')) is null then raise exception 'CAPA plan update denied'; end if;
 before_values:=jsonb_build_object('root_cause_summary',c.root_cause_summary,'corrective_action_summary',c.corrective_action_summary,'preventive_action_summary',c.preventive_action_summary,'closure_decision',c.closure_decision);
 after_values:=jsonb_build_object('root_cause_summary',nullif(trim(p_root_cause_summary),''),'corrective_action_summary',nullif(trim(p_corrective_action_summary),''),'preventive_action_summary',nullif(trim(p_preventive_action_summary),''),'closure_decision',nullif(trim(p_closure_decision),''));
 perform set_config('app.capa_controlled','on',true);
 update public.capa_records set root_cause_summary=nullif(trim(p_root_cause_summary),''),corrective_action_summary=nullif(trim(p_corrective_action_summary),''),preventive_action_summary=nullif(trim(p_preventive_action_summary),''),closure_decision=nullif(trim(p_closure_decision),''),updated_at=now(),updated_by=auth.uid() where id=c.id;
 perform public.record_capa_event(c.id,c.tenant_id,c.organization_id,c.facility_id,'capa.plan_updated',jsonb_build_object('before',before_values,'after',after_values));
end $$;
create or replace function public.record_capa_root_cause(p_capa uuid,p_problem text,p_root_cause text,p_conclusion text,p_participants uuid[] default '{}') returns uuid language plpgsql security definer set search_path=public as $$ declare c public.capa_records%rowtype; id uuid; begin
 select * into c from public.capa_records where public.capa_records.id=p_capa for update; if not found or c.status not in ('draft','submitted','under_review','approved','in_progress','reopened') or not public.can_capa('capa.review',c.tenant_id,c.organization_id,c.facility_id) or coalesce(trim(p_problem),'')='' or coalesce(nullif(trim(p_root_cause),''),nullif(trim(p_conclusion),'')) is null or exists(select 1 from unnest(coalesce(p_participants,'{}'::uuid[])) u where not public.policy_member_in_scope(u,c.tenant_id,c.organization_id,c.facility_id)) then raise exception 'CAPA root-cause record denied'; end if; perform set_config('app.capa_controlled','on',true); insert into public.capa_root_cause_analyses(capa_id,tenant_id,organization_id,facility_id,method_reference_id,problem_statement,root_cause_summary,conclusion,participants,reviewed_by,review_date,created_by) values(c.id,c.tenant_id,c.organization_id,c.facility_id,c.root_cause_method_reference_id,trim(p_problem),nullif(trim(p_root_cause),''),nullif(trim(p_conclusion),''),coalesce(p_participants,'{}'),auth.uid(),current_date,auth.uid()) returning public.capa_root_cause_analyses.id into id; perform public.record_capa_event(c.id,c.tenant_id,c.organization_id,c.facility_id,'capa.root_cause_recorded',jsonb_build_object('root_cause_id',id)); return id; end $$;
create or replace function public.reassign_capa_action(p_action uuid,p_assignee uuid,p_verifier uuid,p_reason text) returns void language plpgsql security definer set search_path=public as $$ declare a public.capa_actions%rowtype; c public.capa_records%rowtype; begin select * into a from public.capa_actions where id=p_action for update; if not found then raise exception 'CAPA action reassignment denied'; end if; select * into c from public.capa_records where id=a.capa_id for update; if c.status not in ('approved','in_progress','reopened','pending_evidence') or not public.can_capa('capa.assign',c.tenant_id,c.organization_id,c.facility_id) or not public.policy_member_in_scope(p_assignee,c.tenant_id,c.organization_id,c.facility_id) or (p_verifier is not null and (p_verifier=p_assignee or not public.policy_member_in_scope(p_verifier,c.tenant_id,c.organization_id,c.facility_id))) or ((a.assigned_user_id,a.verification_user_id) is distinct from (p_assignee,p_verifier) and coalesce(trim(p_reason),'')='') then raise exception 'CAPA action reassignment denied'; end if; perform set_config('app.capa_controlled','on',true); update public.capa_actions set assigned_user_id=p_assignee,verification_user_id=p_verifier,verification_required=(p_verifier is not null),status=case when status='planned' then 'assigned' else status end where id=a.id; perform public.record_capa_event(c.id,c.tenant_id,c.organization_id,c.facility_id,'capa.action_reassigned',jsonb_build_object('action_id',a.id,'reason',trim(p_reason))); end $$;
create or replace function public.request_capa_due_date_extension(p_capa uuid,p_action uuid,p_new_due date,p_reason text) returns uuid language plpgsql security definer set search_path=public as $$ declare c public.capa_records%rowtype; a public.capa_actions%rowtype; old date; id uuid; begin
 select cr.* into c from public.capa_records cr where cr.id=p_capa for update; if not found or c.status in ('closed','archived','cancelled') then raise exception 'CAPA due-date extension request denied'; end if; if p_action is not null then select ca.* into a from public.capa_actions ca where ca.id=p_action and ca.capa_id=c.id for update; if not found then raise exception 'CAPA due-date extension request denied'; end if; end if; old:=case when p_action is null then c.target_completion_date else a.due_date end; if not public.can_capa('capa.extend_due_date',c.tenant_id,c.organization_id,c.facility_id) or old is null or p_new_due<=old or coalesce(trim(p_reason),'')='' or exists(select 1 from public.capa_due_date_extensions x where x.capa_id=c.id and x.action_id is not distinct from p_action and x.status='requested') then raise exception 'CAPA due-date extension request denied'; end if; perform set_config('app.capa_controlled','on',true); insert into public.capa_due_date_extensions(capa_id,action_id,tenant_id,organization_id,facility_id,old_due_date,requested_due_date,reason,requested_by) values(c.id,p_action,c.tenant_id,c.organization_id,c.facility_id,old,p_new_due,trim(p_reason),auth.uid()) returning public.capa_due_date_extensions.id into id; perform public.record_capa_event(c.id,c.tenant_id,c.organization_id,c.facility_id,'capa.due_date_extension_requested',jsonb_build_object('extension_id',id,'action_id',p_action)); return id; end $$;
revoke all on function public.configure_capa_for_review(uuid,uuid,uuid,date,uuid,text),public.update_capa_plan(uuid,text,text,text,text),public.record_capa_root_cause(uuid,text,text,text,uuid[]) from public,anon;
grant execute on function public.configure_capa_for_review(uuid,uuid,uuid,date,uuid,text),public.update_capa_plan(uuid,text,text,text,text),public.record_capa_root_cause(uuid,text,text,text,uuid[]) to authenticated;

-- Source links are created only while the referenced record is live and visible.
-- Losing source access later does not disclose source contents; it only leaves the
-- historic CAPA link auditable to users who remain entitled to CAPA itself.
create or replace function public.capa_source_allowed(p_module text,p_type text,p_id uuid,p_t uuid,p_o uuid,p_f uuid) returns boolean language plpgsql security definer set search_path=public as $$ begin
 if p_module='manual' and p_type='manual' and p_id is null then return true; end if;
 if p_module='medication_errors' and p_type='medication_error' then return exists(select 1 from public.medication_error_reports x where x.id=p_id and x.tenant_id=p_t and x.organization_id=p_o and x.facility_id is not distinct from p_f and x.archived_at is null and public.can_medication_error('medication_errors.view',p_t,p_o,p_f)); end if;
 if p_module='policies' and p_type='policy' then return exists(select 1 from public.policy_definitions x where x.id=p_id and x.tenant_id=p_t and x.organization_id=p_o and x.facility_id is not distinct from p_f and x.status<>'archived' and (public.can_policy('policies.view',p_t,p_o,p_f) or public.can_policy('policies.edit',p_t,p_o,p_f) or public.can_policy('policies.review',p_t,p_o,p_f))); end if;
 raise exception 'CAPA source adapter is not implemented';
end $$;

-- Expired, unfinalized uploads are inaccessible immediately. The trusted storage
-- worker consumes this list and deletes the corresponding private objects; clients
-- have no UPDATE/DELETE Storage policy and cannot replace retained evidence.
create or replace function public.list_expired_capa_upload_keys() returns table(authorization_id uuid,storage_key text) language sql stable security definer set search_path=public as $$
 select id,storage_key from public.capa_upload_authorizations where finalized_at is null and expires_at<=now();
$$;
revoke all on function public.list_expired_capa_upload_keys() from public,anon,authenticated;
grant execute on function public.list_expired_capa_upload_keys() to service_role;
