-- Additive final policy lifecycle hardening. Existing records are preserved.
insert into public.permissions(key,name_ar,name_en) values
 ('policies.view_history','عرض سجل السياسات','View policy history'),
 ('policies.submit','إرسال السياسة للمراجعة','Submit policy for review'),
 ('policies.override_approval_assignment','تجاوز تعيين المعتمد','Override policy approver assignment') on conflict(key) do nothing;
insert into public.role_permissions(role_id,permission_id) select r.id,p.id from public.roles r join public.permissions p on p.key in ('policies.view_history','policies.submit','policies.override_approval_assignment') where r.key='platform_owner' on conflict do nothing;

-- A view must include both the definition and version state. History is never implied by policies.view.
drop policy if exists policy_definitions_read on public.policy_definitions;
drop policy if exists policy_versions_read on public.policy_versions;
create policy policy_definitions_read on public.policy_definitions for select using(
 (status='published' and public.can_policy('policies.view',tenant_id,organization_id,facility_id))
 or (status='archived' and public.can_policy('policies.view_history',tenant_id,organization_id,facility_id))
 or (status in ('draft','under_review','approved') and (public.can_policy('policies.edit',tenant_id,organization_id,facility_id) or public.can_policy('policies.review',tenant_id,organization_id,facility_id) or public.can_policy('policies.approve',tenant_id,organization_id,facility_id))));
create policy policy_versions_read on public.policy_versions for select using(exists(select 1 from public.policy_definitions d where d.id=policy_definition_id and d.tenant_id=tenant_id and d.organization_id=organization_id and d.facility_id is not distinct from facility_id and (
 (d.status='published' and status='published' and public.can_policy('policies.view',tenant_id,organization_id,facility_id))
 or (d.status in ('published','archived') and status in ('published','superseded','archived') and public.can_policy('policies.view_history',tenant_id,organization_id,facility_id))
 or (status='draft' and public.can_policy('policies.edit',tenant_id,organization_id,facility_id))
 or (status='under_review' and (public.can_policy('policies.review',tenant_id,organization_id,facility_id) or public.can_policy('policies.approve',tenant_id,organization_id,facility_id)))
 or (status='approved' and (public.can_policy('policies.approve',tenant_id,organization_id,facility_id) or public.can_policy('policies.publish',tenant_id,organization_id,facility_id))))));

create or replace function public.can_view_policy_document(p_version uuid) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.policy_versions v join public.policy_definitions d on d.id=v.policy_definition_id where v.id=p_version and v.tenant_id=d.tenant_id and v.organization_id=d.organization_id and v.facility_id is not distinct from d.facility_id and ((d.status='published' and v.status='published' and public.can_policy('policies.view',v.tenant_id,v.organization_id,v.facility_id)) or (d.status in ('published','archived') and v.status in ('published','superseded','archived') and public.can_policy('policies.view_history',v.tenant_id,v.organization_id,v.facility_id)) or (v.status='draft' and public.can_policy('policies.edit',v.tenant_id,v.organization_id,v.facility_id)) or (v.status='under_review' and (public.can_policy('policies.review',v.tenant_id,v.organization_id,v.facility_id) or public.can_policy('policies.approve',v.tenant_id,v.organization_id,v.facility_id))) or (v.status='approved' and (public.can_policy('policies.approve',v.tenant_id,v.organization_id,v.facility_id) or public.can_policy('policies.publish',v.tenant_id,v.organization_id,v.facility_id))))); $$;

create or replace function public.submit_policy_for_review(p_version uuid) returns void language plpgsql security definer set search_path=public as $$ declare v public.policy_versions%rowtype; begin select * into v from public.policy_versions where id=p_version for update; if not found or v.status<>'draft' or not public.can_policy('policies.edit',v.tenant_id,v.organization_id,v.facility_id) or not public.can_policy('policies.submit',v.tenant_id,v.organization_id,v.facility_id) then raise exception 'Policy review submission denied'; end if; perform set_config('app.policy_lifecycle','on',true); update public.policy_versions set status='under_review',updated_at=now(),updated_by=auth.uid() where id=v.id; perform public.record_policy_event(v.policy_definition_id,v.id,v.tenant_id,v.organization_id,v.facility_id,'policy.submitted'); end $$;
create or replace function public.approve_policy_version(p_version uuid) returns void language plpgsql security definer set search_path=public as $$ declare v public.policy_versions%rowtype; d public.policy_definitions%rowtype; begin select * into v from public.policy_versions where id=p_version for update; if not found then raise exception 'Policy approval denied'; end if; select * into d from public.policy_definitions where id=v.policy_definition_id and tenant_id=v.tenant_id and organization_id=v.organization_id and facility_id is not distinct from v.facility_id for update; if not found or v.status<>'under_review' or not public.can_policy('policies.approve',v.tenant_id,v.organization_id,v.facility_id) or auth.uid()=v.created_by or auth.uid()=d.owner_id or (d.approver_id is not null and d.approver_id<>auth.uid() and not public.can_policy('policies.override_approval_assignment',v.tenant_id,v.organization_id,v.facility_id)) then raise exception 'Policy approval denied'; end if; perform set_config('app.policy_lifecycle','on',true); update public.policy_versions set status='approved',approved_at=now(),approved_by=auth.uid(),updated_at=now(),updated_by=auth.uid() where id=v.id; perform public.record_policy_event(v.policy_definition_id,v.id,v.tenant_id,v.organization_id,v.facility_id,'policy.approved'); end $$;

-- Browser-side metadata finalization is intentionally unavailable. A trusted server records an upload session then verifies storage before finalization.
create table public.policy_upload_authorizations(id uuid primary key default gen_random_uuid(),policy_version_id uuid not null references public.policy_versions(id) on delete restrict,tenant_id uuid not null references public.tenants(id),organization_id uuid not null references public.organizations(id),facility_id uuid references public.facilities(id),uploader_id uuid not null references public.user_profiles(id),storage_key text not null,expected_size bigint not null check(expected_size between 1 and 52428800),expected_checksum text not null check(expected_checksum ~ '^[A-Fa-f0-9]{64}$'),expires_at timestamptz not null,finalized_at timestamptz,malware_scan_status text not null default 'pending' check(malware_scan_status in ('pending','accepted','rejected')),created_at timestamptz not null default now(),unique(storage_key));
alter table public.policy_upload_authorizations enable row level security;
create policy policy_upload_authorizations_owner on public.policy_upload_authorizations for select using(uploader_id=auth.uid() and public.can_policy('policies.edit',tenant_id,organization_id,facility_id));
create or replace function public.policy_actor_has_permission(p_actor uuid,p_permission text,p_t uuid,p_o uuid,p_f uuid) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.user_role_assignments ura join public.roles r on r.id=ura.role_id join public.role_permissions rp on rp.role_id=r.id join public.permissions p on p.id=rp.permission_id where ura.user_id=p_actor and ura.active and p.key in (p_permission,'platform.full_access') and (ura.tenant_id is null or ura.tenant_id=p_t) and (ura.organization_id is null or ura.organization_id=p_o) and (ura.facility_id is null or ura.facility_id=p_f)); $$;
create or replace function public.authorize_policy_upload(p_version uuid,p_filename text,p_size bigint,p_checksum text) returns uuid language plpgsql security definer set search_path=public as $$ declare v public.policy_versions%rowtype; id uuid; safe_name text; key text; begin select * into v from public.policy_versions where id=p_version for update; if not found or v.status<>'draft' or not public.can_policy('policies.edit',v.tenant_id,v.organization_id,v.facility_id) or p_size not between 1 and 52428800 or p_checksum !~ '^[A-Fa-f0-9]{64}$' then raise exception 'Policy upload authorization denied'; end if; safe_name:=regexp_replace(lower(coalesce(p_filename,'')),'[^a-z0-9._-]','_','g'); if safe_name='' or safe_name ~ '(\.docm|\.xlsm|\.pptm|\.(exe|js|sh|bat|cmd|com)$)' or safe_name ~ '.*\.(pdf|docx|doc|xlsx|xls|pptx|jpg|jpeg|png|webp)\.(exe|js|sh|bat|cmd)$' then raise exception 'Unsafe policy filename'; end if; key:='tenant/'||v.tenant_id||'/organization/'||v.organization_id||'/facility/'||coalesce(v.facility_id::text,'global')||'/policies/'||v.policy_definition_id||'/versions/'||v.id||'/'||gen_random_uuid()||'-'||safe_name; insert into public.policy_upload_authorizations(policy_version_id,tenant_id,organization_id,facility_id,uploader_id,storage_key,expected_size,expected_checksum,expires_at) values(v.id,v.tenant_id,v.organization_id,v.facility_id,auth.uid(),key,p_size,p_checksum,now()+interval '15 minutes') returning id into id; return id; end $$;
create or replace function public.finalize_policy_document_verified(p_authorization uuid,p_mime text,p_language public.content_language,p_label text,p_preview boolean,p_source text,p_extracted text default null) returns uuid language plpgsql security definer set search_path=public,storage as $$ declare a public.policy_upload_authorizations%rowtype; v public.policy_versions%rowtype; object_size bigint; id uuid; begin if auth.role()<>'service_role' then raise exception 'Trusted policy upload finalization requires service role'; end if; select * into a from public.policy_upload_authorizations where id=p_authorization for update; if not found or a.finalized_at is not null or a.expires_at<=now() or a.malware_scan_status not in ('accepted','pending') then raise exception 'Policy upload finalization denied'; end if; select * into v from public.policy_versions where id=a.policy_version_id for update; if not found or v.status<>'draft' then raise exception 'Policy upload finalization denied'; end if; select nullif(metadata->>'size','')::bigint into object_size from storage.objects where bucket_id='policy-documents' and name=a.storage_key; if object_size is null or object_size<>a.expected_size then raise exception 'Policy upload object verification failed'; end if; if coalesce(trim(p_label),'')='' or p_source not in ('upload','word_import') or p_mime not in ('application/pdf','application/vnd.openxmlformats-officedocument.wordprocessingml.document','application/msword','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','application/vnd.ms-excel','application/vnd.openxmlformats-officedocument.presentationml.presentation','image/jpeg','image/png','image/webp') then raise exception 'Policy upload metadata is invalid'; end if; perform set_config('app.policy_lifecycle','on',true); insert into public.policy_documents(policy_version_id,tenant_id,organization_id,facility_id,storage_bucket,storage_key,checksum,mime_type,byte_size,document_language,version_label,preview_available,extracted_text,source_type,uploaded_by) values(v.id,v.tenant_id,v.organization_id,v.facility_id,'policy-documents',a.storage_key,a.expected_checksum,p_mime,a.expected_size,p_language,trim(p_label),p_preview,p_extracted,p_source,a.uploader_id) returning id into id; update public.policy_upload_authorizations set finalized_at=now() where id=a.id; perform public.record_policy_event(v.policy_definition_id,v.id,v.tenant_id,v.organization_id,v.facility_id,'policy.document_uploaded',jsonb_build_object('document_id',id)); return id; end $$;
create or replace function public.delete_draft_policy_document(p_document uuid,p_actor uuid) returns void language plpgsql security definer set search_path=public as $$ declare d public.policy_documents%rowtype; v public.policy_versions%rowtype; begin if auth.role()<>'service_role' then raise exception 'Trusted policy document deletion requires service role'; end if; select * into d from public.policy_documents where id=p_document for update; if not found then raise exception 'Policy document deletion denied'; end if; select * into v from public.policy_versions where id=d.policy_version_id for update; if not found or v.status<>'draft' or not public.policy_member_in_scope(p_actor,v.tenant_id,v.organization_id,v.facility_id) or not public.policy_actor_has_permission(p_actor,'policies.edit',v.tenant_id,v.organization_id,v.facility_id) then raise exception 'Policy document deletion denied'; end if; perform set_config('app.policy_lifecycle','on',true); delete from public.policy_documents where id=d.id; perform public.record_policy_event(v.policy_definition_id,v.id,v.tenant_id,v.organization_id,v.facility_id,'policy.document_deleted',jsonb_build_object('document_id',d.id)); end $$;

-- Legacy finalization signature remains only as a denied compatibility endpoint; clients must use the server-only verified path.
create or replace function public.finalize_policy_document(p_version uuid,p_bucket text,p_key text,p_checksum text,p_mime text,p_size bigint,p_language public.content_language,p_label text,p_preview boolean,p_source text,p_extracted text default null) returns uuid language plpgsql security definer set search_path=public as $$ begin if p_bucket <> 'policy-documents' then raise exception 'Policy document bucket is invalid'; end if; raise exception 'Trusted policy upload finalization is required'; end $$;

revoke all on function public.finalize_policy_document(uuid,text,text,text,text,bigint,public.content_language,text,boolean,text,text) from public,anon,authenticated;
revoke all on function public.policy_actor_has_permission(uuid,text,uuid,uuid,uuid) from public,anon,authenticated;
revoke all on function public.authorize_policy_upload(uuid,text,bigint,text),public.finalize_policy_document_verified(uuid,text,public.content_language,text,boolean,text,text),public.delete_draft_policy_document(uuid,uuid) from public,anon;
grant execute on function public.authorize_policy_upload(uuid,text,bigint,text) to authenticated;
grant execute on function public.finalize_policy_document_verified(uuid,text,public.content_language,text,boolean,text,text),public.delete_draft_policy_document(uuid,uuid) to service_role;
