-- Additive cleanup completion: reject unsafe names before Storage and use prepare/complete deletion around trusted object removal.
create or replace function public.authorize_policy_upload(p_version uuid,p_filename text,p_size bigint,p_checksum text) returns uuid language plpgsql security definer set search_path=public as $$ declare v public.policy_versions%rowtype; id uuid; safe_name text; key text; begin select * into v from public.policy_versions where id=p_version for update; if not found or v.status<>'draft' or not public.can_policy('policies.edit',v.tenant_id,v.organization_id,v.facility_id) or p_size not between 1 and 52428800 or p_checksum !~ '^[A-Fa-f0-9]{64}$' then raise exception 'Policy upload authorization denied'; end if; safe_name:=regexp_replace(lower(coalesce(trim(p_filename),'')),'[^a-z0-9._-]','_','g'); if safe_name !~ '^[a-z0-9][a-z0-9_-]*\.(pdf|docx|doc|xlsx|xls|pptx|jpg|jpeg|png|webp)$' then raise exception 'Unsupported or unsafe policy filename'; end if; key:='tenant/'||v.tenant_id||'/organization/'||v.organization_id||'/facility/'||coalesce(v.facility_id::text,'global')||'/policies/'||v.policy_definition_id||'/versions/'||v.id||'/'||gen_random_uuid()||'-'||safe_name; insert into public.policy_upload_authorizations(policy_version_id,tenant_id,organization_id,facility_id,uploader_id,storage_key,expected_size,expected_checksum,expires_at) values(v.id,v.tenant_id,v.organization_id,v.facility_id,auth.uid(),key,p_size,p_checksum,now()+interval '15 minutes') returning id into id; return id; end $$;

create table public.policy_document_deletion_requests(id uuid primary key default gen_random_uuid(),document_id uuid not null references public.policy_documents(id) on delete restrict,tenant_id uuid not null references public.tenants(id),organization_id uuid not null references public.organizations(id),facility_id uuid references public.facilities(id),storage_bucket text not null,storage_key text not null,requested_by uuid not null references public.user_profiles(id),status text not null default 'requested' check(status in ('requested','storage_deleted','completed','storage_delete_failed','expired')),failure_reason text,requested_at timestamptz not null default now(),completed_at timestamptz);
create unique index policy_document_deletion_requests_active_unique on public.policy_document_deletion_requests(document_id) where status in ('requested','storage_deleted');
alter table public.policy_document_deletion_requests enable row level security;
create policy policy_document_deletion_requests_owner on public.policy_document_deletion_requests for select using(requested_by=auth.uid() and public.can_policy('policies.edit',tenant_id,organization_id,facility_id));
create or replace function public.prepare_draft_policy_document_deletion(p_document uuid) returns uuid language plpgsql security definer set search_path=public as $$ declare d public.policy_documents%rowtype; v public.policy_versions%rowtype; id uuid; begin select * into d from public.policy_documents where id=p_document for update; if not found then raise exception 'Policy document deletion denied'; end if; select * into v from public.policy_versions where id=d.policy_version_id for update; if not found or v.status<>'draft' or not public.can_policy('policies.edit',v.tenant_id,v.organization_id,v.facility_id) then raise exception 'Policy document deletion denied'; end if; insert into public.policy_document_deletion_requests(document_id,tenant_id,organization_id,facility_id,storage_bucket,storage_key,requested_by) values(d.id,d.tenant_id,d.organization_id,d.facility_id,d.storage_bucket,d.storage_key,auth.uid()) returning id into id; perform set_config('app.policy_lifecycle','on',true); perform public.record_policy_event(v.policy_definition_id,v.id,v.tenant_id,v.organization_id,v.facility_id,'policy.document_deletion_prepared',jsonb_build_object('document_id',d.id,'deletion_request_id',id)); return id; end $$;
create or replace function public.complete_draft_policy_document_deletion(p_request uuid) returns void language plpgsql security definer set search_path=public,storage as $$ declare r public.policy_document_deletion_requests%rowtype; d public.policy_documents%rowtype; v public.policy_versions%rowtype; begin if auth.role()<>'service_role' then raise exception 'Trusted policy document deletion completion requires service role'; end if; select * into r from public.policy_document_deletion_requests where id=p_request for update; if not found or r.status not in ('requested','storage_deleted') then raise exception 'Policy document deletion completion denied'; end if; select * into d from public.policy_documents where id=r.document_id for update; if not found then raise exception 'Policy document deletion completion denied'; end if; select * into v from public.policy_versions where id=d.policy_version_id for update; if not found or v.status<>'draft' or not public.policy_member_in_scope(r.requested_by,v.tenant_id,v.organization_id,v.facility_id) or not public.policy_actor_has_permission(r.requested_by,'policies.edit',v.tenant_id,v.organization_id,v.facility_id) then raise exception 'Policy document deletion completion denied'; end if; if exists(select 1 from storage.objects where bucket_id=r.storage_bucket and name=r.storage_key) then raise exception 'Policy storage deletion must succeed before metadata deletion'; end if; delete from public.policy_documents where id=d.id; update public.policy_document_deletion_requests set status='completed',completed_at=now() where id=r.id; perform public.record_policy_event_for_actor(v.policy_definition_id,v.id,v.tenant_id,v.organization_id,v.facility_id,r.requested_by,'policies.edit','policy.document_deleted',jsonb_build_object('document_id',d.id,'deletion_request_id',r.id)); end $$;
-- Prevent accidental use of the old metadata-only API.
create or replace function public.delete_draft_policy_document(p_document uuid,p_actor uuid) returns void language plpgsql security definer set search_path=public as $$ begin raise exception 'Use prepare_draft_policy_document_deletion and trusted completion'; end $$;

revoke all on function public.prepare_draft_policy_document_deletion(uuid),public.complete_draft_policy_document_deletion(uuid),public.delete_draft_policy_document(uuid,uuid) from public,anon;
grant execute on function public.prepare_draft_policy_document_deletion(uuid) to authenticated;
grant execute on function public.complete_draft_policy_document_deletion(uuid) to service_role;
