insert into public.roles(key,name_ar,name_en,scope_level,system_role) values ('medication_error_reporter','مبلّغ خطأ دوائي','Medication Error Reporter','facility',true),('medication_error_reviewer','مراجع أخطاء الدواء','Medication Error Reviewer','facility',true),('medication_error_manager','مدير ومعتمد أخطاء الدواء','Medication Error Manager','facility',true),('medication_error_quality_administrator','مدير جودة أخطاء الدواء','Medication Error Quality Administrator','organization',true) on conflict(key) do nothing;
insert into public.role_permissions(role_id,permission_id) select r.id,p.id from public.roles r join public.permissions p on (r.key='medication_error_reporter' and p.key in ('medication_errors.create','medication_errors.edit_draft','medication_errors.submit')) or (r.key='medication_error_reviewer' and p.key in ('medication_errors.view','medication_errors.review','medication_errors.assign')) or (r.key='medication_error_manager' and p.key in ('medication_errors.view','medication_errors.review','medication_errors.assign','medication_errors.approve','medication_errors.close','medication_errors.reopen','medication_errors.export')) or (r.key='medication_error_quality_administrator' and p.key in ('medication_errors.view','medication_errors.review','medication_errors.assign','medication_errors.approve','medication_errors.close','medication_errors.reopen','medication_errors.export','medication_errors.manage_configuration')) on conflict do nothing;

create or replace function public.enforce_medication_error_integrity() returns trigger language plpgsql security definer set search_path=public as $$
begin
 if new.organization_id<>old.organization_id or new.tenant_id<>old.tenant_id or new.facility_id is distinct from old.facility_id or new.reported_by<>old.reported_by or new.created_by is distinct from old.created_by or new.reference_number<>old.reference_number then raise exception 'Medication error identity and scope are immutable' using errcode='23514'; end if;
 if old.status<>'draft' and (new.incident_type,new.ncc_merp_category,new.severity,new.outcome_classification,new.medication_stage,new.occurred_at,new.department_id,new.title,new.description,new.immediate_action,new.contributing_factors,new.error_categories,new.risk_score,new.witness_information,new.investigation,new.root_cause_analysis,new.corrective_actions,new.preventive_actions,new.follow_up,new.verification,new.closure_notes) is distinct from (old.incident_type,old.ncc_merp_category,old.severity,old.outcome_classification,old.medication_stage,old.occurred_at,old.department_id,old.title,old.description,old.immediate_action,old.contributing_factors,old.error_categories,old.risk_score,old.witness_information,old.investigation,old.root_cause_analysis,old.corrective_actions,old.preventive_actions,old.follow_up,old.verification,old.closure_notes) and current_setting('app.medication_error_revision',true)<>'on' then raise exception 'Submitted material content requires controlled revision' using errcode='23514'; end if;
 if (new.status<>old.status or new.owner_id is distinct from old.owner_id or new.reviewer_id is distinct from old.reviewer_id) and current_setting('app.medication_error_controlled',true)<>'on' then raise exception 'Status and assignment require controlled workflow functions' using errcode='23514'; end if;
 if new.department_id is not null and not exists(select 1 from public.departments d where d.id=new.department_id and d.tenant_id=new.tenant_id and d.organization_id=new.organization_id and d.facility_id is not distinct from new.facility_id) then raise exception 'Medication error department scope mismatch' using errcode='23503'; end if;
 return new;
end $$;
drop trigger medication_errors_immutable_submitted on public.medication_error_reports;
create trigger medication_errors_full_integrity before update on public.medication_error_reports for each row execute function public.enforce_medication_error_integrity();
create or replace function public.enforce_medication_error_child_scope() returns trigger language plpgsql security definer set search_path=public as $$ begin if not exists(select 1 from public.medication_error_reports r where r.id=new.report_id and r.tenant_id=new.tenant_id and r.organization_id=new.organization_id and r.facility_id is not distinct from new.facility_id) then raise exception 'Medication error child scope mismatch' using errcode='23503'; end if; return new; end $$;
create trigger medication_revision_scope before insert or update on public.medication_error_revisions for each row execute function public.enforce_medication_error_child_scope();
create trigger medication_comment_scope before insert or update on public.medication_error_comments for each row execute function public.enforce_medication_error_child_scope();
create trigger medication_attachment_scope before insert or update on public.medication_error_attachments for each row execute function public.enforce_medication_error_child_scope();
create trigger medication_timeline_scope before insert or update on public.medication_error_timeline for each row execute function public.enforce_medication_error_child_scope();
create trigger medication_capa_scope before insert or update on public.medication_error_capa_links for each row execute function public.enforce_medication_error_child_scope();

drop policy medication_reports_read on public.medication_error_reports; drop policy medication_reports_draft_update on public.medication_error_reports;
create policy medication_reports_read on public.medication_error_reports for select using((status='draft' and reported_by=auth.uid() and public.can_medication_error('medication_errors.edit_draft',tenant_id,organization_id,facility_id)) or (status<>'draft' and public.can_medication_error('medication_errors.view',tenant_id,organization_id,facility_id)));
create policy medication_reports_draft_update on public.medication_error_reports for update using(status='draft' and reported_by=auth.uid() and public.can_medication_error('medication_errors.edit_draft',tenant_id,organization_id,facility_id)) with check(status='draft' and reported_by=auth.uid() and public.scope_allowed(tenant_id,organization_id,facility_id));
create policy medication_attachment_insert on public.medication_error_attachments for insert with check(created_by=auth.uid() and public.can_medication_error('medication_errors.create',tenant_id,organization_id,facility_id));
create policy medication_capa_read on public.medication_error_capa_links for select using(public.can_medication_error('medication_errors.view',tenant_id,organization_id,facility_id));
create policy medication_capa_insert on public.medication_error_capa_links for insert with check(created_by=auth.uid() and public.can_medication_error('medication_errors.review',tenant_id,organization_id,facility_id));
create policy medication_config_write on public.medication_error_configurations for all using(public.can_medication_error('medication_errors.manage_configuration',tenant_id,organization_id,facility_id)) with check(public.can_medication_error('medication_errors.manage_configuration',tenant_id,organization_id,facility_id));
create or replace function public.transition_medication_error(p_report_id uuid,p_to public.medication_error_status,p_reason text default null) returns void language plpgsql security definer set search_path=public as $$ declare r public.medication_error_reports%rowtype; required_permission text; begin select * into r from public.medication_error_reports where id=p_report_id for update; if not found then raise exception 'Report not found'; end if; required_permission:=case when p_to='submitted' then 'medication_errors.submit' when p_to in ('triage','under_investigation','awaiting_information','awaiting_approval','follow_up','verified') then 'medication_errors.review' when p_to='closed' then 'medication_errors.close' when p_to='reopened' then 'medication_errors.reopen' else null end; if required_permission is null or not public.can_medication_error(required_permission,r.tenant_id,r.organization_id,r.facility_id) then raise exception 'Workflow permission denied'; end if; if not ((r.status='draft' and p_to='submitted') or (r.status='submitted' and p_to in ('triage','awaiting_information')) or (r.status='triage' and p_to in ('under_investigation','awaiting_information')) or (r.status='under_investigation' and p_to in ('awaiting_information','awaiting_approval','follow_up')) or (r.status='awaiting_information' and p_to in ('triage','under_investigation')) or (r.status='awaiting_approval' and p_to in ('follow_up','closed')) or (r.status='follow_up' and p_to in ('verified','under_investigation')) or (r.status='verified' and p_to in ('closed','under_investigation')) or (r.status='closed' and p_to='reopened') or (r.status='reopened' and p_to in ('triage','under_investigation'))) then raise exception 'Invalid workflow transition'; end if; if p_to='submitted' and (r.title='' or r.description='' or r.ncc_merp_category is null) then raise exception 'Submission fields incomplete'; end if; if p_to='closed' and (r.verification is null or r.closure_notes is null) then raise exception 'Closure fields incomplete'; end if; if p_to='reopened' and coalesce(p_reason,'')='' then raise exception 'Reopen reason required'; end if; perform set_config('app.medication_error_controlled','on',true); update public.medication_error_reports set status=p_to,submitted_at=case when p_to='submitted' then now() else submitted_at end,closed_at=case when p_to='closed' then now() else closed_at end,reopened_at=case when p_to='reopened' then now() else reopened_at end,updated_at=now(),updated_by=auth.uid() where id=r.id; insert into public.medication_error_timeline(report_id,tenant_id,organization_id,facility_id,action,from_status,to_status,note,created_by) values(r.id,r.tenant_id,r.organization_id,r.facility_id,'workflow.transition',r.status,p_to,p_reason,auth.uid()); end $$;
revoke all on function public.transition_medication_error(uuid,public.medication_error_status,text) from public,anon; grant execute on function public.transition_medication_error(uuid,public.medication_error_status,text) to authenticated;
revoke all on function public.enforce_medication_error_integrity() from public,anon,authenticated; revoke all on function public.enforce_medication_error_child_scope() from public,anon,authenticated;
