-- Policies & Procedures is additive. Files live in Supabase Storage; PostgreSQL stores metadata only.
do $$ begin create type public.policy_status as enum ('draft','under_review','approved','published','superseded','archived'); exception when duplicate_object then null; end $$;
insert into public.permissions(key,name_ar,name_en) values
 ('policies.view','عرض السياسات والإجراءات','View policies and procedures'),('policies.create','إنشاء السياسات والإجراءات','Create policies and procedures'),('policies.edit','تعديل مسودات السياسات','Edit policy drafts'),('policies.review','مراجعة السياسات','Review policies'),('policies.approve','اعتماد السياسات','Approve policies'),('policies.publish','نشر السياسات','Publish policies'),('policies.archive','أرشفة السياسات','Archive policies'),('policies.restore','استعادة السياسات','Restore policies'),('policies.acknowledge','الإقرار بقراءة السياسات','Acknowledge policies'),('policies.export','تصدير السياسات','Export policies'),('policies.manage_configuration','إدارة إعدادات السياسات','Manage policy configuration') on conflict(key) do nothing;
insert into public.role_permissions(role_id,permission_id) select r.id,p.id from public.roles r join public.permissions p on p.key like 'policies.%' where r.key='platform_owner' on conflict do nothing;

create table public.policy_definitions(
 id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.tenants(id),organization_id uuid not null references public.organizations(id),facility_id uuid references public.facilities(id),department_id uuid references public.departments(id),policy_id text not null,policy_number text not null,category_reference_id uuid references public.reference_data_items(id),owner_id uuid not null references public.user_profiles(id),approver_id uuid references public.user_profiles(id),status public.policy_status not null default 'draft',current_version_id uuid,title_ar text,title_en text,check(coalesce(nullif(title_ar,''),nullif(title_en,'')) is not null),created_at timestamptz not null default now(),created_by uuid not null references public.user_profiles(id),updated_at timestamptz not null default now(),updated_by uuid not null references public.user_profiles(id),archived_at timestamptz,archived_by uuid references public.user_profiles(id));
create table public.policy_versions(
 id uuid primary key default gen_random_uuid(),policy_definition_id uuid not null references public.policy_definitions(id) on delete restrict,tenant_id uuid not null references public.tenants(id),organization_id uuid not null references public.organizations(id),facility_id uuid references public.facilities(id),version_major integer not null check(version_major>0),version_minor integer not null check(version_minor>=0),status public.policy_status not null default 'draft',content_language public.content_language not null default 'bilingual',title_ar text,title_en text,check(coalesce(nullif(title_ar,''),nullif(title_en,'')) is not null),description_ar text,description_en text,keywords text[] not null default '{}',tags text[] not null default '{}',change_summary text not null,workflow_instance_id uuid references public.workflow_instances(id),effective_date date,review_date date,expiry_date date,approved_at timestamptz,approved_by uuid references public.user_profiles(id),published_at timestamptz,published_by uuid references public.user_profiles(id),created_at timestamptz not null default now(),created_by uuid not null references public.user_profiles(id),updated_at timestamptz not null default now(),updated_by uuid not null references public.user_profiles(id),unique(policy_definition_id,version_major,version_minor));
create unique index policy_definitions_policy_id_scope_unique on public.policy_definitions(tenant_id,organization_id,coalesce(facility_id,'00000000-0000-0000-0000-000000000000'::uuid),policy_id);
create unique index policy_definitions_policy_number_scope_unique on public.policy_definitions(tenant_id,organization_id,coalesce(facility_id,'00000000-0000-0000-0000-000000000000'::uuid),policy_number);
alter table public.policy_definitions add constraint policy_definitions_current_version_fk foreign key(current_version_id) references public.policy_versions(id) deferrable initially deferred;
create table public.policy_documents(
 id uuid primary key default gen_random_uuid(),policy_version_id uuid not null references public.policy_versions(id) on delete restrict,tenant_id uuid not null references public.tenants(id),organization_id uuid not null references public.organizations(id),facility_id uuid references public.facilities(id),storage_bucket text not null,storage_key text not null,checksum text not null,mime_type text not null,byte_size bigint not null check(byte_size>=0),document_language public.content_language not null,version_label text not null,preview_available boolean not null default false,extracted_text text,source_type text not null check(source_type in ('upload','word_import')),uploaded_at timestamptz not null default now(),uploaded_by uuid not null references public.user_profiles(id),unique(storage_bucket,storage_key));
create table public.policy_links(
 id uuid primary key default gen_random_uuid(),policy_definition_id uuid not null references public.policy_definitions(id) on delete restrict,tenant_id uuid not null references public.tenants(id),organization_id uuid not null references public.organizations(id),facility_id uuid references public.facilities(id),target_type text not null check(target_type in ('policy','form','capa','medication_error','drug_recall')),target_id uuid not null,created_at timestamptz not null default now(),created_by uuid not null references public.user_profiles(id),unique(policy_definition_id,target_type,target_id));
create table public.policy_acknowledgements(
 id uuid primary key default gen_random_uuid(),policy_version_id uuid not null references public.policy_versions(id) on delete restrict,tenant_id uuid not null references public.tenants(id),organization_id uuid not null references public.organizations(id),facility_id uuid references public.facilities(id),user_id uuid not null references public.user_profiles(id),department_id uuid references public.departments(id),read_at timestamptz,overdue_at timestamptz,reminder_status text not null default 'none' check(reminder_status in ('none','scheduled','sent','overdue')),created_at timestamptz not null default now(),unique(policy_version_id,user_id));
create table public.policy_events(
 id uuid primary key default gen_random_uuid(),policy_definition_id uuid not null references public.policy_definitions(id) on delete restrict,policy_version_id uuid references public.policy_versions(id) on delete restrict,tenant_id uuid not null references public.tenants(id),organization_id uuid not null references public.organizations(id),facility_id uuid references public.facilities(id),actor_id uuid not null references public.user_profiles(id),action text not null,metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());

create or replace function public.can_policy(p_permission text,p_tenant uuid,p_organization uuid,p_facility uuid) returns boolean language sql stable security definer set search_path=public as $$ select auth.uid() is not null and public.scope_allowed(p_tenant,p_organization,p_facility) and (public.has_platform_permission(p_permission,p_tenant,p_organization,p_facility) or public.has_platform_permission('platform.full_access',p_tenant,p_organization,p_facility)); $$;
create or replace function public.enforce_policy_scope() returns trigger language plpgsql security definer set search_path=public as $$ begin
 if tg_table_name='policy_versions' and not exists(select 1 from public.policy_definitions d where d.id=new.policy_definition_id and d.tenant_id=new.tenant_id and d.organization_id=new.organization_id and d.facility_id is not distinct from new.facility_id) then raise exception 'Policy version scope mismatch' using errcode='23503'; end if;
 if tg_table_name='policy_documents' and not exists(select 1 from public.policy_versions v where v.id=new.policy_version_id and v.tenant_id=new.tenant_id and v.organization_id=new.organization_id and v.facility_id is not distinct from new.facility_id) then raise exception 'Policy document scope mismatch' using errcode='23503'; end if;
 if tg_table_name='policy_links' and not exists(select 1 from public.policy_definitions d where d.id=new.policy_definition_id and d.tenant_id=new.tenant_id and d.organization_id=new.organization_id and d.facility_id is not distinct from new.facility_id) then raise exception 'Policy link scope mismatch' using errcode='23503'; end if;
 if tg_table_name='policy_acknowledgements' and not exists(select 1 from public.policy_versions v where v.id=new.policy_version_id and v.status='published' and v.tenant_id=new.tenant_id and v.organization_id=new.organization_id and v.facility_id is not distinct from new.facility_id) then raise exception 'Policy acknowledgement scope or publication mismatch' using errcode='23503'; end if; return new; end $$;
create or replace function public.prevent_published_policy_mutation() returns trigger language plpgsql security definer set search_path=public as $$ begin if old.status='published' then raise exception 'Published policy versions are immutable'; end if; return new; end $$;
create or replace function public.enforce_published_policy_current_version() returns trigger language plpgsql security definer set search_path=public as $$ begin if new.status='published' and not exists(select 1 from public.policy_versions v where v.id=new.current_version_id and v.policy_definition_id=new.id and v.status='published' and v.tenant_id=new.tenant_id and v.organization_id=new.organization_id and v.facility_id is not distinct from new.facility_id) then raise exception 'Published policy must reference its own published current version'; end if; return new; end $$;
create trigger policy_versions_scope before insert or update on public.policy_versions for each row execute function public.enforce_policy_scope(); create trigger policy_documents_scope before insert or update on public.policy_documents for each row execute function public.enforce_policy_scope(); create trigger policy_links_scope before insert or update on public.policy_links for each row execute function public.enforce_policy_scope(); create trigger policy_acknowledgements_scope before insert or update on public.policy_acknowledgements for each row execute function public.enforce_policy_scope(); create trigger policy_versions_immutable before update or delete on public.policy_versions for each row execute function public.prevent_published_policy_mutation(); create trigger policy_definitions_published_current before insert or update of status,current_version_id,tenant_id,organization_id,facility_id on public.policy_definitions for each row execute function public.enforce_published_policy_current_version();

create or replace function public.create_policy_draft_version(p_policy_id uuid,p_change_summary text) returns uuid language plpgsql security definer set search_path=public as $$ declare d public.policy_definitions%rowtype; v public.policy_versions%rowtype; new_id uuid; begin select * into d from public.policy_definitions where id=p_policy_id for update; if not found or not public.can_policy('policies.edit',d.tenant_id,d.organization_id,d.facility_id) then raise exception 'Policy draft version denied'; end if; if coalesce(trim(p_change_summary),'')='' then raise exception 'Policy change summary is required'; end if; select * into v from public.policy_versions where id=d.current_version_id and status='published' for update; if not found then raise exception 'Published policy version not found'; end if; insert into public.policy_versions(policy_definition_id,tenant_id,organization_id,facility_id,version_major,version_minor,status,content_language,title_ar,title_en,description_ar,description_en,keywords,tags,change_summary,effective_date,review_date,expiry_date,created_by,updated_by) values(d.id,d.tenant_id,d.organization_id,d.facility_id,v.version_major,v.version_minor+1,'draft',v.content_language,v.title_ar,v.title_en,v.description_ar,v.description_en,v.keywords,v.tags,trim(p_change_summary),v.effective_date,v.review_date,v.expiry_date,auth.uid(),auth.uid()) returning id into new_id; insert into public.policy_events(policy_definition_id,policy_version_id,tenant_id,organization_id,facility_id,actor_id,action,metadata) values(d.id,new_id,d.tenant_id,d.organization_id,d.facility_id,auth.uid(),'policy.version_created',jsonb_build_object('based_on',v.id)); return new_id; end $$;
create or replace function public.publish_policy_version(p_policy_id uuid,p_version_id uuid) returns void language plpgsql security definer set search_path=public as $$ declare d public.policy_definitions%rowtype; v public.policy_versions%rowtype; begin select * into d from public.policy_definitions where id=p_policy_id for update; if not found or not public.can_policy('policies.publish',d.tenant_id,d.organization_id,d.facility_id) then raise exception 'Policy publication denied'; end if; select * into v from public.policy_versions where id=p_version_id and policy_definition_id=d.id for update; if not found or v.status<>'approved' then raise exception 'Approved policy version required'; end if; update public.policy_versions set status='published',published_at=now(),published_by=auth.uid(),updated_at=now(),updated_by=auth.uid() where id=v.id; update public.policy_definitions set status='published',current_version_id=v.id,title_ar=v.title_ar,title_en=v.title_en,updated_at=now(),updated_by=auth.uid() where id=d.id; insert into public.policy_events(policy_definition_id,policy_version_id,tenant_id,organization_id,facility_id,actor_id,action) values(d.id,v.id,d.tenant_id,d.organization_id,d.facility_id,auth.uid(),'policy.published'); end $$;
create or replace function public.acknowledge_policy_version(p_policy_version_id uuid) returns void language plpgsql security definer set search_path=public as $$ declare v public.policy_versions%rowtype; begin select * into v from public.policy_versions where id=p_policy_version_id for update; if not found or v.status<>'published' or not public.can_policy('policies.acknowledge',v.tenant_id,v.organization_id,v.facility_id) then raise exception 'Policy acknowledgement denied'; end if; insert into public.policy_acknowledgements(policy_version_id,tenant_id,organization_id,facility_id,user_id,read_at) values(v.id,v.tenant_id,v.organization_id,v.facility_id,auth.uid(),now()) on conflict(policy_version_id,user_id) do update set read_at=excluded.read_at; insert into public.policy_events(policy_definition_id,policy_version_id,tenant_id,organization_id,facility_id,actor_id,action) values(v.policy_definition_id,v.id,v.tenant_id,v.organization_id,v.facility_id,auth.uid(),'policy.acknowledged'); end $$;

alter table public.policy_definitions enable row level security; alter table public.policy_versions enable row level security; alter table public.policy_documents enable row level security; alter table public.policy_links enable row level security; alter table public.policy_acknowledgements enable row level security; alter table public.policy_events enable row level security;
create policy policy_definitions_read on public.policy_definitions for select using(public.can_policy('policies.view',tenant_id,organization_id,facility_id)); create policy policy_definitions_write on public.policy_definitions for all using(public.can_policy('policies.create',tenant_id,organization_id,facility_id) or public.can_policy('policies.edit',tenant_id,organization_id,facility_id)) with check(public.can_policy('policies.create',tenant_id,organization_id,facility_id) or public.can_policy('policies.edit',tenant_id,organization_id,facility_id));
create policy policy_versions_read on public.policy_versions for select using((status='published' and public.can_policy('policies.view',tenant_id,organization_id,facility_id)) or public.can_policy('policies.edit',tenant_id,organization_id,facility_id) or public.can_policy('policies.review',tenant_id,organization_id,facility_id)); create policy policy_versions_draft_write on public.policy_versions for all using(status<>'published' and public.can_policy('policies.edit',tenant_id,organization_id,facility_id)) with check(status<>'published' and public.can_policy('policies.edit',tenant_id,organization_id,facility_id));
create policy policy_documents_read on public.policy_documents for select using(public.can_policy('policies.view',tenant_id,organization_id,facility_id)); create policy policy_documents_write on public.policy_documents for insert with check(public.can_policy('policies.edit',tenant_id,organization_id,facility_id)); create policy policy_links_read on public.policy_links for select using(public.can_policy('policies.view',tenant_id,organization_id,facility_id)); create policy policy_links_write on public.policy_links for all using(public.can_policy('policies.edit',tenant_id,organization_id,facility_id)) with check(public.can_policy('policies.edit',tenant_id,organization_id,facility_id)); create policy policy_acknowledgements_read on public.policy_acknowledgements for select using(user_id=auth.uid() or public.can_policy('policies.view',tenant_id,organization_id,facility_id)); create policy policy_events_read on public.policy_events for select using(public.can_policy('policies.view',tenant_id,organization_id,facility_id));
revoke all on function public.can_policy(text,uuid,uuid,uuid),public.create_policy_draft_version(uuid,text),public.publish_policy_version(uuid,uuid),public.acknowledge_policy_version(uuid) from public,anon; grant execute on function public.can_policy(text,uuid,uuid,uuid),public.create_policy_draft_version(uuid,text),public.publish_policy_version(uuid,uuid),public.acknowledge_policy_version(uuid) to authenticated; revoke all on function public.enforce_policy_scope(),public.prevent_published_policy_mutation(),public.enforce_published_policy_current_version() from public,anon,authenticated;
