-- Additive hardening for Policies & Procedures. This migration intentionally replaces broad client writes with controlled functions.
insert into public.permissions(key,name_ar,name_en) values
 ('policies.view_acknowledgements','عرض إقرارات القراءة','View policy acknowledgements'),
 ('policies.manage_acknowledgements','إدارة إقرارات القراءة','Manage policy acknowledgements') on conflict(key) do nothing;
insert into public.role_permissions(role_id,permission_id) select r.id,p.id from public.roles r join public.permissions p on p.key in ('policies.view_acknowledgements','policies.manage_acknowledgements') where r.key='platform_owner' on conflict do nothing;

create unique index policy_versions_one_published_per_definition on public.policy_versions(policy_definition_id) where status='published';
alter table public.policy_documents add constraint policy_documents_allowed_mime check(mime_type in ('application/pdf','application/vnd.openxmlformats-officedocument.wordprocessingml.document','application/msword','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','application/vnd.ms-excel','application/vnd.openxmlformats-officedocument.presentationml.presentation','image/jpeg','image/png','image/webp'));
alter table public.policy_documents add constraint policy_documents_size_limit check(byte_size between 1 and 52428800);
alter table public.policy_documents add constraint policy_documents_checksum_format check(checksum ~ '^[A-Fa-f0-9]{64}$');
alter table public.policy_documents add constraint policy_documents_extracted_text_limit check(extracted_text is null or octet_length(extracted_text)<=5242880);
alter table public.policy_versions add constraint policy_versions_date_order check((review_date is null or effective_date is null or review_date>effective_date) and (expiry_date is null or effective_date is null or expiry_date>effective_date));
alter table public.policy_versions add constraint policy_versions_keyword_tag_limits check(cardinality(keywords)<=50 and cardinality(tags)<=50);

create or replace function public.policy_member_in_scope(p_user uuid,p_t uuid,p_o uuid,p_f uuid) returns boolean language sql stable security definer set search_path=public as $$ select public.report_member_in_scope(p_user,p_t,p_o,p_f); $$;
create or replace function public.enforce_policy_reference_integrity() returns trigger language plpgsql security definer set search_path=public as $$ begin
 if tg_table_name='policy_definitions' then
   if coalesce(trim(new.policy_id),'')='' or coalesce(trim(new.policy_number),'')='' then raise exception 'Policy ID and policy number are required'; end if;
   if not public.policy_member_in_scope(new.owner_id,new.tenant_id,new.organization_id,new.facility_id) or not public.policy_member_in_scope(new.created_by,new.tenant_id,new.organization_id,new.facility_id) or not public.policy_member_in_scope(new.updated_by,new.tenant_id,new.organization_id,new.facility_id) or (new.approver_id is not null and not public.policy_member_in_scope(new.approver_id,new.tenant_id,new.organization_id,new.facility_id)) or (new.archived_by is not null and not public.policy_member_in_scope(new.archived_by,new.tenant_id,new.organization_id,new.facility_id)) then raise exception 'Policy user reference is outside scope' using errcode='23503'; end if;
   if new.department_id is not null and not exists(select 1 from public.departments d where d.id=new.department_id and d.tenant_id=new.tenant_id and d.organization_id=new.organization_id and d.facility_id is not distinct from new.facility_id) then raise exception 'Policy department is outside scope' using errcode='23503'; end if;
 end if;
 if tg_table_name='policy_versions' then
   if not public.policy_member_in_scope(new.created_by,new.tenant_id,new.organization_id,new.facility_id) or not public.policy_member_in_scope(new.updated_by,new.tenant_id,new.organization_id,new.facility_id) or (new.approved_by is not null and not public.policy_member_in_scope(new.approved_by,new.tenant_id,new.organization_id,new.facility_id)) or (new.published_by is not null and not public.policy_member_in_scope(new.published_by,new.tenant_id,new.organization_id,new.facility_id)) then raise exception 'Policy version user reference is outside scope' using errcode='23503'; end if;
   if new.workflow_instance_id is not null and not exists(select 1 from public.workflow_instances w where w.id=new.workflow_instance_id and w.tenant_id=new.tenant_id and w.organization_id=new.organization_id and w.facility_id is not distinct from new.facility_id) then raise exception 'Policy workflow instance is outside scope' using errcode='23503'; end if;
 end if;
 if tg_table_name='policy_documents' and not public.policy_member_in_scope(new.uploaded_by,new.tenant_id,new.organization_id,new.facility_id) then raise exception 'Policy document uploader is outside scope' using errcode='23503'; end if;
 if tg_table_name='policy_acknowledgements' and not public.policy_member_in_scope(new.user_id,new.tenant_id,new.organization_id,new.facility_id) then raise exception 'Policy acknowledgement user is outside scope' using errcode='23503'; end if;
 return new; end $$;
create trigger policy_definitions_reference_integrity before insert or update on public.policy_definitions for each row execute function public.enforce_policy_reference_integrity();
create trigger policy_versions_reference_integrity before insert or update on public.policy_versions for each row execute function public.enforce_policy_reference_integrity();
create trigger policy_documents_reference_integrity before insert or update on public.policy_documents for each row execute function public.enforce_policy_reference_integrity();
create trigger policy_acknowledgements_reference_integrity before insert or update on public.policy_acknowledgements for each row execute function public.enforce_policy_reference_integrity();

create or replace function public.prevent_non_draft_policy_document_mutation() returns trigger language plpgsql security definer set search_path=public as $$ declare s public.policy_status; target_version uuid; begin target_version:=case when tg_op='DELETE' then old.policy_version_id else new.policy_version_id end; select status into s from public.policy_versions where id=target_version; if s<>'draft' then raise exception 'Documents may only change on draft policy versions'; end if; if tg_op='DELETE' then return old; end if; return new; end $$;
create trigger policy_documents_draft_only before insert or update or delete on public.policy_documents for each row execute function public.prevent_non_draft_policy_document_mutation();
create or replace function public.prevent_published_policy_mutation() returns trigger language plpgsql security definer set search_path=public as $$ begin if old.status='published' and not (new.status='superseded' and current_setting('app.policy_lifecycle',true)='on') then raise exception 'Published policy versions are immutable'; end if; return new; end $$;

create or replace function public.policy_target_in_scope(p_type text,p_id uuid,p_t uuid,p_o uuid,p_f uuid) returns boolean language plpgsql security definer set search_path=public as $$ begin
 if p_type='policy' then return exists(select 1 from public.policy_definitions x where x.id=p_id and x.tenant_id=p_t and x.organization_id=p_o and x.facility_id is not distinct from p_f); end if;
 if p_type='form' then return exists(select 1 from public.form_definitions x where x.id=p_id and x.tenant_id=p_t and x.organization_id=p_o and x.facility_id is not distinct from p_f); end if;
 if p_type='medication_error' then return exists(select 1 from public.medication_error_reports x where x.id=p_id and x.tenant_id=p_t and x.organization_id=p_o and x.facility_id is not distinct from p_f); end if;
 raise exception 'Policy link adapter is not implemented for target type %',p_type; end $$;
create or replace function public.enforce_policy_link_target() returns trigger language plpgsql security definer set search_path=public as $$ begin if not public.policy_target_in_scope(new.target_type,new.target_id,new.tenant_id,new.organization_id,new.facility_id) then raise exception 'Policy link target is invalid or outside scope' using errcode='23503'; end if; return new; end $$;
create trigger policy_links_target_integrity before insert or update on public.policy_links for each row execute function public.enforce_policy_link_target();

create or replace function public.append_policy_audit_event(p_t uuid,p_o uuid,p_f uuid,p_action text,p_entity_type text,p_entity_id uuid,p_metadata jsonb default '{}'::jsonb) returns uuid language plpgsql security definer set search_path=public as $$ declare event_id uuid; begin if current_setting('app.policy_lifecycle',true)<>'on' or auth.uid() is null or p_metadata ?| array['password','token','secret','access_token'] then raise exception 'Policy audit event is not authorized'; end if; insert into public.audit_events(tenant_id,organization_id,facility_id,actor_id,action,entity_type,entity_id,metadata) values(p_t,p_o,p_f,auth.uid(),p_action,p_entity_type,p_entity_id,p_metadata) returning id into event_id; return event_id; end $$;
create or replace function public.record_policy_event(p_policy uuid,p_version uuid,p_t uuid,p_o uuid,p_f uuid,p_action text,p_metadata jsonb default '{}'::jsonb) returns void language plpgsql security definer set search_path=public as $$ begin if current_setting('app.policy_lifecycle',true)<>'on' or auth.uid() is null then raise exception 'Policy event is not authorized'; end if; insert into public.policy_events(policy_definition_id,policy_version_id,tenant_id,organization_id,facility_id,actor_id,action,metadata) values(p_policy,p_version,p_t,p_o,p_f,auth.uid(),p_action,p_metadata); perform public.append_policy_audit_event(p_t,p_o,p_f,p_action,'policy_definition',p_policy,p_metadata); end $$;

create or replace function public.create_policy_definition(p_t uuid,p_o uuid,p_f uuid,p_policy_id text,p_policy_number text,p_title_ar text,p_title_en text,p_owner uuid,p_approver uuid default null) returns uuid language plpgsql security definer set search_path=public as $$ declare id uuid; v uuid; begin if not public.can_policy('policies.create',p_t,p_o,p_f) then raise exception 'Policy creation denied'; end if; perform set_config('app.policy_lifecycle','on',true); insert into public.policy_definitions(tenant_id,organization_id,facility_id,policy_id,policy_number,owner_id,approver_id,status,title_ar,title_en,created_by,updated_by) values(p_t,p_o,p_f,trim(p_policy_id),trim(p_policy_number),p_owner,p_approver,'draft',nullif(trim(p_title_ar),''),nullif(trim(p_title_en),''),auth.uid(),auth.uid()) returning id into id; insert into public.policy_versions(policy_definition_id,tenant_id,organization_id,facility_id,version_major,version_minor,status,content_language,title_ar,title_en,change_summary,created_by,updated_by) values(id,p_t,p_o,p_f,1,0,'draft','bilingual',nullif(trim(p_title_ar),''),nullif(trim(p_title_en),''),'Initial draft',auth.uid(),auth.uid()) returning id into v; perform public.record_policy_event(id,v,p_t,p_o,p_f,'policy.created'); return id; end $$;
create or replace function public.update_policy_draft_metadata(p_version uuid,p_title_ar text,p_title_en text,p_description_ar text,p_description_en text,p_keywords text[],p_tags text[],p_effective date,p_review date,p_expiry date) returns void language plpgsql security definer set search_path=public as $$ declare v public.policy_versions%rowtype; begin select * into v from public.policy_versions where id=p_version for update; if not found or v.status<>'draft' or not public.can_policy('policies.edit',v.tenant_id,v.organization_id,v.facility_id) then raise exception 'Policy draft update denied'; end if; update public.policy_versions set title_ar=nullif(trim(p_title_ar),''),title_en=nullif(trim(p_title_en),''),description_ar=nullif(trim(p_description_ar),''),description_en=nullif(trim(p_description_en),''),keywords=coalesce(p_keywords,'{}'),tags=coalesce(p_tags,'{}'),effective_date=p_effective,review_date=p_review,expiry_date=p_expiry,updated_at=now(),updated_by=auth.uid() where id=v.id; perform set_config('app.policy_lifecycle','on',true); perform public.record_policy_event(v.policy_definition_id,v.id,v.tenant_id,v.organization_id,v.facility_id,'policy.metadata_updated'); end $$;
create or replace function public.submit_policy_for_review(p_version uuid) returns void language plpgsql security definer set search_path=public as $$ declare v public.policy_versions%rowtype; begin select * into v from public.policy_versions where id=p_version for update; if not found or v.status<>'draft' or not public.can_policy('policies.review',v.tenant_id,v.organization_id,v.facility_id) then raise exception 'Policy review submission denied'; end if; perform set_config('app.policy_lifecycle','on',true); update public.policy_versions set status='under_review',updated_at=now(),updated_by=auth.uid() where id=v.id; perform public.record_policy_event(v.policy_definition_id,v.id,v.tenant_id,v.organization_id,v.facility_id,'policy.submitted'); end $$;
create or replace function public.approve_policy_version(p_version uuid) returns void language plpgsql security definer set search_path=public as $$ declare v public.policy_versions%rowtype; begin select * into v from public.policy_versions where id=p_version for update; if not found or v.status<>'under_review' or not public.can_policy('policies.approve',v.tenant_id,v.organization_id,v.facility_id) then raise exception 'Policy approval denied'; end if; perform set_config('app.policy_lifecycle','on',true); update public.policy_versions set status='approved',approved_at=now(),approved_by=auth.uid(),updated_at=now(),updated_by=auth.uid() where id=v.id; perform public.record_policy_event(v.policy_definition_id,v.id,v.tenant_id,v.organization_id,v.facility_id,'policy.approved'); end $$;
create or replace function public.reject_policy_version(p_version uuid,p_reason text) returns void language plpgsql security definer set search_path=public as $$ declare v public.policy_versions%rowtype; begin select * into v from public.policy_versions where id=p_version for update; if not found or v.status<>'under_review' or coalesce(trim(p_reason),'')='' or not public.can_policy('policies.review',v.tenant_id,v.organization_id,v.facility_id) then raise exception 'Policy rejection denied'; end if; perform set_config('app.policy_lifecycle','on',true); update public.policy_versions set status='draft',updated_at=now(),updated_by=auth.uid() where id=v.id; perform public.record_policy_event(v.policy_definition_id,v.id,v.tenant_id,v.organization_id,v.facility_id,'policy.rejected',jsonb_build_object('reason',trim(p_reason))); end $$;
create or replace function public.publish_policy_version(p_policy_id uuid,p_version_id uuid) returns void language plpgsql security definer set search_path=public as $$ declare d public.policy_definitions%rowtype; v public.policy_versions%rowtype; previous_id uuid; begin select * into d from public.policy_definitions where id=p_policy_id for update; if not found or not public.can_policy('policies.publish',d.tenant_id,d.organization_id,d.facility_id) then raise exception 'Policy publication denied'; end if; select * into v from public.policy_versions where id=p_version_id and policy_definition_id=d.id and tenant_id=d.tenant_id and organization_id=d.organization_id and facility_id is not distinct from d.facility_id for update; if not found or v.status<>'approved' then raise exception 'Approved policy version required'; end if; perform set_config('app.policy_lifecycle','on',true); select id into previous_id from public.policy_versions where policy_definition_id=d.id and status='published' for update; if previous_id is not null then update public.policy_versions set status='superseded',updated_at=now(),updated_by=auth.uid() where id=previous_id; perform public.record_policy_event(d.id,previous_id,d.tenant_id,d.organization_id,d.facility_id,'policy.superseded',jsonb_build_object('replacement_version_id',v.id)); end if; update public.policy_versions set status='published',published_at=now(),published_by=auth.uid(),updated_at=now(),updated_by=auth.uid() where id=v.id; update public.policy_definitions set status='published',current_version_id=v.id,title_ar=v.title_ar,title_en=v.title_en,updated_at=now(),updated_by=auth.uid() where id=d.id; perform public.record_policy_event(d.id,v.id,d.tenant_id,d.organization_id,d.facility_id,'policy.published'); end $$;
create or replace function public.archive_policy_definition(p_policy uuid) returns void language plpgsql security definer set search_path=public as $$ declare d public.policy_definitions%rowtype; begin select * into d from public.policy_definitions where id=p_policy for update; if not found or not public.can_policy('policies.archive',d.tenant_id,d.organization_id,d.facility_id) then raise exception 'Policy archive denied'; end if; perform set_config('app.policy_lifecycle','on',true); update public.policy_definitions set status='archived',archived_at=now(),archived_by=auth.uid(),updated_at=now(),updated_by=auth.uid() where id=d.id; perform public.record_policy_event(d.id,d.current_version_id,d.tenant_id,d.organization_id,d.facility_id,'policy.archived'); end $$;
create or replace function public.restore_policy_definition(p_policy uuid) returns void language plpgsql security definer set search_path=public as $$ declare d public.policy_definitions%rowtype; begin select * into d from public.policy_definitions where id=p_policy for update; if not found or d.status<>'archived' or not public.can_policy('policies.restore',d.tenant_id,d.organization_id,d.facility_id) then raise exception 'Policy restore denied'; end if; perform set_config('app.policy_lifecycle','on',true); update public.policy_definitions set status=case when current_version_id is null then 'draft' else 'published' end,archived_at=null,archived_by=null,updated_at=now(),updated_by=auth.uid() where id=d.id; perform public.record_policy_event(d.id,d.current_version_id,d.tenant_id,d.organization_id,d.facility_id,'policy.restored'); end $$;
create or replace function public.create_policy_draft_version(p_policy_id uuid,p_change_summary text) returns uuid language plpgsql security definer set search_path=public as $$ declare d public.policy_definitions%rowtype; v public.policy_versions%rowtype; new_id uuid; begin select * into d from public.policy_definitions where id=p_policy_id for update; if not found or not public.can_policy('policies.edit',d.tenant_id,d.organization_id,d.facility_id) or coalesce(trim(p_change_summary),'')='' then raise exception 'Policy draft version denied'; end if; select * into v from public.policy_versions where id=d.current_version_id and status='published' for update; if not found then raise exception 'Published policy version not found'; end if; perform set_config('app.policy_lifecycle','on',true); insert into public.policy_versions(policy_definition_id,tenant_id,organization_id,facility_id,version_major,version_minor,status,content_language,title_ar,title_en,description_ar,description_en,keywords,tags,change_summary,effective_date,review_date,expiry_date,created_by,updated_by) values(d.id,d.tenant_id,d.organization_id,d.facility_id,v.version_major,v.version_minor+1,'draft',v.content_language,v.title_ar,v.title_en,v.description_ar,v.description_en,v.keywords,v.tags,trim(p_change_summary),v.effective_date,v.review_date,v.expiry_date,auth.uid(),auth.uid()) returning id into new_id; perform public.record_policy_event(d.id,new_id,d.tenant_id,d.organization_id,d.facility_id,'policy.version_created',jsonb_build_object('based_on',v.id)); return new_id; end $$;
create or replace function public.link_policy_record(p_policy uuid,p_target_type text,p_target_id uuid) returns uuid language plpgsql security definer set search_path=public as $$ declare d public.policy_definitions%rowtype; id uuid; begin select * into d from public.policy_definitions where id=p_policy for update; if not found or not public.can_policy('policies.edit',d.tenant_id,d.organization_id,d.facility_id) then raise exception 'Policy link denied'; end if; if not public.policy_target_in_scope(p_target_type,p_target_id,d.tenant_id,d.organization_id,d.facility_id) then raise exception 'Policy link target denied'; end if; perform set_config('app.policy_lifecycle','on',true); insert into public.policy_links(policy_definition_id,tenant_id,organization_id,facility_id,target_type,target_id,created_by) values(d.id,d.tenant_id,d.organization_id,d.facility_id,p_target_type,p_target_id,auth.uid()) returning id into id; perform public.record_policy_event(d.id,null,d.tenant_id,d.organization_id,d.facility_id,'policy.linked',jsonb_build_object('target_type',p_target_type,'target_id',p_target_id)); return id; end $$;
create or replace function public.finalize_policy_document(p_version uuid,p_bucket text,p_key text,p_checksum text,p_mime text,p_size bigint,p_language public.content_language,p_label text,p_preview boolean,p_source text,p_extracted text default null) returns uuid language plpgsql security definer set search_path=public as $$ declare v public.policy_versions%rowtype; id uuid; begin select * into v from public.policy_versions where id=p_version for update; if not found or v.status<>'draft' or not public.can_policy('policies.edit',v.tenant_id,v.organization_id,v.facility_id) then raise exception 'Policy document finalization denied'; end if; if p_key !~ ('^tenant/'||v.tenant_id::text||'/organization/'||v.organization_id::text||'/facility/'||coalesce(v.facility_id::text,'global')||'/policies/'||v.policy_definition_id::text||'/versions/'||v.id::text||'/[0-9a-f-]{36}-[A-Za-z0-9._-]+$') then raise exception 'Policy document storage path is unsafe'; end if; if p_mime like '%macroEnabled%' or p_key ~* '\.(docm|xlsm|pptm)$' then raise exception 'Macro-enabled Office files are not allowed'; end if; perform set_config('app.policy_lifecycle','on',true); insert into public.policy_documents(policy_version_id,tenant_id,organization_id,facility_id,storage_bucket,storage_key,checksum,mime_type,byte_size,document_language,version_label,preview_available,extracted_text,source_type,uploaded_by) values(v.id,v.tenant_id,v.organization_id,v.facility_id,p_bucket,p_key,p_checksum,p_mime,p_size,p_language,trim(p_label),p_preview,p_extracted,p_source,auth.uid()) returning id into id; perform public.record_policy_event(v.policy_definition_id,v.id,v.tenant_id,v.organization_id,v.facility_id,'policy.document_uploaded',jsonb_build_object('document_id',id)); return id; end $$;
create or replace function public.can_view_policy_document(p_version uuid) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.policy_versions v where v.id=p_version and ((v.status='published' and public.can_policy('policies.view',v.tenant_id,v.organization_id,v.facility_id)) or (v.status in ('draft','under_review','approved') and (public.can_policy('policies.edit',v.tenant_id,v.organization_id,v.facility_id) or public.can_policy('policies.review',v.tenant_id,v.organization_id,v.facility_id) or public.can_policy('policies.approve',v.tenant_id,v.organization_id,v.facility_id))) or (v.status in ('superseded','archived') and public.can_policy('policies.view_acknowledgements',v.tenant_id,v.organization_id,v.facility_id)))); $$;
create or replace function public.record_policy_document_download(p_document uuid) returns void language plpgsql security definer set search_path=public as $$ declare d public.policy_documents%rowtype; begin select * into d from public.policy_documents where id=p_document; if not found or not public.can_view_policy_document(d.policy_version_id) then raise exception 'Policy document download denied'; end if; perform set_config('app.policy_lifecycle','on',true); perform public.record_policy_event((select policy_definition_id from public.policy_versions where id=d.policy_version_id),d.policy_version_id,d.tenant_id,d.organization_id,d.facility_id,'policy.document_downloaded',jsonb_build_object('document_id',d.id)); end $$;

-- Remove broad client writes. All lifecycle and metadata changes now go through the functions above.
drop policy if exists policy_definitions_write on public.policy_definitions; drop policy if exists policy_versions_draft_write on public.policy_versions; drop policy if exists policy_documents_write on public.policy_documents; drop policy if exists policy_links_write on public.policy_links; drop policy if exists policy_acknowledgements_read on public.policy_acknowledgements;
drop policy if exists policy_documents_read on public.policy_documents;
create policy policy_documents_read on public.policy_documents for select using(public.can_view_policy_document(policy_version_id));
create policy policy_acknowledgements_self on public.policy_acknowledgements for select using(user_id=auth.uid() and public.can_policy('policies.acknowledge',tenant_id,organization_id,facility_id));
create policy policy_acknowledgements_manager on public.policy_acknowledgements for select using(public.can_policy('policies.view_acknowledgements',tenant_id,organization_id,facility_id));

-- Private bucket: object paths are checked against the policy version scope, and no public bucket policy is created.
insert into storage.buckets(id,name,public) values('policy-documents','policy-documents',false) on conflict(id) do update set public=false;
create or replace function public.policy_storage_object_allowed(p_name text,p_write boolean) returns boolean language plpgsql security definer set search_path=public,storage as $$ declare v uuid; begin if auth.uid() is null or p_name !~ '^tenant/[0-9a-f-]{36}/organization/[0-9a-f-]{36}/facility/([0-9a-f-]{36}|global)/policies/[0-9a-f-]{36}/versions/[0-9a-f-]{36}/[0-9a-f-]{36}-[A-Za-z0-9._-]+$' then return false; end if; v:=split_part(p_name,'/',10)::uuid; return exists(select 1 from public.policy_versions x where x.id=v and x.tenant_id=split_part(p_name,'/',2)::uuid and x.organization_id=split_part(p_name,'/',4)::uuid and coalesce(x.facility_id::text,'global')=split_part(p_name,'/',6) and (case when p_write then x.status='draft' and public.can_policy('policies.edit',x.tenant_id,x.organization_id,x.facility_id) else public.can_view_policy_document(x.id) end)); end $$;
drop policy if exists policy_documents_storage_insert on storage.objects; drop policy if exists policy_documents_storage_select on storage.objects; drop policy if exists policy_documents_storage_update on storage.objects; drop policy if exists policy_documents_storage_delete on storage.objects;
create policy policy_documents_storage_insert on storage.objects for insert to authenticated with check(bucket_id='policy-documents' and public.policy_storage_object_allowed(name,true));
create policy policy_documents_storage_select on storage.objects for select to authenticated using(bucket_id='policy-documents' and public.policy_storage_object_allowed(name,false));

revoke all on function public.policy_member_in_scope(uuid,uuid,uuid,uuid),public.enforce_policy_reference_integrity(),public.prevent_non_draft_policy_document_mutation(),public.policy_target_in_scope(text,uuid,uuid,uuid,uuid),public.enforce_policy_link_target(),public.append_policy_audit_event(uuid,uuid,uuid,text,text,uuid,jsonb),public.record_policy_event(uuid,uuid,uuid,uuid,uuid,text,jsonb),public.policy_storage_object_allowed(text,boolean) from public,anon,authenticated;
revoke all on function public.create_policy_definition(uuid,uuid,uuid,text,text,text,text,uuid,uuid),public.update_policy_draft_metadata(uuid,text,text,text,text,text[],text[],date,date,date),public.submit_policy_for_review(uuid),public.approve_policy_version(uuid),public.reject_policy_version(uuid,text),public.publish_policy_version(uuid,uuid),public.archive_policy_definition(uuid),public.restore_policy_definition(uuid),public.create_policy_draft_version(uuid,text),public.link_policy_record(uuid,text,uuid),public.finalize_policy_document(uuid,text,text,text,text,bigint,public.content_language,text,boolean,text,text),public.record_policy_document_download(uuid),public.can_view_policy_document(uuid) from public,anon;
grant execute on function public.create_policy_definition(uuid,uuid,uuid,text,text,text,text,uuid,uuid),public.update_policy_draft_metadata(uuid,text,text,text,text,text[],text[],date,date,date),public.submit_policy_for_review(uuid),public.approve_policy_version(uuid),public.reject_policy_version(uuid,text),public.publish_policy_version(uuid,uuid),public.archive_policy_definition(uuid),public.restore_policy_definition(uuid),public.create_policy_draft_version(uuid,text),public.link_policy_record(uuid,text,uuid),public.finalize_policy_document(uuid,text,text,text,text,bigint,public.content_language,text,boolean,text,text),public.record_policy_document_download(uuid),public.can_view_policy_document(uuid) to authenticated;
