create type public.medication_error_status as enum ('draft','submitted','triage','under_investigation','awaiting_information','awaiting_approval','follow_up','verified','closed','reopened');
create type public.medication_error_incident_type as enum ('incident','near_miss','no_harm','harm','sentinel_event');
create type public.medication_error_stage as enum ('prescribing','transcribing','dispensing','preparation','administration','monitoring','storage','other');

insert into public.permissions(key,name_ar,name_en) values
('medication_errors.view','عرض أخطاء الدواء','View medication errors'),('medication_errors.create','إنشاء بلاغات أخطاء الدواء','Create medication error reports'),('medication_errors.edit_draft','تعديل مسودات أخطاء الدواء','Edit medication error drafts'),('medication_errors.submit','إرسال بلاغات أخطاء الدواء','Submit medication error reports'),('medication_errors.review','مراجعة أخطاء الدواء','Review medication errors'),('medication_errors.assign','تعيين أخطاء الدواء','Assign medication errors'),('medication_errors.approve','اعتماد أخطاء الدواء','Approve medication errors'),('medication_errors.close','إغلاق أخطاء الدواء','Close medication errors'),('medication_errors.reopen','إعادة فتح أخطاء الدواء','Reopen medication errors'),('medication_errors.export','تصدير أخطاء الدواء','Export medication errors'),('medication_errors.manage_configuration','إدارة إعدادات أخطاء الدواء','Manage medication error configuration') on conflict(key) do nothing;
insert into public.role_permissions(role_id,permission_id) select r.id,p.id from public.roles r cross join public.permissions p where r.key='platform_owner' and p.key like 'medication_errors.%' on conflict do nothing;

create table public.medication_error_reports (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.tenants(id), organization_id uuid not null references public.organizations(id), facility_id uuid references public.facilities(id), reference_number text not null, status public.medication_error_status not null default 'draft', revision integer not null default 1 check(revision>0), incident_type public.medication_error_incident_type not null, ncc_merp_category text check(ncc_merp_category in ('A','B','C','D','E','F','G','H','I')), severity text not null check(severity in ('low','moderate','high','critical')), outcome_classification text, medication_stage public.medication_error_stage not null, occurred_at timestamptz not null, reported_at timestamptz not null default now(), reported_by uuid not null references public.user_profiles(id), department_id uuid references public.departments(id), title text not null, description text not null, immediate_action text, contributing_factors jsonb not null default '[]'::jsonb, error_categories jsonb not null default '[]'::jsonb, risk_score integer not null default 0 check(risk_score between 0 and 25), witness_information text, reviewer_notes text, manager_notes text, quality_notes text, pharmacy_notes text, owner_id uuid references public.user_profiles(id), reviewer_id uuid references public.user_profiles(id), due_at timestamptz, investigation text, root_cause_analysis text, corrective_actions text, preventive_actions text, follow_up text, verification text, closure_notes text, submitted_at timestamptz, approved_at timestamptz, closed_at timestamptz, reopened_at timestamptz, created_at timestamptz not null default now(), created_by uuid references public.user_profiles(id), updated_at timestamptz not null default now(), updated_by uuid references public.user_profiles(id), archived_at timestamptz, archived_by uuid references public.user_profiles(id), unique(tenant_id,reference_number));
create table public.medication_error_revisions (id uuid primary key default gen_random_uuid(), report_id uuid not null references public.medication_error_reports(id) on delete restrict, tenant_id uuid not null references public.tenants(id), organization_id uuid not null references public.organizations(id), facility_id uuid references public.facilities(id), revision integer not null, reason text not null, snapshot jsonb not null, created_at timestamptz not null default now(), created_by uuid not null references public.user_profiles(id), unique(report_id,revision));
create table public.medication_error_comments (id uuid primary key default gen_random_uuid(), report_id uuid not null references public.medication_error_reports(id) on delete restrict, tenant_id uuid not null references public.tenants(id), organization_id uuid not null references public.organizations(id), facility_id uuid references public.facilities(id), body text not null, language text not null check(language in ('ar','en')), visibility text not null check(visibility in ('team','confidential')), created_at timestamptz not null default now(), created_by uuid not null references public.user_profiles(id));
create table public.medication_error_attachments (id uuid primary key default gen_random_uuid(), report_id uuid not null references public.medication_error_reports(id) on delete restrict, tenant_id uuid not null references public.tenants(id), organization_id uuid not null references public.organizations(id), facility_id uuid references public.facilities(id), kind text not null check(kind in ('photo','file','evidence')), file_name text not null, content_type text not null, storage_key text, created_at timestamptz not null default now(), created_by uuid not null references public.user_profiles(id));
create table public.medication_error_timeline (id uuid primary key default gen_random_uuid(), report_id uuid not null references public.medication_error_reports(id) on delete restrict, tenant_id uuid not null references public.tenants(id), organization_id uuid not null references public.organizations(id), facility_id uuid references public.facilities(id), action text not null, from_status public.medication_error_status, to_status public.medication_error_status, note text, created_at timestamptz not null default now(), created_by uuid references public.user_profiles(id));
create table public.medication_error_configurations (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.tenants(id), organization_id uuid not null references public.organizations(id), facility_id uuid references public.facilities(id), field_key text not null, configuration jsonb not null default '{}'::jsonb, active boolean not null default true, created_at timestamptz not null default now(), created_by uuid references public.user_profiles(id), updated_at timestamptz not null default now(), updated_by uuid references public.user_profiles(id), unique(tenant_id,organization_id,facility_id,field_key));
create table public.medication_error_capa_links (id uuid primary key default gen_random_uuid(), report_id uuid not null references public.medication_error_reports(id) on delete restrict, tenant_id uuid not null references public.tenants(id), organization_id uuid not null references public.organizations(id), facility_id uuid references public.facilities(id), external_capa_reference text, status text not null default 'requested', created_at timestamptz not null default now(), created_by uuid references public.user_profiles(id));

create or replace function public.can_medication_error(permission_key text,target_tenant uuid,target_organization uuid,target_facility uuid) returns boolean language sql stable security definer set search_path=public as $$ select auth.uid() is not null and public.scope_allowed(target_tenant,target_organization,target_facility) and (public.has_platform_permission(permission_key,target_tenant,target_organization,target_facility) or public.has_platform_permission('platform.full_access',target_tenant,target_organization,target_facility)); $$;
create or replace function public.enforce_medication_error_scope() returns trigger language plpgsql security definer set search_path=public as $$ begin if new.facility_id is not null and not exists(select 1 from public.facilities f where f.id=new.facility_id and f.tenant_id=new.tenant_id and f.organization_id=new.organization_id) then raise exception 'Medication error facility scope mismatch' using errcode='23503'; end if; return new; end $$;
create or replace function public.prevent_submitted_medication_error_mutation() returns trigger language plpgsql security definer set search_path=public as $$ begin if old.status<>'draft' and (new.title,new.description,new.incident_type,new.medication_stage,new.occurred_at) is distinct from (old.title,old.description,old.incident_type,old.medication_stage,old.occurred_at) then raise exception 'Submitted medication error content requires a tracked revision' using errcode='23514'; end if; return new; end $$;
create trigger medication_errors_scope before insert or update on public.medication_error_reports for each row execute function public.enforce_medication_error_scope();
create trigger medication_errors_immutable_submitted before update on public.medication_error_reports for each row execute function public.prevent_submitted_medication_error_mutation();
alter table public.medication_error_reports enable row level security; alter table public.medication_error_revisions enable row level security; alter table public.medication_error_comments enable row level security; alter table public.medication_error_attachments enable row level security; alter table public.medication_error_timeline enable row level security; alter table public.medication_error_configurations enable row level security; alter table public.medication_error_capa_links enable row level security;
create policy medication_reports_read on public.medication_error_reports for select using(public.can_medication_error('medication_errors.view',tenant_id,organization_id,facility_id) or (status='draft' and reported_by=auth.uid()));
create policy medication_reports_insert on public.medication_error_reports for insert with check(public.can_medication_error('medication_errors.create',tenant_id,organization_id,facility_id) and reported_by=auth.uid());
create policy medication_reports_draft_update on public.medication_error_reports for update using((status='draft' and reported_by=auth.uid() and public.can_medication_error('medication_errors.edit_draft',tenant_id,organization_id,facility_id)) or public.can_medication_error('medication_errors.review',tenant_id,organization_id,facility_id)) with check(public.scope_allowed(tenant_id,organization_id,facility_id));
create policy medication_children_read on public.medication_error_revisions for select using(public.can_medication_error('medication_errors.view',tenant_id,organization_id,facility_id));
create policy medication_comments_read on public.medication_error_comments for select using(public.can_medication_error('medication_errors.view',tenant_id,organization_id,facility_id) and (visibility='team' or public.can_medication_error('medication_errors.review',tenant_id,organization_id,facility_id)));
create policy medication_comments_write on public.medication_error_comments for insert with check(public.can_medication_error('medication_errors.review',tenant_id,organization_id,facility_id) and created_by=auth.uid());
create policy medication_attachments_read on public.medication_error_attachments for select using(public.can_medication_error('medication_errors.view',tenant_id,organization_id,facility_id));
create policy medication_timeline_read on public.medication_error_timeline for select using(public.can_medication_error('medication_errors.view',tenant_id,organization_id,facility_id));
create policy medication_config_read on public.medication_error_configurations for select using(public.can_medication_error('medication_errors.manage_configuration',tenant_id,organization_id,facility_id));
revoke all on function public.can_medication_error(text,uuid,uuid,uuid) from public,anon; grant execute on function public.can_medication_error(text,uuid,uuid,uuid) to authenticated;
revoke all on function public.enforce_medication_error_scope() from public,anon,authenticated; revoke all on function public.prevent_submitted_medication_error_mutation() from public,anon,authenticated;
