-- Secure development foundation only. Apply through `supabase db reset` or
-- `supabase migration up`; never paste this schema into a production console.
create extension if not exists pgcrypto;

create type public.scope_level as enum ('global', 'organization', 'facility');
create type public.form_status as enum ('draft', 'published', 'archived');
create type public.content_language as enum ('arabic', 'english', 'bilingual');
create type public.deletion_request_status as enum ('requested', 'awaiting_second_approval', 'approved', 'rejected', 'cancelled');

create table public.tenants (
  id uuid primary key default gen_random_uuid(), key text not null unique check (key ~ '^[a-z0-9_-]+$'), name_ar text, name_en text not null,
  created_at timestamptz not null default now(), created_by uuid references auth.users(id), updated_at timestamptz not null default now(), updated_by uuid references auth.users(id),
  archived_at timestamptz, archived_by uuid references auth.users(id), deleted_at timestamptz, deleted_by uuid references auth.users(id), deletion_reason text
);
create table public.organizations (
  id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.tenants(id), name_ar text, name_en text not null, code text not null,
  created_at timestamptz not null default now(), created_by uuid references auth.users(id), updated_at timestamptz not null default now(), updated_by uuid references auth.users(id),
  archived_at timestamptz, archived_by uuid references auth.users(id), deleted_at timestamptz, deleted_by uuid references auth.users(id), deletion_reason text,
  unique (tenant_id, code)
);
create table public.facilities (
  id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.tenants(id), organization_id uuid not null references public.organizations(id), name_ar text, name_en text not null, code text not null,
  created_at timestamptz not null default now(), created_by uuid references auth.users(id), updated_at timestamptz not null default now(), updated_by uuid references auth.users(id),
  archived_at timestamptz, archived_by uuid references auth.users(id), deleted_at timestamptz, deleted_by uuid references auth.users(id), deletion_reason text,
  unique (tenant_id, organization_id, code)
);
create table public.branches (
  id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.tenants(id), organization_id uuid not null references public.organizations(id), facility_id uuid references public.facilities(id), name_ar text, name_en text not null, code text not null,
  created_at timestamptz not null default now(), created_by uuid references auth.users(id), updated_at timestamptz not null default now(), updated_by uuid references auth.users(id), archived_at timestamptz, archived_by uuid references auth.users(id), deleted_at timestamptz, deleted_by uuid references auth.users(id), deletion_reason text,
  unique (tenant_id, organization_id, code)
);
create table public.departments (
  id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.tenants(id), organization_id uuid not null references public.organizations(id), facility_id uuid references public.facilities(id), name_ar text, name_en text not null, code text not null,
  created_at timestamptz not null default now(), created_by uuid references auth.users(id), updated_at timestamptz not null default now(), updated_by uuid references auth.users(id), archived_at timestamptz, archived_by uuid references auth.users(id), deleted_at timestamptz, deleted_by uuid references auth.users(id), deletion_reason text,
  unique (tenant_id, organization_id, code)
);
create table public.user_profiles (
  id uuid primary key references auth.users(id) on delete cascade, display_name text, preferred_locale text not null default 'ar' check (preferred_locale in ('ar','en')),
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create function public.handle_new_auth_user() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.user_profiles(id,display_name) values(new.id,coalesce(new.raw_user_meta_data->>'full_name',new.email)) on conflict(id) do nothing; return new; end $$;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_auth_user();
create table public.memberships (
  id uuid primary key default gen_random_uuid(), user_id uuid not null references public.user_profiles(id) on delete cascade, tenant_id uuid not null references public.tenants(id), organization_id uuid references public.organizations(id), facility_id uuid references public.facilities(id), active boolean not null default true,
  created_at timestamptz not null default now(), created_by uuid references auth.users(id), updated_at timestamptz not null default now(), updated_by uuid references auth.users(id), archived_at timestamptz, archived_by uuid references auth.users(id), unique(user_id, tenant_id, organization_id, facility_id)
);
create table public.roles (
  id uuid primary key default gen_random_uuid(), key text not null unique, name_ar text not null, name_en text not null, scope_level public.scope_level not null, system_role boolean not null default false,
  created_at timestamptz not null default now(), created_by uuid references auth.users(id), updated_at timestamptz not null default now(), updated_by uuid references auth.users(id), archived_at timestamptz, archived_by uuid references auth.users(id)
);
create table public.permissions (id uuid primary key default gen_random_uuid(), key text not null unique, name_ar text not null, name_en text not null, created_at timestamptz not null default now());
create table public.role_permissions (role_id uuid not null references public.roles(id) on delete cascade, permission_id uuid not null references public.permissions(id) on delete cascade, created_at timestamptz not null default now(), created_by uuid references auth.users(id), primary key(role_id, permission_id));
insert into public.permissions (key,name_ar,name_en) values
 ('platform.full_access','وصول كامل للمنصة','Platform full access'),('platform.manage_modules','إدارة الوحدات','Manage modules'),('platform.manage_forms','إدارة النماذج','Manage forms'),('platform.manage_fields','إدارة الحقول','Manage fields'),('platform.manage_reference_data','إدارة البيانات المرجعية','Manage reference data'),('platform.manage_database_records','إدارة سجلات قاعدة البيانات','Manage database records'),('platform.manage_imports','إدارة الاستيراد','Manage imports'),('platform.manage_exports','إدارة التصدير','Manage exports'),('platform.manage_schema_requests','إدارة طلبات المخطط','Manage schema requests'),('platform.restore_records','استعادة السجلات','Restore records'),('platform.permanently_delete_records','الحذف الدائم للسجلات','Permanently delete records'),('platform.view_audit_logs','عرض سجل التدقيق','View audit logs'),('platform.manage_roles','إدارة الأدوار','Manage roles'),('platform.manage_permissions','إدارة الصلاحيات','Manage permissions'),('platform.manage_branding','إدارة العلامة','Manage branding'),('platform.manage_licensing','إدارة التراخيص','Manage licensing') on conflict(key) do nothing;
insert into public.roles (key,name_ar,name_en,scope_level,system_role) values ('platform_owner','مالك المنصة','Platform Owner','global',true),('organization_administrator','مدير المنظمة','Organization Administrator','organization',true),('facility_administrator','مدير المنشأة','Facility Administrator','facility',true),('scoped_user','مستخدم بنطاق','Scoped User','facility',true) on conflict(key) do nothing;
insert into public.role_permissions(role_id,permission_id) select r.id,p.id from public.roles r cross join public.permissions p where r.key='platform_owner' on conflict do nothing;
create table public.user_role_assignments (
  id uuid primary key default gen_random_uuid(), user_id uuid not null references public.user_profiles(id) on delete cascade, role_id uuid not null references public.roles(id), tenant_id uuid references public.tenants(id), organization_id uuid references public.organizations(id), facility_id uuid references public.facilities(id), active boolean not null default true,
  created_at timestamptz not null default now(), created_by uuid references auth.users(id), updated_at timestamptz not null default now(), updated_by uuid references auth.users(id), archived_at timestamptz, archived_by uuid references auth.users(id), unique(user_id, role_id, tenant_id, organization_id, facility_id)
);
create table public.organization_settings (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.tenants(id), organization_id uuid not null references public.organizations(id), revision integer not null default 1 check(revision > 0), settings jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), created_by uuid references auth.users(id), updated_at timestamptz not null default now(), updated_by uuid references auth.users(id), unique(tenant_id, organization_id));
create table public.branding_settings (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.tenants(id), organization_id uuid references public.organizations(id), facility_id uuid references public.facilities(id), revision integer not null default 1 check(revision > 0), settings jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), created_by uuid references auth.users(id), updated_at timestamptz not null default now(), updated_by uuid references auth.users(id));
create table public.user_preferences (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.user_profiles(id) on delete cascade, tenant_id uuid references public.tenants(id), locale text not null default 'ar' check(locale in ('ar','en')), numeral_system text not null default 'arabic' check(numeral_system in ('arabic','latin')), theme text not null default 'system' check(theme in ('light','dark','system')), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(user_id, tenant_id));
create table public.sessions_metadata (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.user_profiles(id) on delete cascade, session_hash text not null, user_agent text, ip_prefix inet, last_seen_at timestamptz not null default now(), revoked_at timestamptz, created_at timestamptz not null default now(), unique(user_id, session_hash));

create table public.audit_events (id uuid primary key default gen_random_uuid(), tenant_id uuid references public.tenants(id), organization_id uuid references public.organizations(id), facility_id uuid references public.facilities(id), actor_id uuid references public.user_profiles(id), action text not null, entity_type text not null, entity_id uuid, request_id uuid, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), check (not (metadata ?| array['password','token','secret','access_token'])));
create table public.soft_deleted_records (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.tenants(id), organization_id uuid references public.organizations(id), facility_id uuid references public.facilities(id), entity_type text not null, entity_id uuid not null, deleted_at timestamptz not null default now(), deleted_by uuid not null references public.user_profiles(id), deletion_reason text not null, restored_at timestamptz, restored_by uuid references public.user_profiles(id), unique(entity_type, entity_id));

create table public.form_definitions (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.tenants(id), organization_id uuid references public.organizations(id), facility_id uuid references public.facilities(id), module_key text not null, name_ar text, name_en text, description_ar text, description_en text, content_language public.content_language not null default 'bilingual', status public.form_status not null default 'draft', current_version_id uuid, revision integer not null default 1 check(revision > 0), created_at timestamptz not null default now(), created_by uuid references public.user_profiles(id), updated_at timestamptz not null default now(), updated_by uuid references public.user_profiles(id), archived_at timestamptz, archived_by uuid references public.user_profiles(id), deleted_at timestamptz, deleted_by uuid references public.user_profiles(id), deletion_reason text);
create table public.form_versions (id uuid primary key default gen_random_uuid(), form_id uuid not null references public.form_definitions(id) on delete restrict, tenant_id uuid not null references public.tenants(id), organization_id uuid references public.organizations(id), facility_id uuid references public.facilities(id), version_number integer not null check(version_number > 0), status public.form_status not null default 'draft', based_on_version_id uuid references public.form_versions(id), revision integer not null default 1 check(revision > 0), created_at timestamptz not null default now(), created_by uuid references public.user_profiles(id), updated_at timestamptz not null default now(), updated_by uuid references public.user_profiles(id), published_at timestamptz, published_by uuid references public.user_profiles(id), archived_at timestamptz, archived_by uuid references public.user_profiles(id), unique(form_id, version_number));
alter table public.form_definitions add constraint form_definitions_current_version_fk foreign key(current_version_id) references public.form_versions(id) deferrable initially deferred;
create table public.form_sections (id uuid primary key default gen_random_uuid(), form_version_id uuid not null references public.form_versions(id) on delete restrict, tenant_id uuid not null references public.tenants(id), organization_id uuid references public.organizations(id), facility_id uuid references public.facilities(id), title_ar text, title_en text, display_order integer not null check(display_order >= 0), created_at timestamptz not null default now(), created_by uuid references public.user_profiles(id), updated_at timestamptz not null default now(), updated_by uuid references public.user_profiles(id), unique(form_version_id, display_order));
create table public.form_fields (id uuid primary key default gen_random_uuid(), form_section_id uuid references public.form_sections(id) on delete restrict, form_version_id uuid not null references public.form_versions(id) on delete restrict, tenant_id uuid not null references public.tenants(id), organization_id uuid references public.organizations(id), facility_id uuid references public.facilities(id), field_key text not null, type text not null, label_ar text, label_en text, help_text_ar text, help_text_en text, default_value jsonb, validation jsonb not null default '{}'::jsonb, configuration jsonb not null default '{}'::jsonb, required boolean not null default false, read_only boolean not null default false, confidentiality_level text not null default 'normal' check(confidentiality_level in ('normal','confidential','restricted')), searchable boolean not null default true, sortable boolean not null default false, filterable boolean not null default false, exportable boolean not null default true, importable boolean not null default true, display_order integer not null check(display_order >= 0), created_at timestamptz not null default now(), created_by uuid references public.user_profiles(id), updated_at timestamptz not null default now(), updated_by uuid references public.user_profiles(id), unique(form_version_id, field_key), unique(form_version_id, display_order));
create table public.reference_data_groups (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.tenants(id), organization_id uuid references public.organizations(id), facility_id uuid references public.facilities(id), key text not null, name_ar text, name_en text not null, revision integer not null default 1 check(revision > 0), archived_at timestamptz, archived_by uuid references public.user_profiles(id), created_at timestamptz not null default now(), created_by uuid references public.user_profiles(id), updated_at timestamptz not null default now(), updated_by uuid references public.user_profiles(id), unique(tenant_id, organization_id, facility_id, key));
create table public.reference_data_items (id uuid primary key default gen_random_uuid(), group_id uuid not null references public.reference_data_groups(id) on delete restrict, tenant_id uuid not null references public.tenants(id), organization_id uuid references public.organizations(id), facility_id uuid references public.facilities(id), code text not null, label_ar text, label_en text not null, display_order integer not null check(display_order >= 0), active boolean not null default true, revision integer not null default 1 check(revision > 0), archived_at timestamptz, archived_by uuid references public.user_profiles(id), deleted_at timestamptz, deleted_by uuid references public.user_profiles(id), deletion_reason text, created_at timestamptz not null default now(), created_by uuid references public.user_profiles(id), updated_at timestamptz not null default now(), updated_by uuid references public.user_profiles(id), unique(group_id, code), unique(group_id, display_order));
create table public.import_jobs (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.tenants(id), organization_id uuid references public.organizations(id), facility_id uuid references public.facilities(id), requested_by uuid references public.user_profiles(id), format text not null check(format in ('word','excel','csv','json','google_sheets')), mode text not null check(mode in ('create','append','merge','update','replace_draft')), status text not null default 'requested', mapping jsonb not null default '{}'::jsonb, errors jsonb not null default '[]'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.export_jobs (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.tenants(id), organization_id uuid references public.organizations(id), facility_id uuid references public.facilities(id), requested_by uuid references public.user_profiles(id), format text not null check(format in ('excel','csv','json','pdf')), status text not null default 'requested', filters jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.deletion_requests (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.tenants(id), organization_id uuid references public.organizations(id), facility_id uuid references public.facilities(id), entity_type text not null, entity_id uuid not null, requester_id uuid not null references public.user_profiles(id), reason text not null, typed_confirmation text not null, dependencies_checked boolean not null default false, backup_confirmed boolean not null default false, reauthenticated_at timestamptz, second_approval_required boolean not null default false, second_approver_id uuid references public.user_profiles(id), second_approved_at timestamptz, protected_record boolean not null default false, status public.deletion_request_status not null default 'requested', created_at timestamptz not null default now(), updated_at timestamptz not null default now(), check (second_approver_id is null or second_approver_id <> requester_id), check (not protected_record or status <> 'approved'));

create function public.set_updated_at() returns trigger language plpgsql set search_path=public as $$ begin new.updated_at=now(); return new; end $$;
create function public.append_audit_event(event_tenant_id uuid,event_organization_id uuid,event_facility_id uuid,event_action text,event_entity_type text,event_entity_id uuid,event_metadata jsonb default '{}'::jsonb) returns uuid language plpgsql security definer set search_path=public as $$ declare event_id uuid; begin if auth.uid() is null or not public.scope_allowed(event_tenant_id,event_organization_id,event_facility_id) then raise exception 'Audit event is not authorized'; end if; if event_metadata ?| array['password','token','secret','access_token'] then raise exception 'Sensitive audit metadata is prohibited'; end if; insert into public.audit_events(tenant_id,organization_id,facility_id,actor_id,action,entity_type,entity_id,metadata) values(event_tenant_id,event_organization_id,event_facility_id,auth.uid(),event_action,event_entity_type,event_entity_id,event_metadata) returning id into event_id; return event_id; end $$;
create function public.prevent_published_form_mutation() returns trigger language plpgsql set search_path=public as $$ begin if old.status='published' then raise exception 'Published form versions are immutable'; end if; return new; end $$;
create trigger form_versions_immutable before update or delete on public.form_versions for each row execute function public.prevent_published_form_mutation();
create function public.scope_allowed(target_tenant uuid,target_organization uuid,target_facility uuid) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.user_role_assignments ura join public.roles r on r.id=ura.role_id where ura.user_id=auth.uid() and ura.active and r.key='platform_owner' and r.scope_level='global' and ura.tenant_id is null and ura.organization_id is null and ura.facility_id is null) or exists(select 1 from public.memberships m where m.user_id=auth.uid() and m.active and m.tenant_id=target_tenant and (m.organization_id is null or m.organization_id=target_organization) and (m.facility_id is null or m.facility_id=target_facility)); $$;
create function public.has_platform_permission(permission_key text,target_tenant uuid,target_organization uuid,target_facility uuid) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.user_role_assignments ura join public.roles r on r.id=ura.role_id join public.role_permissions rp on rp.role_id=r.id join public.permissions p on p.id=rp.permission_id where ura.user_id=auth.uid() and ura.active and ((r.key='platform_owner' and r.scope_level='global' and ura.tenant_id is null and ura.organization_id is null and ura.facility_id is null and p.key='platform.full_access') or (ura.tenant_id=target_tenant and (ura.organization_id is null or ura.organization_id=target_organization) and (ura.facility_id is null or ura.facility_id=target_facility) and p.key=permission_key))); $$;
create function public.can_manage_forms(target_tenant uuid,target_organization uuid,target_facility uuid) returns boolean language sql stable security definer set search_path=public as $$ select public.scope_allowed(target_tenant,target_organization,target_facility) and (public.has_platform_permission('platform.manage_forms',target_tenant,target_organization,target_facility) or public.has_platform_permission('platform.full_access',target_tenant,target_organization,target_facility)); $$;
create function public.can_manage_reference_data(target_tenant uuid,target_organization uuid,target_facility uuid) returns boolean language sql stable security definer set search_path=public as $$ select public.scope_allowed(target_tenant,target_organization,target_facility) and (public.has_platform_permission('platform.manage_reference_data',target_tenant,target_organization,target_facility) or public.has_platform_permission('platform.full_access',target_tenant,target_organization,target_facility)); $$;
create function public.bootstrap_first_platform_owner(p_user_id uuid,p_tenant_id uuid) returns void language plpgsql security definer set search_path=public,auth as $$ declare owner_role_id uuid; begin if not exists(select 1 from auth.users where id=p_user_id) then raise exception 'Authenticated Supabase user does not exist'; end if; if not exists(select 1 from public.tenants where id=p_tenant_id and deleted_at is null) then raise exception 'Tenant does not exist'; end if; select id into owner_role_id from public.roles where key='platform_owner' and scope_level='global'; if owner_role_id is null then raise exception 'Platform Owner role is missing'; end if; insert into public.user_profiles(id) values(p_user_id) on conflict(id) do nothing; insert into public.user_role_assignments(user_id,role_id,tenant_id,active) values(p_user_id,owner_role_id,null,true) on conflict(user_id,role_id,tenant_id,organization_id,facility_id) do update set active=true; insert into public.audit_events(tenant_id,actor_id,action,entity_type,entity_id,metadata) values(p_tenant_id,p_user_id,'platform_owner.bootstrap','user_profile',p_user_id,jsonb_build_object('source','controlled_bootstrap')); end $$;
revoke all on function public.bootstrap_first_platform_owner(uuid,uuid) from public;

alter table public.tenants enable row level security; alter table public.organizations enable row level security; alter table public.facilities enable row level security; alter table public.branches enable row level security; alter table public.departments enable row level security; alter table public.user_profiles enable row level security; alter table public.memberships enable row level security; alter table public.roles enable row level security; alter table public.permissions enable row level security; alter table public.role_permissions enable row level security; alter table public.user_role_assignments enable row level security; alter table public.organization_settings enable row level security; alter table public.branding_settings enable row level security; alter table public.user_preferences enable row level security; alter table public.sessions_metadata enable row level security; alter table public.audit_events enable row level security; alter table public.soft_deleted_records enable row level security; alter table public.form_definitions enable row level security; alter table public.form_versions enable row level security; alter table public.form_sections enable row level security; alter table public.form_fields enable row level security; alter table public.reference_data_groups enable row level security; alter table public.reference_data_items enable row level security; alter table public.import_jobs enable row level security; alter table public.export_jobs enable row level security; alter table public.deletion_requests enable row level security;

create policy profile_self on public.user_profiles for select using (id=auth.uid()); create policy profile_self_update on public.user_profiles for update using(id=auth.uid()) with check(id=auth.uid());
create policy membership_self on public.memberships for select using(user_id=auth.uid()); create policy preferences_self on public.user_preferences for all using(user_id=auth.uid()) with check(user_id=auth.uid()); create policy sessions_self on public.sessions_metadata for select using(user_id=auth.uid());
create policy tenant_scope on public.tenants for select using(public.scope_allowed(id,null,null)); create policy organization_scope on public.organizations for select using(public.scope_allowed(tenant_id,id,null)); create policy facility_scope on public.facilities for select using(public.scope_allowed(tenant_id,organization_id,id)); create policy branch_scope on public.branches for select using(public.scope_allowed(tenant_id,organization_id,facility_id)); create policy department_scope on public.departments for select using(public.scope_allowed(tenant_id,organization_id,facility_id));
create policy roles_read on public.roles for select using(auth.uid() is not null); create policy permissions_read on public.permissions for select using(auth.uid() is not null); create policy role_permissions_read on public.role_permissions for select using(auth.uid() is not null); create policy role_assignments_self on public.user_role_assignments for select using(user_id=auth.uid());
create policy settings_scope on public.organization_settings for select using(public.scope_allowed(tenant_id,organization_id,null)); create policy branding_scope on public.branding_settings for select using(public.scope_allowed(tenant_id,organization_id,facility_id));
create policy audit_scope on public.audit_events for select using(public.scope_allowed(tenant_id,organization_id,facility_id) and public.has_platform_permission('platform.view_audit_logs',tenant_id,organization_id,facility_id));
create policy deleted_scope on public.soft_deleted_records for select using(public.scope_allowed(tenant_id,organization_id,facility_id));
create policy forms_select on public.form_definitions for select using(public.can_manage_forms(tenant_id,organization_id,facility_id)); create policy forms_write on public.form_definitions for all using(public.can_manage_forms(tenant_id,organization_id,facility_id)) with check(public.can_manage_forms(tenant_id,organization_id,facility_id));
create policy form_versions_select on public.form_versions for select using(public.can_manage_forms(tenant_id,organization_id,facility_id)); create policy form_versions_write on public.form_versions for all using(public.can_manage_forms(tenant_id,organization_id,facility_id)) with check(public.can_manage_forms(tenant_id,organization_id,facility_id));
create policy form_sections_select on public.form_sections for select using(public.can_manage_forms(tenant_id,organization_id,facility_id)); create policy form_sections_write on public.form_sections for all using(public.can_manage_forms(tenant_id,organization_id,facility_id)) with check(public.can_manage_forms(tenant_id,organization_id,facility_id));
create policy form_fields_select on public.form_fields for select using(public.can_manage_forms(tenant_id,organization_id,facility_id)); create policy form_fields_write on public.form_fields for all using(public.can_manage_forms(tenant_id,organization_id,facility_id)) with check(public.can_manage_forms(tenant_id,organization_id,facility_id));
create policy reference_groups_select on public.reference_data_groups for select using(public.can_manage_reference_data(tenant_id,organization_id,facility_id)); create policy reference_groups_write on public.reference_data_groups for all using(public.can_manage_reference_data(tenant_id,organization_id,facility_id)) with check(public.can_manage_reference_data(tenant_id,organization_id,facility_id));
create policy reference_items_select on public.reference_data_items for select using(public.can_manage_reference_data(tenant_id,organization_id,facility_id)); create policy reference_items_write on public.reference_data_items for all using(public.can_manage_reference_data(tenant_id,organization_id,facility_id)) with check(public.can_manage_reference_data(tenant_id,organization_id,facility_id));
create policy imports_scope on public.import_jobs for all using(public.scope_allowed(tenant_id,organization_id,facility_id) and public.has_platform_permission('platform.manage_imports',tenant_id,organization_id,facility_id)) with check(public.scope_allowed(tenant_id,organization_id,facility_id) and public.has_platform_permission('platform.manage_imports',tenant_id,organization_id,facility_id));
create policy exports_scope on public.export_jobs for all using(public.scope_allowed(tenant_id,organization_id,facility_id) and public.has_platform_permission('platform.manage_exports',tenant_id,organization_id,facility_id)) with check(public.scope_allowed(tenant_id,organization_id,facility_id) and public.has_platform_permission('platform.manage_exports',tenant_id,organization_id,facility_id));
create policy deletion_scope on public.deletion_requests for all using(public.scope_allowed(tenant_id,organization_id,facility_id) and public.has_platform_permission('platform.permanently_delete_records',tenant_id,organization_id,facility_id)) with check(public.scope_allowed(tenant_id,organization_id,facility_id) and public.has_platform_permission('platform.permanently_delete_records',tenant_id,organization_id,facility_id));
